# claude_learning_kernel/claude_learning_kernel.pyi — typed stub for the
# INNER extension module (the `.so` itself), as resolved by the
# `claude_learning_kernel.claude_learning_kernel` import form (the aco
# bridge). Without it, that form falls to the untyped `.so` and Pyright
# measures nothing (measured by the d4, 24/09/2026: the package-level
# `__init__.pyi` covers only the package — the inner module's names were
# invisible to the checker).
#
# Same fidelity contract as the package stub: the parity guard
# (`scripts/test_clk_stub_parity.py`) asserts the declared names equal this
# module's runtime `dir()` AND that `__all__` equals the runtime's
# `__all__` — never the public set (which would omit `__version__` and add
# the package's submodule attribute).

from __future__ import annotations

from typing import Any, Optional

__version__: str

# The runtime `__all__` (measured): the extension's own public names +
# `__version__` — 62 entries, exactly as the module exports it.
__all__ = [
    "AcoGraph", "AcoGraphError", "AcoValidationError", "AstParseError",
    "AstSurgeryError", "AstSymbol", "CRITICAL_WEIGHT", "DimResult",
    "EventBuffer", "EventProjector", "FEATURE_DIM", "GeneratorNode",
    "HALT_ITERATIONS", "HALT_THRESHOLD", "KeywordMatcher", "NORMAL_WEIGHT",
    "NUM_ARMS", "PyChunkerConfig", "PyKeywordMatch", "PyMatcherConfig",
    "PyMonetaryValue", "PySemanticChunk", "QueryCache", "SerializationError",
    "TrackerReport", "TrackerStatus", "VETO_THRESHOLD", "__version__",
    "compute_rl_state", "get_best_action", "get_linucb_arm_stats",
    "get_q_value", "process_reward", "py_analyze_concession",
    "py_build_report", "py_chunk_document", "py_chunk_documents_batch",
    "py_compute_complexity", "py_compute_composite", "py_determine_status",
    "py_extract_imports", "py_extract_symbols", "py_extract_symbols_from_file",
    "py_irr", "py_levenshtein_distance", "py_mcts_search", "py_npv",
    "py_npv_batch", "py_parse_monetary", "py_parse_monetary_batch",
    "py_supported_languages", "py_validate_syntax", "py_viability_verdict",
    "rust_code_gen_workflow", "rust_format_source", "rust_public_api_surface",
    "rust_semantic_analyze", "rust_workspace_info", "select_arm", "simd",
    "update_arm", "verify_chain_parallel",
]

# ── Constants ──────────────────────────────────────────────────────────────

CRITICAL_WEIGHT: float
NORMAL_WEIGHT: float
HALT_ITERATIONS: int
HALT_THRESHOLD: float
VETO_THRESHOLD: float
FEATURE_DIM: int
NUM_ARMS: int

# ── Exceptions ─────────────────────────────────────────────────────────────

class AcoGraphError(Exception): ...
class AcoValidationError(Exception): ...
class AstParseError(Exception): ...
class AstSurgeryError(Exception): ...
class SerializationError(Exception): ...

# ── ACO core ───────────────────────────────────────────────────────────────

class DimResult:
    dim_id: int
    name: str
    score: float
    details: str
    checks_passed: int
    checks_total: int
    def is_passing_py(self) -> bool: ...
    def weight_py(self) -> float: ...
    def weighted_score_py(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

class TrackerReport:
    iteration: int
    composite: float
    status: str
    dims: list[DimResult]
    def to_json(self) -> str: ...
    def to_dict_json(self) -> str: ...

class TrackerStatus: ...

class AcoGraph:
    def __init__(self) -> None: ...
    def add_node(self, *args: Any, **kwargs: Any) -> Any: ...
    def remove_node(self, *args: Any, **kwargs: Any) -> Any: ...
    def freeze(self) -> None: ...
    def get_all_levels(self) -> Any: ...
    def get_critical_path(self) -> Any: ...
    def topological_sort(self) -> Any: ...
    def validate_acyclic(self) -> Any: ...
    def validate_contracts(self) -> Any: ...
    def validate_dependencies(self) -> Any: ...
    def detect_parallelizable(self) -> Any: ...

class GeneratorNode: ...
class QueryCache: ...
class EventBuffer: ...

class EventProjector:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def load_events(*args: Any, **kwargs: Any) -> Any: ...
    def project_agent_state(self, *args: Any, **kwargs: Any) -> Any: ...
    def replay_since(self, *args: Any, **kwargs: Any) -> Any: ...
    def verify_hash_chain(self, *args: Any, **kwargs: Any) -> Any: ...

def py_build_report(dims: Any, iteration: int) -> TrackerReport: ...
def py_compute_composite(dims: Any) -> float: ...
def py_determine_status(dims: Any, composite: float) -> str: ...
def verify_chain_parallel(events_json: str) -> Any: ...

# ── NLP / monetary / chunking ──────────────────────────────────────────────

class PyMonetaryValue:
    value: float
    currency: str
    multiplier: float
    source_text: str
    position_start: int
    position_end: int
    confidence: float
    context: str
    def __str__(self) -> str: ...

class PyKeywordMatch: ...
class PySemanticChunk: ...
class PyMatcherConfig: ...
class PyChunkerConfig: ...

class KeywordMatcher:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def py_parse_monetary(text: str) -> list[PyMonetaryValue]: ...
def py_parse_monetary_batch(texts: list[str]) -> list[list[PyMonetaryValue]]: ...
def py_chunk_document(*args: Any, **kwargs: Any) -> Any: ...
def py_chunk_documents_batch(*args: Any, **kwargs: Any) -> Any: ...

# ── AST / syntax ───────────────────────────────────────────────────────────

class AstSymbol: ...

def py_extract_symbols(source: str, *args: Any, **kwargs: Any) -> Any: ...
def py_extract_symbols_from_file(path: str, *args: Any, **kwargs: Any) -> Any: ...
def py_extract_imports(source: str, *args: Any, **kwargs: Any) -> Any: ...
def py_compute_complexity(source: str, *args: Any, **kwargs: Any) -> float: ...
def py_validate_syntax(source: str, *args: Any, **kwargs: Any) -> Any: ...
def py_supported_languages() -> list[str]: ...
def py_levenshtein_distance(a: str, b: str) -> int: ...

# ── RL ─────────────────────────────────────────────────────────────────────

def compute_rl_state(*args: Any, **kwargs: Any) -> Any: ...
def get_best_action(*args: Any, **kwargs: Any) -> Any: ...
def get_linucb_arm_stats(*args: Any, **kwargs: Any) -> Any: ...
def get_q_value(*args: Any, **kwargs: Any) -> float: ...
def process_reward(*args: Any, **kwargs: Any) -> Any: ...
def select_arm(*args: Any, **kwargs: Any) -> Any: ...
def update_arm(*args: Any, **kwargs: Any) -> Any: ...

# ── Cognitive / MCTS ───────────────────────────────────────────────────────

def py_mcts_search(*args: Any, **kwargs: Any) -> Any: ...

# ── Financial ──────────────────────────────────────────────────────────────

def py_npv(*args: Any, **kwargs: Any) -> float: ...
def py_npv_batch(*args: Any, **kwargs: Any) -> list[float]: ...
def py_irr(*args: Any, **kwargs: Any) -> float: ...
def py_analyze_concession(*args: Any, **kwargs: Any) -> Any: ...
def py_viability_verdict(*args: Any, **kwargs: Any) -> Any: ...

# ── Deep Rust semantic (syn) ───────────────────────────────────────────────

def rust_semantic_analyze(*args: Any, **kwargs: Any) -> Any: ...
def rust_format_source(source: str) -> str: ...
def rust_workspace_info(*args: Any, **kwargs: Any) -> Any: ...
def rust_public_api_surface(*args: Any, **kwargs: Any) -> Any: ...
def rust_code_gen_workflow(*args: Any, **kwargs: Any) -> Any: ...

# ── The `simd` submodule ───────────────────────────────────────────────────

class simd:
    """`claude_learning_kernel.simd` — the registered submodule."""

    class CosineComputer:
        def __init__(self) -> None: ...
        def cosine(self, a: list[float], b: list[float]) -> float: ...
        def cosine_batch(self, *args: Any, **kwargs: Any) -> Any: ...

    class WilsonRanker:
        def __init__(self) -> None: ...
        def wilson_score(self, successes: int, total: int) -> float: ...
        def wilson_scores_batch(self, data: list[tuple[int, int]]) -> list[float]: ...

    class DriftDetector:
        def __init__(self) -> None: ...
        def ks_statistic(self, sample1: list[float], sample2: list[float]) -> float: ...
        def js_divergence(self, dist1: list[float], dist2: list[float]) -> float: ...

    @staticmethod
    def py_cosine_similarity(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def py_rank_by_wilson(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def py_has_significant_drift(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def py_weighted_mean(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def py_coefficient_of_variation(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def py_bayesian_fusion(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def py_reconcile_weighted(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def py_npv(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def py_npv_batch(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def py_irr(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def py_stress_scenarios(*args: Any, **kwargs: Any) -> Any: ...
