//! Wave T1 — `cargo-mutants` wrapper for the touring quality stack.
//!
//! Drives the external `cargo-mutants` binary, parses the
//! `mutants.out/outcomes.json` artifact, and exposes a stable
//! [`MutationReport`] for downstream consumers (R1 repo-score Testing
//! category, T2 CI gate, MCP tool, etc.).
//!
//! # Architecture
//!
//! - [`MutationConfig`] is the input contract (workspace, package filter,
//!   threshold, timeouts, parallelism).
//! - [`MutationReport`] is the deterministic output (counts + kill_rate +
//!   passed_threshold flag).
//! - [`run_mutation_test`] orchestrates `cargo mutants` execution and
//!   reads `outcomes.json` from the produced output directory.
//! - [`parse_outcomes_json`] is the file-only parser — testable without
//!   cargo-mutants installed (mock-friendly).
//! - [`compute_kill_rate`] is pure arithmetic — exhaustively unit-tested.
//! - [`cache_load`] / [`cache_store`] persist reports under
//!   `<cache_root>/mutation-test/<package>.json` keyed by
//!   `(workspace_hash, source_fingerprint)`.
//!
//! # Failure mode
//!
//! When `cargo-mutants` is absent, [`run_mutation_test`] returns
//! `Err(MutationError::BinaryNotFound)` so callers (CI gates, repo-score)
//! can degrade gracefully instead of panicking.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::Instant;

use serde::{Deserialize, Serialize};

// ─────────────────────────────────────────────────────────────────────────────
// Public types
// ─────────────────────────────────────────────────────────────────────────────

/// Inputs for a mutation test run. Defaults via [`MutationConfig::new`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MutationConfig {
    /// Absolute path to the cargo workspace root (must contain Cargo.toml).
    pub workspace: PathBuf,
    /// Optional `--package` filter (None = whole workspace).
    pub package: Option<String>,
    /// Per-mutant test timeout in seconds (passed as `--timeout`).
    pub timeout_secs: u32,
    /// Parallel jobs (passed as `--jobs`); defaults to physical cores.
    pub jobs: u32,
    /// Kill-rate threshold in percent `[0.0, 100.0]` (e.g. 80.0 = 80% killed).
    pub threshold: f32,
    /// Optional output dir override (cargo-mutants writes `mutants.out/` here).
    /// Defaults to `<workspace>/target/mutants/<package_or_all>`.
    pub output_dir: Option<PathBuf>,
}

impl MutationConfig {
    /// Construct a config with sensible defaults: 60s per-mutant timeout,
    /// physical-core jobs, 80% threshold, default output dir.
    #[must_use]
    pub fn new(workspace: PathBuf) -> Self {
        Self {
            workspace,
            package: None,
            timeout_secs: 60,
            jobs: physical_cores(),
            threshold: 80.0,
            output_dir: None,
        }
    }

    /// Resolve the effective output directory for this config.
    #[must_use]
    pub fn resolved_output_dir(&self) -> PathBuf {
        if let Some(dir) = &self.output_dir {
            return dir.clone();
        }
        let leaf = self.package.clone().unwrap_or_else(|| "all".to_string());
        self.workspace.join("target").join("mutants").join(leaf)
    }
}

/// Deterministic outcome of a mutation test run.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MutationReport {
    /// Total mutants generated by cargo-mutants (caught + missed + timeout + unviable).
    pub mutants_total: u32,
    /// Mutants caught by the test suite (a test failed when this mutant ran).
    pub mutants_killed: u32,
    /// Mutants survived (no test failed — gap in coverage).
    pub mutants_survived: u32,
    /// Mutants that timed out (counted as caught for kill_rate).
    pub mutants_timeout: u32,
    /// Mutants that failed to compile (excluded from kill_rate denominator).
    pub mutants_unviable: u32,
    /// `(killed + timeout) / (killed + timeout + survived)` in percent `[0,100]`.
    pub kill_rate: f32,
    /// Wall-clock elapsed seconds for the run.
    pub elapsed_secs: u64,
    /// `kill_rate >= threshold`.
    pub passed_threshold: bool,
    /// Threshold used during this run (for downstream context).
    pub threshold: f32,
    /// Package filter used during this run (None = whole workspace).
    pub package: Option<String>,
    /// `cargo-mutants` version reported by the outcomes artifact.
    pub cargo_mutants_version: String,
}

/// Errors surfaced by the wrapper. Conservative variants — callers can
/// degrade per-variant (e.g. `BinaryNotFound` → skip gate, log warning).
#[derive(Debug, thiserror::Error)]
pub enum MutationError {
    /// `cargo-mutants` binary missing from PATH.
    #[error("cargo-mutants binary not found on PATH (install: cargo install cargo-mutants)")]
    BinaryNotFound,
    /// `cargo mutants` exited with a non-zero status that we couldn't classify.
    /// Note: cargo-mutants returns non-zero when MissedMutant exists — that
    /// is normal and parsed as `passed_threshold=false`, not an error.
    #[error("cargo-mutants exit failed (status={status:?}): {stderr}")]
    ExitFailed {
        /// Process exit status code, if the process exited normally.
        status: Option<i32>,
        /// Captured standard error output for diagnosis.
        stderr: String,
    },
    /// `outcomes.json` missing after a run (cargo-mutants likely crashed pre-emit).
    #[error("outcomes.json missing at expected path: {0}")]
    OutcomesMissing(PathBuf),
    /// `outcomes.json` could not be parsed as the expected schema.
    #[error("outcomes.json parse error at {path}: {source}")]
    OutcomesParse {
        /// Path to the `outcomes.json` file that failed to parse.
        path: PathBuf,
        /// The underlying deserialization error.
        #[source]
        source: serde_json::Error,
    },
    /// Filesystem error (cache I/O, dir creation, etc.).
    #[error("filesystem error: {0}")]
    Io(#[from] std::io::Error),
    /// The artifact records no viable mutant, so nothing was measured.
    ///
    /// A run that generates zero testable mutants is a FAILED run, not a
    /// passing one: `compute_kill_rate` yields 0.0 for an empty denominator,
    /// and returning that as a report lets a dead harness read as a measured
    /// score. Origin (2026-08-20): the workspace baseline died on the
    /// iai-callgrind bench target for months, emitting `total_mutants: 0`
    /// while the CLI answered `ok: true` and `repo-score` scored its "testing"
    /// category from that zero.
    #[error(
        "no viable mutants at {path} (total={total}, unviable={unviable}) — \
         the run produced nothing to measure; check the cargo-mutants baseline"
    )]
    NoViableMutants {
        /// Path to the `outcomes.json` that carried no viable mutant.
        path: PathBuf,
        /// Total mutants the artifact reports (may be 0 or all-unviable).
        total: u32,
        /// Mutants that failed to compile, hence never testable.
        unviable: u32,
    },
}

/// Convenience alias matching the rest of the touring codebase.
pub type Result<T> = std::result::Result<T, MutationError>;

// ─────────────────────────────────────────────────────────────────────────────
// outcomes.json schema (private — only what we consume)
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
struct OutcomesArtifact {
    #[serde(default)]
    total_mutants: u32,
    #[serde(default)]
    caught: u32,
    #[serde(default)]
    missed: u32,
    #[serde(default)]
    timeout: u32,
    #[serde(default)]
    unviable: u32,
    #[serde(default)]
    cargo_mutants_version: String,
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/// Compute the canonical kill_rate from the four outcome counts.
///
/// `kill_rate = (killed + timeout) / (killed + timeout + survived)` in percent.
/// `unviable` mutants are excluded from the denominator (they never compiled,
/// so the test suite had no opportunity to detect them).
///
/// Returns 0.0 when the denominator is zero (no testable mutants generated).
#[must_use]
pub fn compute_kill_rate(killed: u32, survived: u32, timeout: u32) -> f32 {
    let detected = killed.saturating_add(timeout);
    let denom = detected.saturating_add(survived);
    if denom == 0 {
        return 0.0;
    }
    let pct = (f64::from(detected) / f64::from(denom)) * 100.0;
    // Clamp to a sane numeric range; arithmetic above guarantees [0, 100].
    pct.clamp(0.0, 100.0) as f32
}

/// Parse a `mutants.out/outcomes.json` file into a [`MutationReport`].
///
/// `threshold` and `package` are stamped into the report for context — they
/// are not validated against the file contents.
///
/// # Errors
///
/// - [`MutationError::OutcomesMissing`] if the file does not exist.
/// - [`MutationError::OutcomesParse`] if the JSON does not match the schema.
pub fn parse_outcomes_json(
    path: &Path,
    threshold: f32,
    package: Option<String>,
    elapsed_secs: u64,
) -> Result<MutationReport> {
    if !path.exists() {
        return Err(MutationError::OutcomesMissing(path.to_path_buf()));
    }
    let bytes = fs::read(path)?;
    let artifact: OutcomesArtifact =
        serde_json::from_slice(&bytes).map_err(|e| MutationError::OutcomesParse {
            path: path.to_path_buf(),
            source: e,
        })?;

    // A zero denominator is the absence of a measurement, never a score of
    // zero — fail loudly instead of handing back a report the caller cannot
    // distinguish from a real one. The same rule is applied to the CACHE path
    // in `cache_load`; both call `has_measurement` so a third caller cannot
    // diverge from the definition.
    if artifact
        .caught
        .saturating_add(artifact.timeout)
        .saturating_add(artifact.missed)
        == 0
    {
        return Err(MutationError::NoViableMutants {
            path: path.to_path_buf(),
            total: artifact.total_mutants,
            unviable: artifact.unviable,
        });
    }

    let kill_rate = compute_kill_rate(artifact.caught, artifact.missed, artifact.timeout);
    let passed_threshold = kill_rate >= threshold;

    Ok(MutationReport {
        mutants_total: artifact.total_mutants,
        mutants_killed: artifact.caught,
        mutants_survived: artifact.missed,
        mutants_timeout: artifact.timeout,
        mutants_unviable: artifact.unviable,
        kill_rate,
        elapsed_secs,
        passed_threshold,
        threshold,
        package,
        cargo_mutants_version: artifact.cargo_mutants_version,
    })
}

/// Run `cargo mutants` end-to-end and return a [`MutationReport`].
///
/// Side effects:
/// - Spawns `cargo mutants` with the configured package/timeout/jobs.
/// - Writes the `mutants.out/` artifact under `config.resolved_output_dir()`.
/// - Returns parsed outcomes (caller decides whether to cache).
///
/// # Errors
///
/// - [`MutationError::BinaryNotFound`] if `cargo-mutants` is not installed.
/// - [`MutationError::ExitFailed`] if cargo itself errored (workspace broken).
/// - [`MutationError::OutcomesMissing`] / [`MutationError::OutcomesParse`] on artifact problems.
pub fn run_mutation_test(config: &MutationConfig) -> Result<MutationReport> {
    if !cargo_mutants_available() {
        return Err(MutationError::BinaryNotFound);
    }

    let out_dir = config.resolved_output_dir();
    fs::create_dir_all(&out_dir)?;

    let started = Instant::now();
    let mut cmd = Command::new("cargo");
    cmd.arg("mutants")
        .arg("--no-shuffle")
        .arg("--output")
        .arg(&out_dir)
        .arg("--timeout")
        .arg(config.timeout_secs.to_string())
        .arg("--jobs")
        .arg(config.jobs.to_string());
    if let Some(pkg) = &config.package {
        cmd.arg("-p").arg(pkg);
    }
    cmd.current_dir(&config.workspace);

    let output = cmd.output().map_err(|e| {
        if e.kind() == std::io::ErrorKind::NotFound {
            MutationError::BinaryNotFound
        } else {
            MutationError::Io(e)
        }
    })?;

    // cargo-mutants exits non-zero when MissedMutant exists. That's not a
    // wrapper error — we still parse outcomes.json. Only hard-classify a
    // failure when outcomes.json is absent AND status is non-zero.
    let outcomes = out_dir.join("mutants.out").join("outcomes.json");
    if !outcomes.exists() && !output.status.success() {
        return Err(MutationError::ExitFailed {
            status: output.status.code(),
            stderr: String::from_utf8_lossy(&output.stderr).to_string(),
        });
    }

    let elapsed = started.elapsed().as_secs();
    parse_outcomes_json(&outcomes, config.threshold, config.package.clone(), elapsed)
}

// ─────────────────────────────────────────────────────────────────────────────
// Cache
// ─────────────────────────────────────────────────────────────────────────────

/// Stale threshold for the on-disk cache (7 days, per T1 spec).
pub const CACHE_STALE_SECS: u64 = 7 * 24 * 60 * 60;

/// Resolve the cache file for a given package under the touring cache root.
/// `package = None` collapses to `"_workspace"`.
#[must_use]
pub fn cache_path(cache_root: &Path, package: Option<&str>) -> PathBuf {
    let leaf = package.unwrap_or("_workspace");
    cache_root
        .join("mutation-test")
        .join(format!("{leaf}.json"))
}

impl MutationReport {
    /// Whether this report represents an actual measurement.
    ///
    /// False when no mutant was testable: `caught + timeout + survived == 0`.
    /// `unviable` is excluded — a mutant that never compiled was never a test.
    ///
    /// 2026-08-20: `parse_outcomes_json` rejected this case and the CACHE path
    /// did not, so a stored report with `mutants_total: 0` was served straight
    /// back as `ok: true` — and the cache is consulted FIRST, which made the
    /// unguarded path the one that actually ran.
    #[must_use]
    pub fn has_measurement(&self) -> bool {
        self.mutants_killed
            .saturating_add(self.mutants_timeout)
            .saturating_add(self.mutants_survived)
            > 0
    }
}

/// Load a cached [`MutationReport`] when present and fresh (≤ 7 days).
///
/// Returns `Ok(None)` for missing or stale entries (caller re-runs).
///
/// # Errors
///
/// Returns [`MutationError::OutcomesParse`] when the cache file exists but
/// is corrupt — caller may delete it and re-run.
pub fn cache_load(cache_root: &Path, package: Option<&str>) -> Result<Option<MutationReport>> {
    let path = cache_path(cache_root, package);
    if !path.exists() {
        return Ok(None);
    }
    let metadata = fs::metadata(&path)?;
    if let Ok(modified) = metadata.modified()
        && let Ok(age) = modified.elapsed()
        && age.as_secs() > CACHE_STALE_SECS
    {
        return Ok(None);
    }
    let bytes = fs::read(&path)?;
    let report: MutationReport =
        serde_json::from_slice(&bytes).map_err(|e| MutationError::OutcomesParse {
            path: path.clone(),
            source: e,
        })?;
    // A cached non-measurement is still a non-measurement. Treated as a MISS
    // rather than an error: a stale useless entry should make the caller
    // re-run, not fail. Serving it as `ok: true` is what this guards.
    if !report.has_measurement() {
        return Ok(None);
    }
    Ok(Some(report))
}

/// Persist a [`MutationReport`] to the cache atomically (tempfile + rename).
///
/// # Errors
///
/// Filesystem and serialization failures bubble up via [`MutationError::Io`].
pub fn cache_store(
    cache_root: &Path,
    package: Option<&str>,
    report: &MutationReport,
) -> Result<()> {
    let path = cache_path(cache_root, package);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let bytes = serde_json::to_vec_pretty(report).map_err(|e| MutationError::OutcomesParse {
        path: path.clone(),
        source: e,
    })?;
    let tmp = path.with_extension("json.tmp");
    fs::write(&tmp, &bytes)?;
    fs::rename(&tmp, &path)?;
    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Returns true iff `cargo-mutants` (or `cargo-mutants.exe`) is reachable the
/// way `cargo` itself resolves external subcommands: on PATH, **or** in
/// `$CARGO_HOME/bin` (default `~/.cargo/bin`), which cargo always consults.
///
/// The narrower PATH-only probe refused runs the executor would have
/// completed: on 2026-08-28 a daemon spawned without the cargo dir on PATH
/// answered `binary_not_found` while `cargo mutants` worked from every shell
/// — the verifier must not see less than the executor.
#[must_use]
pub fn cargo_mutants_available() -> bool {
    which_in_path("cargo-mutants").is_some()
        || cargo_home_bin()
            .map(|bin| has_subcommand_in(&bin, "cargo-mutants"))
            .unwrap_or(false)
}

/// `$CARGO_HOME/bin`, falling back to `~/.cargo/bin` — the directory cargo
/// consults for external subcommands regardless of PATH.
fn cargo_home_bin() -> Option<PathBuf> {
    std::env::var_os("CARGO_HOME")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".cargo")))
        .map(|base| base.join("bin"))
}

/// True when `<bin_dir>/<name>` (or the `.exe` variant) exists as a file.
fn has_subcommand_in(bin_dir: &Path, name: &str) -> bool {
    bin_dir.join(name).is_file() || bin_dir.join(format!("{name}.exe")).is_file()
}

fn which_in_path(name: &str) -> Option<PathBuf> {
    let path_var = std::env::var_os("PATH")?;
    for dir in std::env::split_paths(&path_var) {
        let candidate = dir.join(name);
        if candidate.is_file() {
            return Some(candidate);
        }
        // Windows .exe variant — harmless on unix (file won't exist).
        let exe = dir.join(format!("{name}.exe"));
        if exe.is_file() {
            return Some(exe);
        }
    }
    None
}

fn physical_cores() -> u32 {
    // `num_cpus` is already a transitive workspace dep via tokio/rayon ecosystem.
    // Fallback to 1 in pathological environments.
    let n = num_cpus::get_physical();
    u32::try_from(n.max(1)).unwrap_or(1)
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {

    /// A CACHED non-measurement must read as a miss, not as a passing report.
    ///
    /// 2026-08-20, second half of the same defect: `parse_outcomes_json` was
    /// taught to reject `caught + timeout + survived == 0`, and the cache path
    /// was not — so `.touring-cache/mutation-test/_workspace.json` holding
    /// `mutants_total: 0` came straight back as `ok: true, kill_rate: 0.0`.
    /// The cache is consulted FIRST, which made the unguarded path the live
    /// one. Fixing the cold site and leaving the hot one is how the original
    /// zero survived being "fixed".
    #[test]
    fn a_cached_non_measurement_reads_as_a_miss() {
        let dir = tempfile::TempDir::new().unwrap();
        let empty = MutationReport {
            mutants_total: 0,
            mutants_killed: 0,
            mutants_survived: 0,
            mutants_timeout: 0,
            mutants_unviable: 0,
            kill_rate: 0.0,
            elapsed_secs: 1160,
            passed_threshold: false,
            threshold: 80.0,
            package: None,
            cargo_mutants_version: "26.1.2".to_owned(),
        };
        cache_store(dir.path(), None, &empty).unwrap();
        assert!(
            cache_load(dir.path(), None).unwrap().is_none(),
            "a stored report that measured nothing must not be served back"
        );

        // A report with a real measurement still loads.
        let real = MutationReport {
            mutants_total: 134,
            mutants_killed: 105,
            mutants_survived: 1,
            mutants_timeout: 2,
            mutants_unviable: 26,
            kill_rate: 99.1,
            ..empty
        };
        cache_store(dir.path(), None, &real).unwrap();
        assert!(
            cache_load(dir.path(), None).unwrap().is_some(),
            "a real measurement must still be served from cache"
        );
    }

    /// A cache entry older than the TTL must read as a miss.
    ///
    /// `cache_load` has enforced `CACHE_STALE_SECS` (7 days) since it was
    /// written, and until 2026-08-20 nothing tested it — the guard could be
    /// deleted in an edit and every suite would stay green while a months-old
    /// kill-rate was served as current.
    #[test]
    fn cache_load_treats_an_expired_entry_as_a_miss() {
        let dir = tempfile::TempDir::new().unwrap();
        let report = MutationReport {
            mutants_total: 19,
            mutants_killed: 3,
            mutants_survived: 2,
            mutants_timeout: 9,
            mutants_unviable: 5,
            kill_rate: 85.7,
            elapsed_secs: 1160,
            passed_threshold: true,
            threshold: 80.0,
            package: Some("touring-identity".to_owned()),
            cargo_mutants_version: "26.1.2".to_owned(),
        };
        cache_store(dir.path(), Some("touring-identity"), &report).unwrap();

        // Fresh: the entry is served.
        let fresh = cache_load(dir.path(), Some("touring-identity")).unwrap();
        assert!(fresh.is_some(), "a just-written entry must load");

        // Age it one second past the TTL.
        let path = cache_path(dir.path(), Some("touring-identity"));
        let expired =
            std::time::SystemTime::now() - std::time::Duration::from_secs(CACHE_STALE_SECS + 1);
        let f = fs::File::options().write(true).open(&path).unwrap();
        f.set_modified(expired).unwrap();
        drop(f);

        let stale = cache_load(dir.path(), Some("touring-identity")).unwrap();
        assert!(
            stale.is_none(),
            "an entry past CACHE_STALE_SECS must read as a miss, not as a result"
        );
    }
    use super::*;

    /// A run with zero viable mutants is a FAILED run, never a 0% score.
    ///
    /// Mutation-proof for the defect of 2026-08-20: `parse_outcomes_json`
    /// used to return `Ok` here, so a dead baseline reached the caller as a
    /// well-formed report with `kill_rate: 0.0` — indistinguishable from a
    /// suite that genuinely killed nothing.
    #[test]
    fn zero_viable_mutants_is_an_error_not_a_zero_score() {
        let dir =
            std::env::temp_dir().join(format!("touring-mutants-empty-{}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("temp dir");
        let path = dir.join("outcomes.json");
        std::fs::write(
            &path,
            br#"{"outcomes":[],"total_mutants":0,"missed":0,"caught":0,
                "timeout":0,"unviable":0,"success":0}"#,
        )
        .expect("write artifact");

        let err = parse_outcomes_json(&path, 80.0, None, 1160)
            .expect_err("an empty artifact must not parse into a report");
        assert!(
            matches!(err, MutationError::NoViableMutants { total: 0, .. }),
            "expected NoViableMutants, got {err:?}"
        );

        std::fs::remove_file(&path).ok();
        std::fs::remove_dir(&dir).ok();
    }

    /// All-unviable is the same absence: nothing compiled, nothing was tested.
    #[test]
    fn all_unviable_is_also_an_error() {
        let dir =
            std::env::temp_dir().join(format!("touring-mutants-unviable-{}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("temp dir");
        let path = dir.join("outcomes.json");
        std::fs::write(
            &path,
            br#"{"outcomes":[],"total_mutants":7,"missed":0,"caught":0,
                "timeout":0,"unviable":7,"success":0}"#,
        )
        .expect("write artifact");

        let err = parse_outcomes_json(&path, 80.0, None, 42)
            .expect_err("all-unviable must not parse into a report");
        assert!(matches!(
            err,
            MutationError::NoViableMutants {
                total: 7,
                unviable: 7,
                ..
            }
        ));

        std::fs::remove_file(&path).ok();
        std::fs::remove_dir(&dir).ok();
    }

    use serial_test::serial;
    use std::io::Write;
    use tempfile::TempDir;

    fn write_outcomes(dir: &Path, body: &str) -> PathBuf {
        let path = dir.join("outcomes.json");
        let mut f = fs::File::create(&path).unwrap();
        f.write_all(body.as_bytes()).unwrap();
        path
    }

    #[test]
    fn kill_rate_zero_when_no_mutants() {
        assert_eq!(compute_kill_rate(0, 0, 0), 0.0);
    }

    #[test]
    fn kill_rate_unviable_excluded() {
        // 8 caught + 2 missed = 10 testable; unviable doesn't enter.
        assert!((compute_kill_rate(8, 2, 0) - 80.0).abs() < f32::EPSILON);
    }

    #[test]
    fn kill_rate_timeout_counts_as_killed() {
        // 6 caught + 4 timeout = 10 detected; 0 missed → 100%.
        assert!((compute_kill_rate(6, 0, 4) - 100.0).abs() < f32::EPSILON);
    }

    #[test]
    fn kill_rate_partial() {
        // 5 caught + 5 missed = 50%.
        assert!((compute_kill_rate(5, 5, 0) - 50.0).abs() < f32::EPSILON);
    }

    #[test]
    fn parse_outcomes_canonical_fixture() {
        let dir = TempDir::new().unwrap();
        let body = r#"{
            "outcomes": [],
            "total_mutants": 100,
            "caught": 80,
            "missed": 15,
            "timeout": 3,
            "unviable": 2,
            "cargo_mutants_version": "26.1.2"
        }"#;
        let path = write_outcomes(dir.path(), body);
        let report = parse_outcomes_json(&path, 80.0, Some("touring-ast".into()), 42).unwrap();
        assert_eq!(report.mutants_total, 100);
        assert_eq!(report.mutants_killed, 80);
        assert_eq!(report.mutants_survived, 15);
        assert_eq!(report.mutants_timeout, 3);
        assert_eq!(report.mutants_unviable, 2);
        // (80 + 3) / (80 + 3 + 15) = 83/98 ≈ 84.69%
        assert!((report.kill_rate - 84.693_88).abs() < 0.01);
        assert!(report.passed_threshold); // 84.69 >= 80
        assert_eq!(report.elapsed_secs, 42);
        assert_eq!(report.threshold, 80.0);
        assert_eq!(report.package.as_deref(), Some("touring-ast"));
        assert_eq!(report.cargo_mutants_version, "26.1.2");
    }

    #[test]
    fn parse_outcomes_threshold_fail() {
        let dir = TempDir::new().unwrap();
        let body = r#"{"total_mutants":10,"caught":4,"missed":6,"timeout":0,"unviable":0,"cargo_mutants_version":"26.1.2"}"#;
        let path = write_outcomes(dir.path(), body);
        let report = parse_outcomes_json(&path, 80.0, None, 1).unwrap();
        assert!((report.kill_rate - 40.0).abs() < f32::EPSILON);
        assert!(!report.passed_threshold);
    }

    #[test]
    fn parse_outcomes_missing_fails_gracefully() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("nope.json");
        let err = parse_outcomes_json(&path, 80.0, None, 0).unwrap_err();
        assert!(matches!(err, MutationError::OutcomesMissing(_)));
    }

    #[test]
    fn parse_outcomes_corrupt_fails_with_parse_error() {
        let dir = TempDir::new().unwrap();
        let path = write_outcomes(dir.path(), "{ not valid json");
        let err = parse_outcomes_json(&path, 80.0, None, 0).unwrap_err();
        assert!(matches!(err, MutationError::OutcomesParse { .. }));
    }

    #[test]
    fn config_resolved_output_dir_default() {
        let cfg = MutationConfig::new(PathBuf::from("/ws"));
        assert_eq!(
            cfg.resolved_output_dir(),
            PathBuf::from("/ws/target/mutants/all")
        );
    }

    #[test]
    fn config_resolved_output_dir_with_package() {
        let mut cfg = MutationConfig::new(PathBuf::from("/ws"));
        cfg.package = Some("touring-ast".into());
        assert_eq!(
            cfg.resolved_output_dir(),
            PathBuf::from("/ws/target/mutants/touring-ast")
        );
    }

    #[test]
    fn config_resolved_output_dir_explicit_override() {
        let mut cfg = MutationConfig::new(PathBuf::from("/ws"));
        cfg.output_dir = Some(PathBuf::from("/tmp/custom"));
        assert_eq!(cfg.resolved_output_dir(), PathBuf::from("/tmp/custom"));
    }

    #[test]
    fn cache_roundtrip() {
        let dir = TempDir::new().unwrap();
        let report = MutationReport {
            mutants_total: 50,
            mutants_killed: 40,
            mutants_survived: 8,
            mutants_timeout: 1,
            mutants_unviable: 1,
            kill_rate: 83.67,
            elapsed_secs: 120,
            passed_threshold: true,
            threshold: 80.0,
            package: Some("touring-ast".into()),
            cargo_mutants_version: "26.1.2".into(),
        };
        cache_store(dir.path(), Some("touring-ast"), &report).unwrap();
        let loaded = cache_load(dir.path(), Some("touring-ast"))
            .unwrap()
            .unwrap();
        assert_eq!(loaded, report);
    }

    #[test]
    fn cache_miss_returns_none() {
        let dir = TempDir::new().unwrap();
        assert!(cache_load(dir.path(), Some("nope")).unwrap().is_none());
    }

    #[test]
    fn cache_path_workspace_collapse() {
        let p = cache_path(Path::new("/cache"), None);
        assert_eq!(p, PathBuf::from("/cache/mutation-test/_workspace.json"));
    }

    #[test]
    fn cache_path_per_package() {
        let p = cache_path(Path::new("/cache"), Some("touring-ast"));
        assert_eq!(p, PathBuf::from("/cache/mutation-test/touring-ast.json"));
    }

    /// Mock CI test: when cargo-mutants is absent, `run_mutation_test`
    /// returns `BinaryNotFound` (graceful degradation, no panic).
    /// Simulated by setting PATH to an empty dir.
    #[serial]
    #[test]
    fn ci_mock_no_cargo_mutants_returns_binary_not_found() {
        let dir = TempDir::new().unwrap();
        let original_path = std::env::var_os("PATH");
        // The probe now also consults $CARGO_HOME/bin (the way cargo itself
        // resolves subcommands), so the "absent" scenario must isolate BOTH
        // lookups — on a dev machine ~/.cargo/bin/cargo-mutants exists and an
        // empty PATH alone would still report available.
        let original_cargo_home = std::env::var_os("CARGO_HOME");
        // SAFETY: tests with env mutation must not run in parallel with other
        // tests touching PATH; this one only checks our own helper.
        unsafe {
            std::env::set_var("PATH", dir.path());
            std::env::set_var("CARGO_HOME", dir.path());
        }
        let available = cargo_mutants_available();
        // SAFETY: restore immediately to minimize cross-test contamination.
        unsafe {
            if let Some(p) = original_path {
                std::env::set_var("PATH", p);
            }
            match original_cargo_home {
                Some(v) => std::env::set_var("CARGO_HOME", v),
                None => std::env::remove_var("CARGO_HOME"),
            }
        }
        assert!(
            !available,
            "expected cargo-mutants absent under empty PATH + empty CARGO_HOME"
        );
    }

    /// The pure half of the CARGO_HOME probe: a file named like the
    /// subcommand (or its .exe variant) in the bin dir is found; an empty
    /// dir is not. No env mutation — the env-resolving wrapper is covered
    /// by `ci_mock_no_cargo_mutants_returns_binary_not_found`.
    #[test]
    fn cargo_home_bin_probe_finds_the_subcommand_file() {
        let dir = TempDir::new().unwrap();
        assert!(!has_subcommand_in(dir.path(), "cargo-mutants"));
        std::fs::write(dir.path().join("cargo-mutants"), b"").unwrap();
        assert!(has_subcommand_in(dir.path(), "cargo-mutants"));
        let dir2 = TempDir::new().unwrap();
        std::fs::write(dir2.path().join("cargo-mutants.exe"), b"").unwrap();
        assert!(
            has_subcommand_in(dir2.path(), "cargo-mutants"),
            "the .exe variant must also be found"
        );
    }
}
