//! `touring-hooks` — Façade re-exports for the 8 split sub-crates.
//!
//! Auto-generated by w8_hooks_facade_emitter.py (W8.6).
//! DO NOT add direct code here — extend the relevant sub-crate instead.

#![forbid(unsafe_code)]
#![deny(missing_docs)]

pub use touring_hooks_infra as infra;
pub use touring_hooks_lifecycle as lifecycle;
pub use touring_hooks_rl as rl;
pub use touring_hooks_prediction as prediction;
pub use touring_hooks_core as core;
pub use touring_hooks_tools as tools;
pub use touring_hooks_cli as cli;
pub use touring_hooks_shared as shared;

/// Crate version (semver-compatible with workspace).
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
