"""Target-crate and current-crate registry (13 target crates, 46 current crates).

Extracted from generate_plan.py:168-411. CRATES_TARGET is the canonical post-
refactor 13-crate topology; CRATES_CURRENT records each existing crate's
disposition (KEEP / FUSE_INTO_X / SPLIT_INTO_X / DELETE).
"""
from __future__ import annotations

from .dataclasses import CrateCurrent, CrateTarget

# ─── DATA: target crates (13) ─────────────────────────────────────────────────


CRATES_TARGET: list[CrateTarget] = [
    CrateTarget(
        name="touring-foundation",
        layer=1,
        modules=["alloc", "cgm", "char_classes", "checkpoint", "chunker", "config",
                 "conflict", "diagnostic", "drift", "failover", "feedback", "governor",
                 "hash", "health", "migration", "plugin", "profile", "schema", "security",
                 "shared", "shutdown", "telemetry", "sentinel", "rules", "definitions",
                 "activity"],
        public_api=["Config", "Diagnostic", "Health", "PluginRegistry", "Profile",
                    "Schema", "Sentinel", "RuleEngine", "ActivityLog", "Telemetry"],
        features=["tracing-otel", "tracing-jaeger", "gpu-embeddings",
                  "mimalloc-allocator", "sentinel-psi", "rules-eval"],
        internal_deps=[],
        loc_src_target=18_000,
        loc_test_target=4_000,
        pub_target=250,
        absorves=["touring-core (rename+slim)", "touring-rule-engine",
                  "touring-definitions", "touring-telemetry",
                  "touring-resource-monitor", "touring-activity"],
        notes="Zero deps in touring-*; configures everything. Layer 1.",
    ),
    CrateTarget(
        name="touring-simd",
        layer=2,
        modules=["aco", "cosine", "gpu", "u4_dot", "quantize", "bitvec", "mask"],
        public_api=["CosineComputer", "BitVec", "U4DotProduct", "AcoPheromone"],
        features=["gpu-cuda", "gpu-vulkan", "gpu-metal", "simd-avx2",
                  "simd-avx512", "simd-neon"],
        internal_deps=["touring-foundation"],
        loc_src_target=9_000,
        loc_test_target=2_000,
        pub_target=170,
        notes="SIMD primitives + GPU u4_dot. Layer 2 Kernel.",
    ),
    CrateTarget(
        name="touring-rkyv",
        layer=2,
        modules=["transport", "wire", "magic", "dispatch"],
        public_api=["WireFormat", "MagicHeader", "DispatchTable", "IpcMessage"],
        features=["bincode-fallback", "compression-zstd"],
        internal_deps=["touring-foundation"],
        loc_src_target=1_500,
        loc_test_target=600,
        pub_target=40,
        notes="Zero-copy IPC transport. Layer 2 Kernel.",
    ),
    CrateTarget(
        name="touring-identity",
        layer=2,
        modules=["registry", "schema", "types", "criterion", "resolution"],
        public_api=["EntityId", "EntityKind", "Criterion", "Resolution",
                    "Registry", "MatchKind"],
        features=[],
        internal_deps=["touring-foundation"],
        loc_src_target=2_000,
        loc_test_target=600,
        pub_target=30,
        notes="RFC-004 Entity Registry. Layer 2 Kernel.",
    ),
    CrateTarget(
        name="touring-code",
        layer=3,
        modules=["parsers/tree_sitter", "parsers/ast_grep", "parsers/syn",
                 "languages", "semantics", "graph", "format", "complexity",
                 "incremental"],
        public_api=["Parser", "Lang", "Tier", "Definition", "Symbol", "Visitor",
                    "Surgery", "ComplexityMetrics", "SemanticSearch"],
        features=["lang-rust", "lang-typescript", "lang-python", "lang-go",
                  "lang-ruby", "lang-java", "lang-cpp",
                  "parser-tree-sitter", "parser-ast-grep", "parser-syn",
                  "semantic-search", "incremental-salsa"],
        internal_deps=["touring-foundation", "touring-simd", "touring-identity"],
        loc_src_target=26_000,
        loc_test_target=6_000,
        pub_target=280,
        absorves=["touring-ast", "touring-ast-polyglot", "touring-language",
                  "touring-semantics"],
        notes="Code intelligence — tree-sitter + ast-grep + syn. Layer 3 Domain Core.",
    ),
    CrateTarget(
        name="touring-storage",
        layer=3,
        modules=["fts", "vec/sqlite", "vec/qdrant", "vec/in_memory",
                 "embeddings/candle", "embeddings/fastembed", "embeddings/voyage",
                 "vfs/mem", "vfs/disk", "salsa", "hybrid_search", "indexer"],
        public_api=["FtsIndex", "VectorStore", "EmbeddingProvider", "Vfs",
                    "SalsaDb", "HybridSearcher", "Indexer"],
        features=["storage-fts", "storage-vec-sqlite", "storage-vec-qdrant",
                  "storage-vec-mem", "storage-emb-candle", "storage-emb-fastembed",
                  "storage-emb-voyage", "storage-vfs-mem", "storage-vfs-disk",
                  "storage-salsa"],
        internal_deps=["touring-foundation"],
        loc_src_target=10_000,
        loc_test_target=2_500,
        pub_target=160,
        absorves=["touring-index", "touring-vfs", "touring-incremental-salsa",
                  "touring-vector-store", "touring-embeddings",
                  "touring-search-fusion"],
        notes="Unified storage layer. Layer 3 Domain Core.",
    ),
    CrateTarget(
        name="touring-analysis",
        layer=3,
        modules=["blast_radius", "quality", "wiring", "health", "temporal",
                 "e2e", "rules", "knowledge", "security", "cache", "report",
                 "pipeline"],
        public_api=["BlastRadius", "QualityReport", "WiringAuditor",
                    "HealthTracker", "E2EHealth", "KnowledgeBase"],
        features=["bench-iai", "cache-moka", "cache-dashmap", "temporal-history"],
        internal_deps=["touring-foundation", "touring-code"],
        loc_src_target=16_000,
        loc_test_target=4_000,
        pub_target=300,
        notes="Analysis — TDG, Halstead, MI, blast, wiring. Layer 3.",
    ),
    CrateTarget(
        name="touring-offensive",
        layer=3,
        modules=["concolic", "erickson", "solver", "vuln", "bug_bounty"],
        public_api=["ConcolicExecutor", "EricksonAttack", "SolverBackend",
                    "VulnReport"],
        features=["solver-z3", "solver-cvc5", "concolic-tracer", "vuln-pattern-db"],
        internal_deps=["touring-foundation", "touring-code"],
        loc_src_target=7_500,
        loc_test_target=2_000,
        pub_target=110,
        notes="Offensive security. Opt-in. Layer 3 Domain Core.",
    ),
    CrateTarget(
        name="touring-intelligence",
        layer=4,
        modules=["reasoning", "rl", "pipeline", "ann"],
        public_api=["Reasoner", "Mcts", "BanditPolicy", "RlAgent", "Pipeline",
                    "FusionScorer", "AnnIndex", "Pensieve", "Predictor"],
        features=["intel-reasoning", "intel-rl", "intel-pipeline", "intel-mcts",
                  "intel-bandit", "intel-aco", "intel-ann", "intel-clustering",
                  "intel-pensieve", "intel-got", "intel-dspy"],
        internal_deps=["touring-foundation", "touring-simd", "touring-code",
                       "touring-storage", "touring-analysis"],
        loc_src_target=90_000,
        loc_test_target=18_000,
        pub_target=1_100,
        absorves=["touring-cognitive", "touring-cortex", "touring-learning",
                  "touring-antt"],
        notes=("Mega-fusion eliminating macrociclo of depth 618. Internal "
               "pub(crate) discipline; external façade is single. Layer 4."),
    ),
    CrateTarget(
        name="touring-generator",
        layer=5,
        modules=["pipeline", "kinds", "vgp", "render", "speculate"],
        public_api=["Generator", "GeneratorKind", "Plan", "Verified", "Rendered",
                    "Speculated", "Committed"],
        features=["generator-rust", "generator-python", "generator-typescript",
                  "generator-tsx", "vgp-strict"],
        internal_deps=["touring-foundation", "touring-code", "touring-analysis",
                       "touring-intelligence", "touring-identity", "touring-rkyv"],
        loc_src_target=13_000,
        loc_test_target=5_000,
        pub_target=290,
        notes="Typestate codegen pipeline, 36 kinds. Layer 5 Application.",
    ),
    CrateTarget(
        name="touring-assists",
        layer=5,
        modules=["auto_wire", "extract_function", "inline_call", "auto_import",
                 "generate_impl", "merge_imports", "change_visibility",
                 "add_missing_match_arms", "move_module_to_file",
                 "convert_to_guarded_return"],
        public_api=["AssistKind", "AssistApplier", "AssistResult"],
        features=["assist-rust", "assist-typescript", "assist-python"],
        internal_deps=["touring-foundation", "touring-code", "touring-analysis"],
        loc_src_target=2_500,
        loc_test_target=700,
        pub_target=75,
        notes="10 assist handlers. Layer 5.",
    ),
    CrateTarget(
        name="touring-orchestration",
        layer=5,
        modules=["flow", "tasks", "decompose", "session", "diary", "devrc"],
        public_api=["Flow", "TaskGraph", "Decompose", "Session", "Diary",
                    "DevRc"],
        features=["flow-dag", "tasks-sqlite", "decompose-mcts", "session-persist"],
        internal_deps=["touring-foundation", "touring-identity"],
        loc_src_target=3_500,
        loc_test_target=900,
        pub_target=80,
        absorves=["touring-flow", "touring-tasksfile", "touring-devrc-adapter"],
        notes="DAG + tasks + session/diary. Layer 5.",
    ),
    CrateTarget(
        name="touring-server",
        layer=6,
        modules=["server-cli", "server-tools", "server-reasoning",
                 "server-session", "server-telemetry", "server-visual"],
        public_api=["Server", "Cli", "ToolRegistry", "Reasoner",
                    "SessionManager"],
        features=["tier-free", "tier-standard", "tier-premium", "tier-enterprise"],
        internal_deps=["ALL"],
        loc_src_target=25_000,
        loc_test_target=6_000,
        pub_target=600,
        notes="Binary + CLI dispatch. 6 internal sub-crates, single external façade.",
    ),
    CrateTarget(
        name="touring-hooks",
        layer=6,
        modules=["hooks-core", "hooks-lifecycle", "hooks-cli", "hooks-tools",
                 "hooks-prediction", "hooks-rl"],
        public_api=["HookHandler", "HookContext", "HookRuntime", "Hook"],
        features=["hooks-claude-code", "hooks-mcp", "hooks-prediction",
                  "hooks-rl", "hooks-cortex"],
        internal_deps=["ALL"],
        loc_src_target=155_000,
        loc_test_target=32_000,
        pub_target=1_500,
        notes="Claude Code interface. 6 internal sub-crates, single external façade.",
    ),
    CrateTarget(
        name="touring-bindings",
        layer=6,
        modules=["bindings-python", "bindings-wasm", "bindings-capnp",
                 "bindings-web", "bindings-desktop", "bindings-postgis"],
        public_api=["BindPython", "BindWasm", "BindCapnp", "BindWeb",
                    "BindDesktop", "BindPostgis"],
        features=["bind-python", "bind-wasm", "bind-capnp", "bind-web",
                  "bind-desktop", "bind-postgis"],
        internal_deps=["ALL"],
        loc_src_target=15_000,
        loc_test_target=3_500,
        pub_target=280,
        absorves=["touring-python", "touring-wasm", "touring-capnp-server",
                  "touring-web", "touring-web-server", "touring-desktop-ui",
                  "touring-geopostgis"],
        notes="Default features empty (opt-in). Layer 6.",
    ),
]


