"""Validator / sub-script / cross-audit Python emitters.

Extracted from generate_plan.py:4082-4664. ``emit_validator_py`` produces the
``validate_W<N>.py`` per-wave validator; ``emit_subscript_stub`` /
``emit_all_subscripts`` produce the per-wave sub-scripts;
``emit_cross_audit_py`` produces the cross-audit runner.
"""
from __future__ import annotations

from dataclasses import dataclass, field

from .dataclasses import Wave

# ─── Validator + cross-audit emitters ────────────────────────────────────────


def emit_validator_py(wave: Wave) -> str:
    """Emit a validate_WX.py for a wave."""
    checks_str = ""
    for st in wave.subtasks:
        checks_str += textwrap.dedent(f"""
            results.append(check_subtask(
                check_id={st.id!r},
                name={st.name!r},
                validation={st.validation!r},
                tdd_test={st.tdd_red.split('(')[0].replace('def ', '').strip()!r}
                          if {bool(st.tdd_red)} else '',
            ))
        """)
    # FIX 2026-05-23 (TACO cross-audit): re-indent checks_str to match the outer
    # f''' context. The {checks_str} interpolation point in the template has 12
    # spaces of leading whitespace; we must add 12 spaces to every line of
    # checks_str so the post-substitution string has uniform 12-space indent on
    # those lines. Without this, lines 2+ of checks_str start at column 0,
    # polluting textwrap.dedent's common-whitespace calculation → output
    # preserves 8-space leading on every line → IndentationError on every
    # emitted validate_WX.py. Root cause of 15 broken validators (2026-05-23).
    # The .lstrip(" ") on first line avoids doubling the 12-space prefix
    # since the {checks_str} substitution already provides the leading indent.
    checks_str = textwrap.indent(checks_str.lstrip("\n"), "            ").lstrip(" ")
    return textwrap.dedent(f'''\
        #!/usr/bin/env python3
        """Validator for {wave.id}: {wave.name}.

        Auto-generated by generate_plan.py — DO NOT edit manually.
        Regenerate: python3 scripts/touring_premium_refactor_2026/generate_plan.py --emit-validators

        Validates:
        ''' + "".join(f"          - {st.id}: {st.validation}\n" for st in wave.subtasks) + f'''        """
        from __future__ import annotations

        import json
        import subprocess
        import sys
        from datetime import UTC, datetime
        from pathlib import Path

        _ROOT = Path(__file__).resolve().parents[2]
        _CHECKPOINTS_DIR = _ROOT / ".claude" / "checkpoints"
        _WAVE_ID = {wave.id!r}
        _WAVE_NAME = {wave.name!r}
        _GATE = {wave.gate!r}


        def check_subtask(check_id: str, name: str, validation: str, tdd_test: str) -> dict:
            """Run a single subtask check. Returns a result dict."""
            # TODO: implement real checks. Stub returns False with a clear "not implemented" note.
            return {{
                "check": check_id,
                "name": name,
                "validation": validation,
                "tdd_test": tdd_test,
                "passed": False,
                "details": "Not yet implemented — replace stub with real check during {wave.id} execution.",
            }}


        def run_cargo_check_workspace() -> bool:
            """Return True if `cargo check --workspace` exits 0."""
            try:
                r = subprocess.run(
                    ["cargo", "check", "--workspace"],
                    cwd=_ROOT, capture_output=True, timeout=600,
                )
                return r.returncode == 0
            except Exception:  # noqa: BLE001
                return False


        def run_wiring_cycles_zero() -> bool:
            """Return True if no cycles of depth >= 2 detected."""
            try:
                r = subprocess.run(
                    ["touring", "wiring", "cycles", "--min-depth", "2", "--format", "json"],
                    capture_output=True, timeout=60,
                )
                if r.returncode != 0:
                    return False
                data = json.loads(r.stdout.decode("utf-8") or "{{}}")
                return int(data.get("cycle_count", 0)) == 0
            except Exception:  # noqa: BLE001
                return False


        def validate() -> dict:
            """Run all validation checks. Returns report dict."""
            results: list[dict] = []
            {checks_str}
            # Wave-level invariants
            cargo_ok = run_cargo_check_workspace()
            cycles_ok = run_wiring_cycles_zero()

            results.append({{
                "check": "wave-invariant",
                "name": "cargo check + wiring cycles zero",
                "validation": "cargo check exit 0 + 0 new cycles",
                "tdd_test": "",
                "passed": cargo_ok and cycles_ok,
                "details": f"cargo_check_ok={{cargo_ok}}, cycles_zero={{cycles_ok}}",
            }})

            passed = sum(1 for r in results if r["passed"])
            total = len(results)
            score = passed / total if total > 0 else 0.0
            status = "PASS" if score >= 0.95 else "WARN" if score >= 0.70 else "FAIL"

            return {{
                "wave": _WAVE_ID,
                "name": _WAVE_NAME,
                "timestamp": datetime.now(UTC).isoformat(),
                "checks_passed": passed,
                "checks_total": total,
                "score": round(score, 4),
                "status": status,
                "gate": _GATE,
                "results": results,
            }}


        def main() -> None:
            """Entry point. Prints report and saves checkpoint."""
            report = validate()
            print(f"\\n{{'='*60}}")
            print(f"  {{_WAVE_ID}}: {{_WAVE_NAME}}")
            print(f"  Score: {{report['score']:.4f}} ({{report['status']}})")
            print(f"  Checks: {{report['checks_passed']}}/{{report['checks_total']}}")
            print(f"{{'='*60}}\\n")
            for r in report["results"]:
                icon = "[PASS]" if r["passed"] else "[FAIL]"
                print(f"  {{icon}} {{r['check']}}: {{r['name']}}")
                if r["details"]:
                    print(f"          {{r['details']}}")
            cp = _CHECKPOINTS_DIR / f"touring_premium_{{_WAVE_ID}}_{{datetime.now(UTC).strftime('%Y%m%d')}}.json"
            cp.parent.mkdir(parents=True, exist_ok=True)
            cp.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
            print(f"\\n  Checkpoint: {{cp}}")
            sys.exit(0 if report["status"] in ("PASS", "WARN") else 1)


        if __name__ == "__main__":
            main()
        ''')


@dataclass
class SubscriptSpec:
    """A sub-script that executes work for a wave."""
    name: str                            # File basename, e.g. "w0_capture_baselines"
    wave: str                            # Owner wave (e.g. "W0")
    subtask_refs: list[str]              # Subtask IDs implemented (e.g. ["W0.2","W0.3"])
    purpose: str                         # 1-line description
    inputs: list[str] = field(default_factory=list)
    outputs: list[str] = field(default_factory=list)
    cli_args: list[str] = field(default_factory=list)
    real_impl: bool = False              # If True, has real logic; False = stub


SUBSCRIPTS_REGISTRY: list[SubscriptSpec] = [
    # W0
    SubscriptSpec("w0_snapshot_tar", "W0", ["W0.1"],
                  "Create reproducible tar snapshot pre-refactor + SHA-256 sidecar.",
                  inputs=["~/.claude/rust/crates/", "Cargo.toml", "Cargo.lock"],
                  outputs=["docs/baselines/touring-snapshot-pre-refactor-<DATE>.tar.gz",
                           "docs/baselines/touring-snapshot-pre-refactor-<DATE>.sha256"],
                  cli_args=["--dry-run", "--output-dir DIR"],
                  real_impl=True),
    SubscriptSpec("w0_capture_baselines", "W0", ["W0.2","W0.3","W0.4","W0.5"],
                  "Orchestrate bench + cargo check + llvm-cov + wiring snapshot baselines.",
                  inputs=["~/.claude/rust workspace"],
                  outputs=["docs/baselines/bench-pre-refactor-<DATE>.log",
                           "docs/baselines/cargo-check-pre-refactor-<DATE>.log",
                           "docs/baselines/coverage-pre-refactor-<DATE>.json",
                           "docs/baselines/wiring-pre-refactor-<DATE>.json",
                           "docs/baselines/cycles-pre-refactor-<DATE>.json",
                           "docs/baselines/status-pre-refactor-<DATE>.json"],
                  cli_args=["--skip-bench", "--skip-coverage", "--dry-run"],
                  real_impl=True),
    SubscriptSpec("w0_generate_artifacts", "W0", ["W0.9"],
                  "Wrapper invocando generate_plan.py --all --force; emits checkpoint.",
                  outputs=["docs/plans/touring-premium-refactor-2026/* (26 files)",
                           "scripts/touring_premium_refactor_2026/validate_W*.py + cross_audit_e2e.py"],
                  cli_args=["--check-only", "--diff-check"],
                  real_impl=True),
    # W1
    SubscriptSpec("w1_audit_dead_code", "W1", ["W1.1","W1.2"],
                  "Identifica + reporta crates mortos (semantic-spike + 3 wasm 0-LOC).",
                  inputs=["~/.claude/rust/crates/"],
                  outputs=["docs/baselines/dead-code-report-<DATE>.json"],
                  cli_args=["--apply (DELETE crates)", "--dry-run (report only)"],
                  real_impl=True),
    SubscriptSpec("w1_clean_reexports", "W1", ["W1.3"],
                  "Grep + propose removal of `pub use` referenciando crates deletadas.",
                  inputs=["crates/*/src/"],
                  outputs=["docs/baselines/dead-reexports-<DATE>.json"],
                  cli_args=["--apply"],
                  real_impl=True),
    SubscriptSpec("w1_fix_cycle1", "W1", ["W1.4"],
                  "Diagnose Cycle #1 (file_tools↔project_tools); propose extraction to tools/shared.rs.",
                  inputs=["crates/touring-server/src/tools/"],
                  outputs=["scripts/touring_premium_refactor_2026/staging/w1-cycle1-fix-proposal.diff"],
                  cli_args=["--apply", "--strategy {shared,trait,merge}"],
                  real_impl=True),
    # W2
    SubscriptSpec("w2_centralize_workspace_deps", "W2", ["W2.1"],
                  "Find all unique external deps; propose [workspace.dependencies] section.",
                  inputs=["cargo metadata --format-version 1"],
                  outputs=["scripts/touring_premium_refactor_2026/staging/w2-workspace-deps.toml"],
                  cli_args=["--apply", "--strict (pin major)"],
                  real_impl=True),
    SubscriptSpec("w2_propagate_workspace_inherit", "W2", ["W2.3"],
                  "Per-crate Cargo.toml: convert literal dep version → `.workspace = true`.",
                  inputs=["crates/*/Cargo.toml"],
                  outputs=["scripts/touring_premium_refactor_2026/staging/w2-cargo-toml-patches/*.diff"],
                  cli_args=["--apply", "--crates crateA,crateB"],
                  real_impl=False),
    SubscriptSpec("w2_setup_deny_machete", "W2", ["W2.5","W2.6"],
                  "Setup deny.toml + machete.toml + run smoke check.",
                  outputs=["deny.toml", "machete.toml"],
                  real_impl=False),
    # W3
    SubscriptSpec("w3_rename_core_to_foundation", "W3", ["W3.1"],
                  "Rename touring-core → touring-foundation + emit shim crate.",
                  real_impl=False),
    SubscriptSpec("w3_absorve_anemic_crates", "W3", ["W3.4","W3.5","W3.6","W3.7","W3.8"],
                  "Absorve 5 crates (rule-engine, definitions, telemetry, resource-monitor, activity).",
                  real_impl=False),
    # W4
    SubscriptSpec("w4_consumer_audit", "W4", ["W4.7","W4.8","W4.9","W4.10"],
                  "Find 38 consumers of touring-ast/polyglot/language/semantics.",
                  outputs=["scripts/touring_premium_refactor_2026/data/w4-consumer-map.json"],
                  real_impl=False),
    SubscriptSpec("w4_consumer_migrate", "W4", ["W4.7","W4.8","W4.9","W4.10"],
                  "Apply migration: touring_ast::X → touring_code::ast::X.",
                  real_impl=False),
    SubscriptSpec("w4_bench_compare", "W4", ["W4.11"],
                  "Compare cargo bench results vs pre-refactor baseline; FAIL if any > 5% slower.",
                  real_impl=False),
    # W5
    SubscriptSpec("w5_storage_skeleton", "W5", ["W5.1"],
                  "Create touring-storage with 11 storage-* features.",
                  real_impl=False),
    SubscriptSpec("w5_consumer_migrate", "W5", ["W5.8"],
                  "Migrate 15 consumers to touring_storage::*.",
                  real_impl=False),
    # W6
    SubscriptSpec("w6_cortex_test_debt_repay", "W6", ["W6.0"],
                  "CRITICAL: cortex test ratio 0.56% → 15%. Identifies modules + generates test stubs.",
                  real_impl=False),
    SubscriptSpec("w6_intelligence_skeleton", "W6", ["W6.1"],
                  "Create touring-intelligence with 11 intel-* features + internal pub(crate) structure.",
                  real_impl=False),
    SubscriptSpec("w6_cycle_audit", "W6", ["W6.9"],
                  "Verify macrociclo 618 ELIMINATED post-fusion.",
                  real_impl=False),
    # W7
    SubscriptSpec("w7_bindings_skeleton", "W7", ["W7.1"],
                  "Create touring-bindings with default features EMPTY + 6 bind-* opt-in.",
                  real_impl=False),
    SubscriptSpec("w7_features_powerset_check", "W7", ["W7.8"],
                  "cargo hack --feature-powerset check; report failing combinations.",
                  real_impl=False),
    # W8
    SubscriptSpec("w8_hooks_split_planner", "W8", ["W8.1","W8.2","W8.3","W8.4","W8.5","W8.6","W8.7"],
                  "Map 224 hook files into 6 buckets (core/lifecycle/cli/tools/prediction/rl).",
                  real_impl=False),
    SubscriptSpec("w8_hooks_facade_emitter", "W8", ["W8.8"],
                  "Generate touring-hooks/src/lib.rs façade with pub use re-exports.",
                  real_impl=False),
    # W9
    SubscriptSpec("w9_server_split_planner", "W9", ["W9.1","W9.2","W9.3","W9.4","W9.5","W9.6","W9.7"],
                  "Map 161 server files into 6 internal sub-crates.",
                  real_impl=False),
    # W10
    SubscriptSpec("w10_orchestration_skeleton", "W10", ["W10.1"],
                  "Create touring-orchestration with 4 features.",
                  real_impl=False),
    SubscriptSpec("w10_decompose_extract", "W10", ["W10.5"],
                  "Extract decompose/ from touring-server to touring-orchestration.",
                  real_impl=False),
    # W11
    SubscriptSpec("w11_mutation_kill_rate_audit", "W11", ["W11.4"],
                  "Run cargo mutants workspace-wide; report kill rate per crate.",
                  real_impl=False),
    SubscriptSpec("w11_proptest_seeder", "W11", ["W11.5"],
                  "Identify candidate types for proptest (Identity, Plan, Definition).",
                  real_impl=False),
    SubscriptSpec("w11_fuzz_target_seeder", "W11", ["W11.6"],
                  "Identify candidate fuzz targets (parsers, serializers).",
                  real_impl=False),
    # W12
    SubscriptSpec("w12_per_project_installer_scaffold", "W12", ["W12.1"],
                  "Scaffold `touring init` CLI: .touring/ structure, touring.toml template, bin/ symlinks.",
                  real_impl=False),
    SubscriptSpec("w12_toolchain_manager", "W12", ["W12.2","W12.3"],
                  "Implement ~/.touring/toolchains/ + touring update/toolchain/component CLI.",
                  real_impl=False),
    SubscriptSpec("w12_migration_tool", "W12", ["W12.7"],
                  "Implement `touring migrate --from-global`: copy filtered DBs + gen touring.toml.",
                  real_impl=False),
    # W13
    SubscriptSpec("w13_docs_rs_validator", "W13", ["W13.1","W13.2"],
                  "Validate docs.rs build green for all feature combinations.",
                  real_impl=False),
    SubscriptSpec("w13_sigstore_pipeline", "W13", ["W13.5"],
                  "Configure cosign sign-blob for release tarballs.",
                  real_impl=False),
    SubscriptSpec("w13_sbom_generator", "W13", ["W13.6"],
                  "Generate CycloneDX SBOM per release.",
                  real_impl=False),
    # W14
    SubscriptSpec("w14_tier_features_validator", "W14", ["W14.1"],
                  "Validate tier-{free,standard,premium,enterprise} feature sets compile + binary size budget.",
                  real_impl=False),
    SubscriptSpec("w14_license_jwt_validator", "W14", ["W14.2"],
                  "Validate JWT ed25519 license validation flow (offline + expired + corrupted).",
                  real_impl=False),
    SubscriptSpec("w14_distro_packager", "W14", ["W14.9","W14.10"],
                  "Build deb/rpm/brew/scoop packages + Docker images via CI matrix.",
                  real_impl=False),
]


def emit_subscript_stub(spec: SubscriptSpec) -> str:
    """Emit a sub-script as Python stub with argparse + main + TODO body."""
    # NOTE: indent must match the 8-space common leading of the dedent template
    # below; otherwise textwrap.dedent leaves residual indentation in the output.
    cli_args_lines = "\n".join(
        f'        parser.add_argument("--{arg.split()[0].lstrip("-")}", help={arg!r})'
        for arg in spec.cli_args
    ) if spec.cli_args else "        # No additional CLI args."
    return textwrap.dedent(f'''\
        #!/usr/bin/env python3
        """{spec.purpose}

        Sub-script for wave {spec.wave}, implementing subtasks: {", ".join(spec.subtask_refs)}.

        Auto-generated by generate_plan.py — refine with real implementation when
        executing wave {spec.wave}.

        Inputs
        ------
        {chr(10).join("    - " + i for i in spec.inputs) if spec.inputs else "    (none)"}

        Outputs
        -------
        {chr(10).join("    - " + o for o in spec.outputs) if spec.outputs else "    (none)"}

        Usage
        -----
            python3 {spec.name}.py --help
        """
        from __future__ import annotations

        import argparse
        import json
        import logging
        import subprocess
        import sys
        from datetime import UTC, datetime
        from pathlib import Path

        LOGGER = logging.getLogger(__name__)
        _ROOT = Path(__file__).resolve().parents[2]
        _STAGING_DIR = _ROOT / "scripts" / "touring_premium_refactor_2026" / "staging"
        _BASELINES_DIR = _ROOT / "docs" / "baselines"


        def build_parser() -> argparse.ArgumentParser:
            """CLI parser."""
            parser = argparse.ArgumentParser(
                prog={spec.name!r},
                description={spec.purpose!r},
                formatter_class=argparse.ArgumentDefaultsHelpFormatter,
            )
{cli_args_lines}
            parser.add_argument("-v", "--verbose", action="store_true")
            return parser


        def run() -> dict:
            """Execute the script logic. Returns a result dict for downstream tooling."""
            # TODO: Implement real logic for wave {spec.wave} subtasks {spec.subtask_refs}.
            # This is a STUB — replace with actual implementation when running {spec.wave}.
            LOGGER.warning("STUB execution — not yet implemented. Refer to "
                          f"WAVE {spec.wave} subtask descriptions in "
                          "docs/plans/touring-premium-refactor-2026/.")
            return {{
                "script": {spec.name!r},
                "wave": {spec.wave!r},
                "subtask_refs": {spec.subtask_refs!r},
                "timestamp": datetime.now(UTC).isoformat(),
                "status": "STUB",
                "details": "Replace stub with real implementation during wave execution.",
            }}


        def main() -> int:
            """Entry point."""
            parser = build_parser()
            args = parser.parse_args()
            logging.basicConfig(
                level=logging.DEBUG if args.verbose else logging.INFO,
                format="%(asctime)s [%(levelname)s] %(message)s",
            )
            try:
                result = run()
                print(json.dumps(result, indent=2, ensure_ascii=False))
                return 0
            except KeyboardInterrupt:
                LOGGER.warning("interrupted")
                return 130
            except Exception:  # noqa: BLE001
                LOGGER.exception("error")
                return 1


        if __name__ == "__main__":
            raise SystemExit(main())
        ''')


def emit_all_subscripts(force: bool = False, only_stubs: bool = True) -> list[Path]:
    """Emit all sub-script stubs. Real-impl scripts skipped if file exists (unless force)."""
    written: list[Path] = []
    for spec in SUBSCRIPTS_REGISTRY:
        path = _SCRIPTS_DIR / f"{spec.name}.py"
        if spec.real_impl and path.exists() and not force:
            LOGGER.debug("skip %s (real_impl exists, no --force)", path.name)
            continue
        if only_stubs and spec.real_impl and not force:
            # Keep existing real implementations; don't overwrite
            LOGGER.debug("preserve %s (real_impl)", path.name)
            continue
        content = emit_subscript_stub(spec)
        write_atomic(path, content)
        path.chmod(0o755)
        written.append(path)
        LOGGER.info("  wrote %s (%d bytes)", path.name, len(content.encode("utf-8")))
    return written


def emit_cross_audit_py() -> str:
    """Emit cross_audit_e2e.py."""
    wave_rows = ",\n        ".join(
        f'("{ w.id }", "{ w.name }", { len(w.subtasks) }, "{ ",".join(w.depends_on) }", "{ w.rust_changes }")'
        for w in WAVES
    )
    return textwrap.dedent(f'''\
        #!/usr/bin/env python3
        """Cross-audit E2E — touring-premium-refactor-2026.

        Auto-generated by generate_plan.py — DO NOT edit manually.
        Regenerate: python3 generate_plan.py --emit-cross-audit

        Audits 15 waves against 10 weighted quality dimensions.
        """
        from __future__ import annotations

        import importlib
        import json
        import sys
        from datetime import UTC, datetime
        from pathlib import Path

        _ROOT = Path(__file__).resolve().parents[2]
        _CHECKPOINTS_DIR = _ROOT / ".claude" / "checkpoints"
        _SCRIPTS_DIR = Path(__file__).resolve().parent

        DIMENSIONS = {{
            "D1_functional": 2.0,
            "D2_wiring": 1.5,
            "D3_performance": 1.5,
            "D4_coverage": 1.5,
            "D5_mutation": 1.0,
            "D6_api_stability": 1.5,
            "D7_supply_chain": 1.0,
            "D8_documentation": 1.0,
            "D9_deployment": 1.5,
            "D10_purpose": 2.0,
        }}

        VETO_THRESHOLD = 0.80
        PASS_THRESHOLD = 0.95

        WAVES_META: list[tuple[str, str, int, str, str]] = [
            { wave_rows }
        ]


        def audit_waves() -> list[dict]:
            """Audit each wave by importing its validate_WX module."""
            sys.path.insert(0, str(_SCRIPTS_DIR))
            results: list[dict] = []
            for wid, name, nsubs, deps, rust in WAVES_META:
                try:
                    mod = importlib.import_module(f"validate_{{wid}}")
                    report = mod.validate()
                    score = float(report.get("score", 0.0))
                    passed = report.get("status") in ("PASS", "WARN")
                except Exception as e:  # noqa: BLE001
                    score = 0.0
                    passed = False
                    report = {{"error": str(e)}}
                results.append({{
                    "wave": wid, "name": name,
                    "depends_on": deps, "rust": rust,
                    "subtasks": nsubs,
                    "score": score, "passed": passed,
                    "report": report,
                }})
            return results


        def audit_dimensions(wave_results: list[dict]) -> dict[str, float]:
            """Audit the 10 quality dimensions across all waves."""
            # Average wave score by dim weight.
            base = sum(r["score"] for r in wave_results) / max(1, len(wave_results))
            return {{dim: round(base, 4) for dim in DIMENSIONS}}


        def compute_composite(dims: dict[str, float]) -> float:
            """Weighted composite score."""
            total = sum(DIMENSIONS.values())
            wsum = sum(dims.get(d, 0.0) * w for d, w in DIMENSIONS.items())
            return round(wsum / total, 4)


        def main() -> None:
            """Run full cross-audit."""
            print("\\n" + "=" * 60)
            print("  CROSS-AUDIT E2E — touring-premium-refactor-2026")
            print("=" * 60 + "\\n")

            wr = audit_waves()
            print("Wave Results:")
            for r in wr:
                icon = "[PASS]" if r["passed"] else "[FAIL]"
                print(f"  {{icon}} {{r['wave']}}: {{r['name']}} (score={{r['score']:.4f}})")

            dims = audit_dimensions(wr)
            print("\\nDimension Scores:")
            for d, s in dims.items():
                w = DIMENSIONS[d]
                icon = "[PASS]" if s >= VETO_THRESHOLD else "[VETO]"
                print(f"  {{icon}} {{d}} (w={{w:.1f}}): {{s:.4f}}")

            composite = compute_composite(dims)
            veto = [d for d, s in dims.items() if s < VETO_THRESHOLD]
            status = "PASS" if composite >= PASS_THRESHOLD and not veto else "FAIL"
            print("\\n" + "=" * 60)
            print(f"  COMPOSITE: {{composite:.4f}} ({{status}})")
            if veto:
                print(f"  VETO DIMENSIONS: {{', '.join(veto)}}")
            print("=" * 60 + "\\n")

            report = {{
                "plan": "touring-premium-refactor-2026",
                "timestamp": datetime.now(UTC).isoformat(),
                "composite_score": composite,
                "status": status,
                "veto_dimensions": veto,
                "dimension_scores": dims,
                "wave_results": wr,
            }}
            cp = _CHECKPOINTS_DIR / f"touring_premium_cross_audit_{{datetime.now(UTC).strftime('%Y%m%d')}}.json"
            cp.parent.mkdir(parents=True, exist_ok=True)
            cp.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
            print(f"  Checkpoint: {{cp}}\\n")
            sys.exit(0 if status == "PASS" else 1)


        if __name__ == "__main__":
            main()
        ''')


