"""conftest for W1 tests.

Generated by TACO-wt scaffold_wave.py. Provides:
  - sys.path bridge so tests can ``import discover`` without packaging
  - ``mock_workspace`` fixture: a minimal pytest tmp_path workspace
  - ``frozen_now`` fixture: deterministic ISO 8601 timestamp for snapshot tests
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

# Sys path bridge — make the wave's sub-script directory importable
_SCRIPTS_DIR = Path(__file__).resolve().parent.parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))


@pytest.fixture
def mock_workspace(tmp_path: Path) -> Path:
    """Minimal workspace structure for forensic scans.

    Layout
    ------
        tmp_path/
            crates/demo/src/lib.rs   (empty Rust stub)
            crates/demo/Cargo.toml   (workspace member declaration)
            Cargo.toml               (workspace root with one member)
            scripts/touring-47-to-13-residual/data/ (empty data dir, ready for output)

    Tests can extend this fixture by writing additional files.
    """
    # Workspace skeleton
    crate_dir = tmp_path / "crates" / "demo"
    (crate_dir / "src").mkdir(parents=True)
    (crate_dir / "src" / "lib.rs").write_text(
        '//! demo crate\n\npub fn hello() -> &\'static str {\n    "world"\n}\n',
    )
    (crate_dir / "Cargo.toml").write_text(
        '[package]\nname = "demo"\nversion = "0.1.0"\nedition = "2021"\n',
    )
    (tmp_path / "Cargo.toml").write_text(
        '[workspace]\nmembers = ["crates/demo"]\n',
    )

    # Forensic data dir
    (tmp_path / "scripts" / "touring-47-to-13-residual" / "data").mkdir(parents=True)
    (tmp_path / "scripts" / "touring-47-to-13-residual" / "staging").mkdir(parents=True)

    return tmp_path


@pytest.fixture
def frozen_now(monkeypatch: pytest.MonkeyPatch) -> str:
    """Freeze ``datetime.now(UTC)`` for snapshot tests.

    Returns the frozen ISO 8601 string used in tests.
    """
    from datetime import datetime, timezone

    frozen = datetime(2026, 1, 1, 12, 0, 0, tzinfo=timezone.utc)
    iso = frozen.isoformat()

    class _FrozenDatetime(datetime):
        @classmethod
        def now(cls, tz=None):  # noqa: ARG003
            return frozen

    monkeypatch.setattr(
        "discover.datetime",
        _FrozenDatetime,
        raising=False,
    )
    return iso
