#!/usr/bin/env python3
"""
validate_phase04.py — Validation for AST Enhancements: FileHeat, Fused Search, EnrichedBlastRadius
Insights: AST-1, AST-2, AST-3
Generated by generate_plan.py — do not edit manually.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

WORKSPACE = Path("/home/gabrielgadea/.claude/rust")
PLAN_DIR = Path(__file__).parent


@dataclass
class Check:
    name: str
    passed: bool
    detail: str


def find_crate(path_fragment: str) -> str:
    """Infer crate name from a path fragment."""
    for crate in ["touring-learning", "touring-ast", "touring-cognitive"]:
        if crate in path_fragment:
            return crate
    # Guess from module path
    if "aco/" in path_fragment:
        return "touring-learning"
    if "semantic_search" in path_fragment or "file_heat" in path_fragment or "graph.rs" in path_fragment:
        return "touring-ast"
    if "cognitive" in path_fragment or "got.rs" in path_fragment or "refinement" in path_fragment:
        return "touring-cognitive"
    return ""


def run_cargo_check(name: str, cmd: str) -> Check:
    """Run a cargo command and return a Check."""
    try:
        result = subprocess.run(
            cmd.split(), capture_output=True, text=True,
            cwd=str(WORKSPACE), timeout=300,
        )
        return Check(name, result.returncode == 0, result.stderr[-300:] if result.returncode != 0 else "OK")
    except Exception as e:
        return Check(name, False, str(e))


def grep_check(name: str, symbol: str) -> Check:
    """Check if a symbol exists in any Rust file."""
    try:
        result = subprocess.run(
            ["grep", "-r", symbol, str(WORKSPACE / "crates")],
            capture_output=True, text=True, timeout=30,
        )
        found = result.returncode == 0
        detail = result.stdout.split("\n")[0] if found else f"{symbol} not found"
        return Check(name, found, detail)
    except Exception as e:
        return Check(name, False, str(e))


def run_checks(dry_run: bool = False) -> list[Check]:
    """Run all validation checks for this phase."""
    checks: list[Check] = []


    # Check 1: src/file_heat.rs exists with FileHeat and HeatMap structs
    path = WORKSPACE / "crates" / find_crate("src/file_heat.rs") / "src/file_heat.rs" if "src/" in "src/file_heat.rs" else PLAN_DIR / "src/file_heat.rs"
    checks.append(Check("src_file_heat.rs_exists_with_FileHeat_and_HeatMap_", path.exists(), f"{path} exists"))

    # Check 2: find_symbols_fused method exists in semantic_search.rs
    checks.append(grep_check("find_symbols_fused_method_exists_in_semantic_searc", "find_symbols_fused"))

    # Check 3: EnrichedBlastRadius struct exists in graph.rs
    checks.append(Check("EnrichedBlastRadius_struct_exists_in_graph.rs", True, "manual: EnrichedBlastRadius struct exists in graph.rs"))

    # Check 4: ImpactCategory enum exists in graph.rs
    checks.append(Check("ImpactCategory_enum_exists_in_graph.rs", True, "manual: ImpactCategory enum exists in graph.rs"))

    # Check 5: compute_enriched_blast_radius function exists in graph.rs
    checks.append(grep_check("compute_enriched_blast_radius_function_exists_in_g", "compute_enriched_blast_radius"))

    # Check 6: cargo clippy -p touring-ast -- -D warnings exits 0
    checks.append(run_cargo_check("cargo_clippy_-p_touring-ast_--_-D_warnings_exits_0", "cargo clippy -p touring-ast -- -D warnings"))

    # Check 7: cargo test -p touring-ast exits 0
    checks.append(run_cargo_check("cargo_test_-p_touring-ast_exits_0", "cargo test -p touring-ast"))

    # Check 8: All 15+ new tests pass
    checks.append(Check("All_15+_new_tests_pass", True, "manual: All 15+ new tests pass"))

    if dry_run:
        print(f"[DRY RUN] Phase 04: {len(checks)} checks defined")
    return checks


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate phase 04")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args()

    checks = run_checks(dry_run=args.dry_run)
    if args.dry_run:
        return

    passed = sum(1 for c in checks if c.passed)
    total = len(checks)

    print(f"\n=== Phase 04: {phase.title} ===")
    for c in checks:
        status = "PASS" if c.passed else "FAIL"
        print(f"  [{status}] {c.name}")
        if args.verbose or not c.passed:
            print(f"         {c.detail}")

    print(f"\n  Score: {passed}/{total}")
    sys.exit(0 if passed == total else 1)


if __name__ == "__main__":
    main()
