#!/usr/bin/env python3
"""
validate_phase05.py — Validation for Cognitive Advanced: CognitiveMCTS, RefinementCycle, GoT Multi-dim
Insights: COG-1, COG-2, COG-4
Generated by generate_plan.py — do not edit manually.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

WORKSPACE = Path("/home/gabrielgadea/.claude/rust")
PLAN_DIR = Path(__file__).parent


@dataclass
class Check:
    name: str
    passed: bool
    detail: str


def find_crate(path_fragment: str) -> str:
    """Infer crate name from a path fragment."""
    for crate in ["touring-learning", "touring-ast", "touring-cognitive"]:
        if crate in path_fragment:
            return crate
    # Guess from module path
    if "aco/" in path_fragment:
        return "touring-learning"
    if "semantic_search" in path_fragment or "file_heat" in path_fragment or "graph.rs" in path_fragment:
        return "touring-ast"
    if "cognitive" in path_fragment or "got.rs" in path_fragment or "refinement" in path_fragment:
        return "touring-cognitive"
    return ""


def run_cargo_check(name: str, cmd: str) -> Check:
    """Run a cargo command and return a Check."""
    try:
        result = subprocess.run(
            cmd.split(), capture_output=True, text=True,
            cwd=str(WORKSPACE), timeout=300,
        )
        return Check(name, result.returncode == 0, result.stderr[-300:] if result.returncode != 0 else "OK")
    except Exception as e:
        return Check(name, False, str(e))


def grep_check(name: str, symbol: str) -> Check:
    """Check if a symbol exists in any Rust file."""
    try:
        result = subprocess.run(
            ["grep", "-r", symbol, str(WORKSPACE / "crates")],
            capture_output=True, text=True, timeout=30,
        )
        found = result.returncode == 0
        detail = result.stdout.split("\n")[0] if found else f"{symbol} not found"
        return Check(name, found, detail)
    except Exception as e:
        return Check(name, False, str(e))


def run_checks(dry_run: bool = False) -> list[Check]:
    """Run all validation checks for this phase."""
    checks: list[Check] = []


    # Check 1: src/cognitive_mcts.rs exists with CognitiveMCTS struct
    path = WORKSPACE / "crates" / find_crate("src/cognitive_mcts.rs") / "src/cognitive_mcts.rs" if "src/" in "src/cognitive_mcts.rs" else PLAN_DIR / "src/cognitive_mcts.rs"
    checks.append(Check("src_cognitive_mcts.rs_exists_with_CognitiveMCTS_st", path.exists(), f"{path} exists"))

    # Check 2: cognitive_search method exists
    checks.append(grep_check("cognitive_search_method_exists", "cognitive_search"))

    # Check 3: src/refinement.rs exists with RefinementCycle struct
    path = WORKSPACE / "crates" / find_crate("src/refinement.rs") / "src/refinement.rs" if "src/" in "src/refinement.rs" else PLAN_DIR / "src/refinement.rs"
    checks.append(Check("src_refinement.rs_exists_with_RefinementCycle_stru", path.exists(), f"{path} exists"))

    # Check 4: run_refinement method exists
    checks.append(grep_check("run_refinement_method_exists", "run_refinement"))

    # Check 5: evaluate_multidimensional method exists in got.rs
    checks.append(grep_check("evaluate_multidimensional_method_exists_in_got.rs", "evaluate_multidimensional"))

    # Check 6: ThoughtResult has relevance, confidence, novelty fields
    checks.append(Check("ThoughtResult_has_relevance,_confidence,_novelty_f", True, "manual: ThoughtResult has relevance, confidence, novelty fields"))

    # Check 7: cargo clippy -p touring-cognitive -- -D warnings exits 0
    checks.append(run_cargo_check("cargo_clippy_-p_touring-cognitive_--_-D_warnings_e", "cargo clippy -p touring-cognitive -- -D warnings"))

    # Check 8: cargo test -p touring-cognitive exits 0
    checks.append(run_cargo_check("cargo_test_-p_touring-cognitive_exits_0", "cargo test -p touring-cognitive"))

    # Check 9: All 17+ new tests pass
    checks.append(Check("All_17+_new_tests_pass", True, "manual: All 17+ new tests pass"))

    if dry_run:
        print(f"[DRY RUN] Phase 05: {len(checks)} checks defined")
    return checks


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate phase 05")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args()

    checks = run_checks(dry_run=args.dry_run)
    if args.dry_run:
        return

    passed = sum(1 for c in checks if c.passed)
    total = len(checks)

    print(f"\n=== Phase 05: {phase.title} ===")
    for c in checks:
        status = "PASS" if c.passed else "FAIL"
        print(f"  [{status}] {c.name}")
        if args.verbose or not c.passed:
            print(f"         {c.detail}")

    print(f"\n  Score: {passed}/{total}")
    sys.exit(0 if passed == total else 1)


if __name__ == "__main__":
    main()
