#!/usr/bin/env python3
"""
validate_phase03.py — Validation for ACO Evolution: EvolutionPackage Population Logic
Insights: ACO-2
Generated by generate_plan.py — do not edit manually.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

WORKSPACE = Path("/home/gabrielgadea/.claude/rust")
PLAN_DIR = Path(__file__).parent


@dataclass
class Check:
    name: str
    passed: bool
    detail: str


def find_crate(path_fragment: str) -> str:
    """Infer crate name from a path fragment."""
    for crate in ["touring-learning", "touring-ast", "touring-cognitive"]:
        if crate in path_fragment:
            return crate
    # Guess from module path
    if "aco/" in path_fragment:
        return "touring-learning"
    if "semantic_search" in path_fragment or "file_heat" in path_fragment or "graph.rs" in path_fragment:
        return "touring-ast"
    if "cognitive" in path_fragment or "got.rs" in path_fragment or "refinement" in path_fragment:
        return "touring-cognitive"
    return ""


def run_cargo_check(name: str, cmd: str) -> Check:
    """Run a cargo command and return a Check."""
    try:
        result = subprocess.run(
            cmd.split(), capture_output=True, text=True,
            cwd=str(WORKSPACE), timeout=300,
        )
        return Check(name, result.returncode == 0, result.stderr[-300:] if result.returncode != 0 else "OK")
    except Exception as e:
        return Check(name, False, str(e))


def grep_check(name: str, symbol: str) -> Check:
    """Check if a symbol exists in any Rust file."""
    try:
        result = subprocess.run(
            ["grep", "-r", symbol, str(WORKSPACE / "crates")],
            capture_output=True, text=True, timeout=30,
        )
        found = result.returncode == 0
        detail = result.stdout.split("\n")[0] if found else f"{symbol} not found"
        return Check(name, found, detail)
    except Exception as e:
        return Check(name, False, str(e))


def run_checks(dry_run: bool = False) -> list[Check]:
    """Run all validation checks for this phase."""
    checks: list[Check] = []


    # Check 1: src/aco/evolution.rs exists
    path = WORKSPACE / "crates" / find_crate("src/aco/evolution.rs") / "src/aco/evolution.rs" if "src/" in "src/aco/evolution.rs" else PLAN_DIR / "src/aco/evolution.rs"
    checks.append(Check("src_aco_evolution.rs_exists", path.exists(), f"{path} exists"))

    # Check 2: populate_evolution_package function exists
    checks.append(grep_check("populate_evolution_package_function_exists", "populate_evolution_package"))

    # Check 3: extract_learned_patterns function exists
    checks.append(grep_check("extract_learned_patterns_function_exists", "extract_learned_patterns"))

    # Check 4: discover_anti_patterns function exists
    checks.append(grep_check("discover_anti_patterns_function_exists", "discover_anti_patterns"))

    # Check 5: propose_system_upgrades function exists
    checks.append(grep_check("propose_system_upgrades_function_exists", "propose_system_upgrades"))

    # Check 6: cargo clippy -p touring-learning -- -D warnings exits 0
    checks.append(run_cargo_check("cargo_clippy_-p_touring-learning_--_-D_warnings_ex", "cargo clippy -p touring-learning -- -D warnings"))

    # Check 7: cargo test -p touring-learning exits 0
    checks.append(run_cargo_check("cargo_test_-p_touring-learning_exits_0", "cargo test -p touring-learning"))

    if dry_run:
        print(f"[DRY RUN] Phase 03: {len(checks)} checks defined")
    return checks


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate phase 03")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args()

    checks = run_checks(dry_run=args.dry_run)
    if args.dry_run:
        return

    passed = sum(1 for c in checks if c.passed)
    total = len(checks)

    print(f"\n=== Phase 03: {phase.title} ===")
    for c in checks:
        status = "PASS" if c.passed else "FAIL"
        print(f"  [{status}] {c.name}")
        if args.verbose or not c.passed:
            print(f"         {c.detail}")

    print(f"\n  Score: {passed}/{total}")
    sys.exit(0 if passed == total else 1)


if __name__ == "__main__":
    main()
