#!/usr/bin/env python3
"""
validate_phase07.py — Validation for Final Audit and Consolidation
Insights: N/A (infrastructure)
Generated by generate_plan.py — do not edit manually.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

WORKSPACE = Path("/home/gabrielgadea/.claude/rust")
PLAN_DIR = Path(__file__).parent


@dataclass
class Check:
    name: str
    passed: bool
    detail: str


def find_crate(path_fragment: str) -> str:
    """Infer crate name from a path fragment."""
    for crate in ["touring-learning", "touring-ast", "touring-cognitive"]:
        if crate in path_fragment:
            return crate
    # Guess from module path
    if "aco/" in path_fragment:
        return "touring-learning"
    if "semantic_search" in path_fragment or "file_heat" in path_fragment or "graph.rs" in path_fragment:
        return "touring-ast"
    if "cognitive" in path_fragment or "got.rs" in path_fragment or "refinement" in path_fragment:
        return "touring-cognitive"
    return ""


def run_cargo_check(name: str, cmd: str) -> Check:
    """Run a cargo command and return a Check."""
    try:
        result = subprocess.run(
            cmd.split(), capture_output=True, text=True,
            cwd=str(WORKSPACE), timeout=300,
        )
        return Check(name, result.returncode == 0, result.stderr[-300:] if result.returncode != 0 else "OK")
    except Exception as e:
        return Check(name, False, str(e))


def grep_check(name: str, symbol: str) -> Check:
    """Check if a symbol exists in any Rust file."""
    try:
        result = subprocess.run(
            ["grep", "-r", symbol, str(WORKSPACE / "crates")],
            capture_output=True, text=True, timeout=30,
        )
        found = result.returncode == 0
        detail = result.stdout.split("\n")[0] if found else f"{symbol} not found"
        return Check(name, found, detail)
    except Exception as e:
        return Check(name, False, str(e))


def run_checks(dry_run: bool = False) -> list[Check]:
    """Run all validation checks for this phase."""
    checks: list[Check] = []


    # Check 1: audit_implementation.py reports 13/13 PASS
    checks.append(Check("audit_implementation.py_reports_13_13_PASS", True, "manual: audit_implementation.py reports 13/13 PASS"))

    # Check 2: cargo clippy --workspace -- -D warnings exits 0
    checks.append(run_cargo_check("cargo_clippy_--workspace_--_-D_warnings_exits_0", "cargo clippy --workspace -- -D warnings"))

    # Check 3: cargo test --workspace --exclude touring-python exits 0
    checks.append(run_cargo_check("cargo_test_--workspace_--exclude_touring-python_ex", "cargo test --workspace --exclude touring-python"))

    # Check 4: Test count >= baseline + 80
    checks.append(Check("Test_count_>=_baseline_+_80", True, "manual: Test count >= baseline + 80"))

    # Check 5: No stale TODO comments in modified files
    checks.append(Check("No_stale_TODO_comments_in_modified_files", True, "manual: No stale TODO comments in modified files"))

    # Check 6: Final checkpoint file exists
    checks.append(Check("Final_checkpoint_file_exists", True, "manual check: Final checkpoint file exists"))

    if dry_run:
        print(f"[DRY RUN] Phase 07: {len(checks)} checks defined")
    return checks


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate phase 07")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args()

    checks = run_checks(dry_run=args.dry_run)
    if args.dry_run:
        return

    passed = sum(1 for c in checks if c.passed)
    total = len(checks)

    print(f"\n=== Phase 07: {phase.title} ===")
    for c in checks:
        status = "PASS" if c.passed else "FAIL"
        print(f"  [{status}] {c.name}")
        if args.verbose or not c.passed:
            print(f"         {c.detail}")

    print(f"\n  Score: {passed}/{total}")
    sys.exit(0 if passed == total else 1)


if __name__ == "__main__":
    main()
