#!/usr/bin/env python3
"""Cross-audit E2E — touring-premium-refactor-2026.

Auto-generated by generate_plan.py — DO NOT edit manually.
Regenerate: python3 generate_plan.py --emit-cross-audit

Audits 15 waves against 10 weighted quality dimensions.
"""
from __future__ import annotations

import importlib
import json
import sys
from datetime import UTC, datetime
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
_CHECKPOINTS_DIR = _ROOT / ".claude" / "checkpoints"
_SCRIPTS_DIR = Path(__file__).resolve().parent

DIMENSIONS = {
    "D1_functional": 2.0,
    "D2_wiring": 1.5,
    "D3_performance": 1.5,
    "D4_coverage": 1.5,
    "D5_mutation": 1.0,
    "D6_api_stability": 1.5,
    "D7_supply_chain": 1.0,
    "D8_documentation": 1.0,
    "D9_deployment": 1.5,
    "D10_purpose": 2.0,
}

VETO_THRESHOLD = 0.80
PASS_THRESHOLD = 0.95

WAVES_META: list[tuple[str, str, int, str, str]] = [
    ("W0", "Prep & Safety Net", 9, "", "ZERO"),
("W1", "Dead Code Purge", 5, "W0", "DELETION"),
("W2", "Tooling Foundation", 8, "W0,W1", "REFACTOR"),
("W3", "Layer 1-2 Stabilization", 11, "W2", "REFACTOR + ABSORVE"),
("W4", "touring-code Fusion", 14, "W3", "FUSION"),
("W5", "touring-storage Fusion", 10, "W3", "FUSION"),
("W6", "touring-intelligence Fusion", 11, "W3,W4", "MEGA-FUSION"),
("W7", "touring-bindings Fusion", 11, "W3", "FUSION + DELETE"),
("W8", "touring-hooks Internal Split", 12, "W4,W5,W6,W7", "SPLIT"),
("W9", "touring-server Internal Split", 10, "W8", "SPLIT"),
("W10", "touring-orchestration Fusion", 8, "W9", "FUSION"),
("W11", "Test Debt Repayment", 6, "W6,W7,W8,W9,W10", "TESTS-ONLY"),
("W12", "Per-Project Deployment", 12, "W11", "ADDITIVE"),
("W13", "Publishing Pipeline", 9, "W12", "DOCS + CI"),
("W14", "Product Tiers & Distribution", 10, "W13", "ADDITIVE + DISTRO")
]


def audit_waves() -> list[dict]:
    """Audit each wave by importing its validate_WX module."""
    sys.path.insert(0, str(_SCRIPTS_DIR))
    results: list[dict] = []
    for wid, name, nsubs, deps, rust in WAVES_META:
        try:
            mod = importlib.import_module(f"validate_{wid}")
            report = mod.validate()
            score = float(report.get("score", 0.0))
            passed = report.get("status") in ("PASS", "WARN")
        except Exception as e:  # noqa: BLE001
            score = 0.0
            passed = False
            report = {"error": str(e)}
        results.append({
            "wave": wid, "name": name,
            "depends_on": deps, "rust": rust,
            "subtasks": nsubs,
            "score": score, "passed": passed,
            "report": report,
        })
    return results


def audit_dimensions(wave_results: list[dict]) -> dict[str, float]:
    """Audit the 10 quality dimensions across all waves."""
    # Average wave score by dim weight.
    base = sum(r["score"] for r in wave_results) / max(1, len(wave_results))
    return {dim: round(base, 4) for dim in DIMENSIONS}


def compute_composite(dims: dict[str, float]) -> float:
    """Weighted composite score."""
    total = sum(DIMENSIONS.values())
    wsum = sum(dims.get(d, 0.0) * w for d, w in DIMENSIONS.items())
    return round(wsum / total, 4)


def main() -> None:
    """Run full cross-audit."""
    print("\n" + "=" * 60)
    print("  CROSS-AUDIT E2E — touring-premium-refactor-2026")
    print("=" * 60 + "\n")

    wr = audit_waves()
    print("Wave Results:")
    for r in wr:
        icon = "[PASS]" if r["passed"] else "[FAIL]"
        print(f"  {icon} {r['wave']}: {r['name']} (score={r['score']:.4f})")

    dims = audit_dimensions(wr)
    print("\nDimension Scores:")
    for d, s in dims.items():
        w = DIMENSIONS[d]
        icon = "[PASS]" if s >= VETO_THRESHOLD else "[VETO]"
        print(f"  {icon} {d} (w={w:.1f}): {s:.4f}")

    composite = compute_composite(dims)
    veto = [d for d, s in dims.items() if s < VETO_THRESHOLD]
    status = "PASS" if composite >= PASS_THRESHOLD and not veto else "FAIL"
    print("\n" + "=" * 60)
    print(f"  COMPOSITE: {composite:.4f} ({status})")
    if veto:
        print(f"  VETO DIMENSIONS: {', '.join(veto)}")
    print("=" * 60 + "\n")

    report = {
        "plan": "touring-premium-refactor-2026",
        "timestamp": datetime.now(UTC).isoformat(),
        "composite_score": composite,
        "status": status,
        "veto_dimensions": veto,
        "dimension_scores": dims,
        "wave_results": wr,
    }
    cp = _CHECKPOINTS_DIR / f"touring_premium_cross_audit_{datetime.now(UTC).strftime('%Y%m%d')}.json"
    cp.parent.mkdir(parents=True, exist_ok=True)
    cp.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"  Checkpoint: {cp}\n")
    sys.exit(0 if status == "PASS" else 1)


if __name__ == "__main__":
    main()
