#!/usr/bin/env python3
"""Validator for W9: touring-server Internal Split.

Auto-generated by generate_plan.py — DO NOT edit manually.
Regenerate: python3 scripts/touring_premium_refactor_2026/generate_plan.py --emit-validators

Validates:
          - W9.1: 6 crates cargo check exit 0.
  - W9.2: cargo check -p touring-server-cli exit 0.
  - W9.3: cargo check -p touring-server-tools exit 0.
  - W9.4: cargo check -p touring-server-reasoning exit 0.
  - W9.5: cargo check -p touring-server-session exit 0.
  - W9.6: cargo check -p touring-server-telemetry exit 0.
  - W9.7: cargo build --bin touring exit 0.
  - W9.8: cargo test --workspace exit 0.
  - W9.9: P99 < 10ms para 3 commands hot-path.
  - W9.10: 82/82 smoke tests exit 0.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
_CHECKPOINTS_DIR = _ROOT / ".claude" / "checkpoints"
_WAVE_ID = 'W9'
_WAVE_NAME = 'touring-server Internal Split'
_GATE = 'touring-server façade 25k LOC, 6 internal sub-crates, CLI dispatch P99 < 10ms, 82 commands smoke pass.'


def check_subtask(check_id: str, name: str, validation: str, tdd_test: str) -> dict:
    """Run a single subtask check. Returns a result dict."""
    # TODO: implement real checks. Stub returns False with a clear "not implemented" note.
    return {
        "check": check_id,
        "name": name,
        "validation": validation,
        "tdd_test": tdd_test,
        "passed": False,
        "details": "Not yet implemented — replace stub with real check during W9 execution.",
    }


def run_cargo_check_workspace() -> bool:
    """Return True if `cargo check --workspace` exits 0."""
    try:
        r = subprocess.run(
            ["cargo", "check", "--workspace"],
            cwd=_ROOT, capture_output=True, timeout=600,
        )
        return r.returncode == 0
    except Exception:  # noqa: BLE001
        return False


def run_wiring_cycles_zero() -> bool:
    """Return True if no cycles of depth >= 2 detected."""
    try:
        r = subprocess.run(
            ["touring", "wiring", "cycles", "--min-depth", "2", "--format", "json"],
            capture_output=True, timeout=60,
        )
        if r.returncode != 0:
            return False
        data = json.loads(r.stdout.decode("utf-8") or "{}")
        return int(data.get("cycle_count", 0)) == 0
    except Exception:  # noqa: BLE001
        return False


def validate() -> dict:
    """Run all validation checks. Returns report dict."""
    results: list[dict] = []
    results.append(check_subtask(
        check_id='W9.1',
        name='Create 6 internal sub-crates',
        validation='6 crates cargo check exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W9.2',
        name='Move cli/* → server-cli',
        validation='cargo check -p touring-server-cli exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W9.3',
        name='Move tools/* → server-tools',
        validation='cargo check -p touring-server-tools exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W9.4',
        name='Move reasoning/* → server-reasoning',
        validation='cargo check -p touring-server-reasoning exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W9.5',
        name='Move session/* + snapshot/* → server-session',
        validation='cargo check -p touring-server-session exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W9.6',
        name='Move telemetry/* + telemetry_init.rs → server-telemetry',
        validation='cargo check -p touring-server-telemetry exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W9.7',
        name='Move visual/* → server-visual + façade',
        validation='cargo build --bin touring exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W9.8',
        name='Tests reorganize',
        validation='cargo test --workspace exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W9.9',
        name='Bench CLI dispatch < 10ms P99',
        validation='P99 < 10ms para 3 commands hot-path.',
        tdd_test='test_cli_dispatch_p99_under_10ms'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W9.10',
        name='Validation: 82 CLI commands smoke test',
        validation='82/82 smoke tests exit 0.',
        tdd_test=''
                  if False else '',
    ))

    # Wave-level invariants
    cargo_ok = run_cargo_check_workspace()
    cycles_ok = run_wiring_cycles_zero()

    results.append({
        "check": "wave-invariant",
        "name": "cargo check + wiring cycles zero",
        "validation": "cargo check exit 0 + 0 new cycles",
        "tdd_test": "",
        "passed": cargo_ok and cycles_ok,
        "details": f"cargo_check_ok={cargo_ok}, cycles_zero={cycles_ok}",
    })

    passed = sum(1 for r in results if r["passed"])
    total = len(results)
    score = passed / total if total > 0 else 0.0
    status = "PASS" if score >= 0.95 else "WARN" if score >= 0.70 else "FAIL"

    return {
        "wave": _WAVE_ID,
        "name": _WAVE_NAME,
        "timestamp": datetime.now(UTC).isoformat(),
        "checks_passed": passed,
        "checks_total": total,
        "score": round(score, 4),
        "status": status,
        "gate": _GATE,
        "results": results,
    }


def main() -> None:
    """Entry point. Prints report and saves checkpoint."""
    report = validate()
    print(f"\n{'='*60}")
    print(f"  {_WAVE_ID}: {_WAVE_NAME}")
    print(f"  Score: {report['score']:.4f} ({report['status']})")
    print(f"  Checks: {report['checks_passed']}/{report['checks_total']}")
    print(f"{'='*60}\n")
    for r in report["results"]:
        icon = "[PASS]" if r["passed"] else "[FAIL]"
        print(f"  {icon} {r['check']}: {r['name']}")
        if r["details"]:
            print(f"          {r['details']}")
    cp = _CHECKPOINTS_DIR / f"touring_premium_{_WAVE_ID}_{datetime.now(UTC).strftime('%Y%m%d')}.json"
    cp.parent.mkdir(parents=True, exist_ok=True)
    cp.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n  Checkpoint: {cp}")
    sys.exit(0 if report["status"] in ("PASS", "WARN") else 1)


if __name__ == "__main__":
    main()
