#!/usr/bin/env python3
"""Validator for W2: Tooling Foundation.

Auto-generated by generate_plan.py — DO NOT edit manually.
Regenerate: python3 scripts/touring_premium_refactor_2026/generate_plan.py --emit-validators

Validates:
          - W2.1: [workspace.dependencies] tem ≥ 60 entradas; nenhuma versão duplicada.
  - W2.2: [workspace.package] presente com 5+ campos.
  - W2.3: grep -rn 'serde = "' crates/*/Cargo.toml retorna 0 hits para deps já em workspace.dependencies.
  - W2.4: cargo clippy --workspace -- -D warnings exit 0.
  - W2.5: cargo deny check exit 0.
  - W2.6: cargo machete exit 0 OR justified ignore-list.
  - W2.7: cargo mutants --baseline workspace exit 0 (não enforça threshold).
  - W2.8: Push para branch + observe workflow green.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
_CHECKPOINTS_DIR = _ROOT / ".claude" / "checkpoints"
_WAVE_ID = 'W2'
_WAVE_NAME = 'Tooling Foundation'
_GATE = '[workspace.dependencies] populated; 42 Cargo.toml usam .workspace=true; cargo-deny + machete clean; CI workflow ativo.'


def check_subtask(check_id: str, name: str, validation: str, tdd_test: str) -> dict:
    """Run a single subtask check. Returns a result dict."""
    # TODO: implement real checks. Stub returns False with a clear "not implemented" note.
    return {
        "check": check_id,
        "name": name,
        "validation": validation,
        "tdd_test": tdd_test,
        "passed": False,
        "details": "Not yet implemented — replace stub with real check during W2 execution.",
    }


def run_cargo_check_workspace() -> bool:
    """Return True if `cargo check --workspace` exits 0."""
    try:
        r = subprocess.run(
            ["cargo", "check", "--workspace"],
            cwd=_ROOT, capture_output=True, timeout=600,
        )
        return r.returncode == 0
    except Exception:  # noqa: BLE001
        return False


def run_wiring_cycles_zero() -> bool:
    """Return True if no cycles of depth >= 2 detected."""
    try:
        r = subprocess.run(
            ["touring", "wiring", "cycles", "--min-depth", "2", "--format", "json"],
            capture_output=True, timeout=60,
        )
        if r.returncode != 0:
            return False
        data = json.loads(r.stdout.decode("utf-8") or "{}")
        return int(data.get("cycle_count", 0)) == 0
    except Exception:  # noqa: BLE001
        return False


def validate() -> dict:
    """Run all validation checks. Returns report dict."""
    results: list[dict] = []
    results.append(check_subtask(
        check_id='W2.1',
        name='Centralize external deps in [workspace.dependencies]',
        validation='[workspace.dependencies] tem ≥ 60 entradas; nenhuma versão duplicada.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W2.2',
        name='Centralize [workspace.package] metadata',
        validation='[workspace.package] presente com 5+ campos.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W2.3',
        name='Update 42 Cargo.toml: <dep>.workspace = true',
        validation='grep -rn \'serde = "\' crates/*/Cargo.toml retorna 0 hits para deps já em workspace.dependencies.',
        tdd_test='test_no_inline_dep_versions'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W2.4',
        name='[workspace.lints] strict',
        validation='cargo clippy --workspace -- -D warnings exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W2.5',
        name='cargo-deny config',
        validation='cargo deny check exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W2.6',
        name='cargo-machete (0 unused deps)',
        validation='cargo machete exit 0 OR justified ignore-list.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W2.7',
        name='cargo-mutants per-crate config',
        validation='cargo mutants --baseline workspace exit 0 (não enforça threshold).',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W2.8',
        name='CI workflow: deny + machete + mutants + msrv',
        validation='Push para branch + observe workflow green.',
        tdd_test=''
                  if False else '',
    ))

    # Wave-level invariants
    cargo_ok = run_cargo_check_workspace()
    cycles_ok = run_wiring_cycles_zero()

    results.append({
        "check": "wave-invariant",
        "name": "cargo check + wiring cycles zero",
        "validation": "cargo check exit 0 + 0 new cycles",
        "tdd_test": "",
        "passed": cargo_ok and cycles_ok,
        "details": f"cargo_check_ok={cargo_ok}, cycles_zero={cycles_ok}",
    })

    passed = sum(1 for r in results if r["passed"])
    total = len(results)
    score = passed / total if total > 0 else 0.0
    status = "PASS" if score >= 0.95 else "WARN" if score >= 0.70 else "FAIL"

    return {
        "wave": _WAVE_ID,
        "name": _WAVE_NAME,
        "timestamp": datetime.now(UTC).isoformat(),
        "checks_passed": passed,
        "checks_total": total,
        "score": round(score, 4),
        "status": status,
        "gate": _GATE,
        "results": results,
    }


def main() -> None:
    """Entry point. Prints report and saves checkpoint."""
    report = validate()
    print(f"\n{'='*60}")
    print(f"  {_WAVE_ID}: {_WAVE_NAME}")
    print(f"  Score: {report['score']:.4f} ({report['status']})")
    print(f"  Checks: {report['checks_passed']}/{report['checks_total']}")
    print(f"{'='*60}\n")
    for r in report["results"]:
        icon = "[PASS]" if r["passed"] else "[FAIL]"
        print(f"  {icon} {r['check']}: {r['name']}")
        if r["details"]:
            print(f"          {r['details']}")
    cp = _CHECKPOINTS_DIR / f"touring_premium_{_WAVE_ID}_{datetime.now(UTC).strftime('%Y%m%d')}.json"
    cp.parent.mkdir(parents=True, exist_ok=True)
    cp.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n  Checkpoint: {cp}")
    sys.exit(0 if report["status"] in ("PASS", "WARN") else 1)


if __name__ == "__main__":
    main()
