#!/usr/bin/env python3
"""Validator for W13: Publishing Pipeline.

Auto-generated by generate_plan.py — DO NOT edit manually.
Regenerate: python3 scripts/touring_premium_refactor_2026/generate_plan.py --emit-validators

Validates:
          - W13.1: cargo doc --workspace --no-deps --warnings-as-errors exit 0.
  - W13.2: cargo +nightly doc --no-deps --all-features exit 0.
  - W13.3: CI workflow runs cargo semver-checks check-release.
  - W13.4: cargo msrv verify per crate exit 0.
  - W13.5: cosign verify-blob --certificate-identity exit 0.
  - W13.6: sbom.json válido CycloneDX 1.5 schema.
  - W13.7: docs/privacy.md ≥ 200 LOC; opt-out testado.
  - W13.8: release-plz update --dry-run gera CHANGELOG diffs.
  - W13.9: install.touring.dev installa 1.0.0-rc.1; touring --version mostra rc.1.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
_CHECKPOINTS_DIR = _ROOT / ".claude" / "checkpoints"
_WAVE_ID = 'W13'
_WAVE_NAME = 'Publishing Pipeline'
_GATE = 'Release tooling funcional; RC1 published; docs.rs green; semver-check + msrv + sigstore + SBOM operacionais.'


def check_subtask(check_id: str, name: str, validation: str, tdd_test: str) -> dict:
    """Run a single subtask check. Returns a result dict."""
    # TODO: implement real checks. Stub returns False with a clear "not implemented" note.
    return {
        "check": check_id,
        "name": name,
        "validation": validation,
        "tdd_test": tdd_test,
        "passed": False,
        "details": "Not yet implemented — replace stub with real check during W13 execution.",
    }


def run_cargo_check_workspace() -> bool:
    """Return True if `cargo check --workspace` exits 0."""
    try:
        r = subprocess.run(
            ["cargo", "check", "--workspace"],
            cwd=_ROOT, capture_output=True, timeout=600,
        )
        return r.returncode == 0
    except Exception:  # noqa: BLE001
        return False


def run_wiring_cycles_zero() -> bool:
    """Return True if no cycles of depth >= 2 detected."""
    try:
        r = subprocess.run(
            ["touring", "wiring", "cycles", "--min-depth", "2", "--format", "json"],
            capture_output=True, timeout=60,
        )
        if r.returncode != 0:
            return False
        data = json.loads(r.stdout.decode("utf-8") or "{}")
        return int(data.get("cycle_count", 0)) == 0
    except Exception:  # noqa: BLE001
        return False


def validate() -> dict:
    """Run all validation checks. Returns report dict."""
    results: list[dict] = []
    results.append(check_subtask(
        check_id='W13.1',
        name='README per crate + #![warn(missing_docs)]',
        validation='cargo doc --workspace --no-deps --warnings-as-errors exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W13.2',
        name='docs.rs build all features combinatorially',
        validation='cargo +nightly doc --no-deps --all-features exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W13.3',
        name='semver-check CI gate',
        validation='CI workflow runs cargo semver-checks check-release.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W13.4',
        name='cargo-msrv verify per crate',
        validation='cargo msrv verify per crate exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W13.5',
        name='Sigstore signing pipeline',
        validation='cosign verify-blob --certificate-identity exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W13.6',
        name='SBOM (CycloneDX) per release',
        validation='sbom.json válido CycloneDX 1.5 schema.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W13.7',
        name='Telemetry privacy doc + opt-out UX',
        validation='docs/privacy.md ≥ 200 LOC; opt-out testado.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W13.8',
        name='CHANGELOG.md per crate (release-plz config)',
        validation='release-plz update --dry-run gera CHANGELOG diffs.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W13.9',
        name='Release candidate 1.0.0-rc.1',
        validation='install.touring.dev installa 1.0.0-rc.1; touring --version mostra rc.1.',
        tdd_test=''
                  if False else '',
    ))

    # Wave-level invariants
    cargo_ok = run_cargo_check_workspace()
    cycles_ok = run_wiring_cycles_zero()

    results.append({
        "check": "wave-invariant",
        "name": "cargo check + wiring cycles zero",
        "validation": "cargo check exit 0 + 0 new cycles",
        "tdd_test": "",
        "passed": cargo_ok and cycles_ok,
        "details": f"cargo_check_ok={cargo_ok}, cycles_zero={cycles_ok}",
    })

    passed = sum(1 for r in results if r["passed"])
    total = len(results)
    score = passed / total if total > 0 else 0.0
    status = "PASS" if score >= 0.95 else "WARN" if score >= 0.70 else "FAIL"

    return {
        "wave": _WAVE_ID,
        "name": _WAVE_NAME,
        "timestamp": datetime.now(UTC).isoformat(),
        "checks_passed": passed,
        "checks_total": total,
        "score": round(score, 4),
        "status": status,
        "gate": _GATE,
        "results": results,
    }


def main() -> None:
    """Entry point. Prints report and saves checkpoint."""
    report = validate()
    print(f"\n{'='*60}")
    print(f"  {_WAVE_ID}: {_WAVE_NAME}")
    print(f"  Score: {report['score']:.4f} ({report['status']})")
    print(f"  Checks: {report['checks_passed']}/{report['checks_total']}")
    print(f"{'='*60}\n")
    for r in report["results"]:
        icon = "[PASS]" if r["passed"] else "[FAIL]"
        print(f"  {icon} {r['check']}: {r['name']}")
        if r["details"]:
            print(f"          {r['details']}")
    cp = _CHECKPOINTS_DIR / f"touring_premium_{_WAVE_ID}_{datetime.now(UTC).strftime('%Y%m%d')}.json"
    cp.parent.mkdir(parents=True, exist_ok=True)
    cp.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n  Checkpoint: {cp}")
    sys.exit(0 if report["status"] in ("PASS", "WARN") else 1)


if __name__ == "__main__":
    main()
