#!/usr/bin/env python3
"""Validator for W4: touring-code Fusion.

Auto-generated by generate_plan.py — DO NOT edit manually.
Regenerate: python3 scripts/touring_premium_refactor_2026/generate_plan.py --emit-validators

Validates:
          - W4.1: cargo check -p touring-code exit 0; crate registrado em workspace.
  - W4.2: cargo check -p touring-code exit 0; pub mod ast exposto.
  - W4.3: cargo check -p touring-code --features parser-ast-grep exit 0.
  - W4.4: touring_code::languages::Lang exposto.
  - W4.5: touring_code::semantics::Definition exposto.
  - W4.6: cargo check --no-default-features -p touring-code exit 0; cargo check --all-features -p touring-code exit 0.
  - W4.7: grep 'use touring_ast::' crates/ → apenas em touring-ast shim crate.
  - W4.8: grep 'touring_ast_polyglot' crates/ → apenas em shim.
  - W4.9: grep 'touring_language' crates/ → apenas em shim.
  - W4.10: grep 'touring_semantics' crates/ → apenas em shim.
  - W4.11: Nenhum bench mais lento que -5%. Idealmente alguns ficam mais rápidos (cache compartilhado dentro do crate).
  - W4.12: cargo test workspace exit 0; cycle count ≤ baseline W3.
  - W4.13: ls crates/touring-{ast,ast-polyglot,language,semantics}/src/ → apenas lib.rs com pub use re-exports.
  - W4.14: grep '"crates/touring-code"' Cargo.toml; cargo check exit 0.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
_CHECKPOINTS_DIR = _ROOT / ".claude" / "checkpoints"
_WAVE_ID = 'W4'
_WAVE_NAME = 'touring-code Fusion'
_GATE = 'touring-code 26k LOC, 6+3 features funcionais, ≥ 23% test ratio, 0 cycle regression, < 5% perf regression, 38 consumers atualizados, shim crates por 2 versões.'


def check_subtask(check_id: str, name: str, validation: str, tdd_test: str) -> dict:
    """Run a single subtask check. Returns a result dict."""
    # TODO: implement real checks. Stub returns False with a clear "not implemented" note.
    return {
        "check": check_id,
        "name": name,
        "validation": validation,
        "tdd_test": tdd_test,
        "passed": False,
        "details": "Not yet implemented — replace stub with real check during W4 execution.",
    }


def run_cargo_check_workspace() -> bool:
    """Return True if `cargo check --workspace` exits 0."""
    try:
        r = subprocess.run(
            ["cargo", "check", "--workspace"],
            cwd=_ROOT, capture_output=True, timeout=600,
        )
        return r.returncode == 0
    except Exception:  # noqa: BLE001
        return False


def run_wiring_cycles_zero() -> bool:
    """Return True if no cycles of depth >= 2 detected."""
    try:
        r = subprocess.run(
            ["touring", "wiring", "cycles", "--min-depth", "2", "--format", "json"],
            capture_output=True, timeout=60,
        )
        if r.returncode != 0:
            return False
        data = json.loads(r.stdout.decode("utf-8") or "{}")
        return int(data.get("cycle_count", 0)) == 0
    except Exception:  # noqa: BLE001
        return False


def validate() -> dict:
    """Run all validation checks. Returns report dict."""
    results: list[dict] = []
    results.append(check_subtask(
        check_id='W4.1',
        name='Create touring-code skeleton + Cargo.toml',
        validation='cargo check -p touring-code exit 0; crate registrado em workspace.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W4.2',
        name='Move touring-ast/src/* → touring-code/src/parsers/tree_sitter/ + ast deep',
        validation='cargo check -p touring-code exit 0; pub mod ast exposto.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W4.3',
        name='Move touring-ast-polyglot/* → touring-code/src/parsers/ast_grep/',
        validation='cargo check -p touring-code --features parser-ast-grep exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W4.4',
        name='Move touring-language/* → touring-code/src/languages/',
        validation='touring_code::languages::Lang exposto.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W4.5',
        name='Move touring-semantics/* → touring-code/src/semantics/',
        validation='touring_code::semantics::Definition exposto.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W4.6',
        name='Define features lang-* + parser-*',
        validation='cargo check --no-default-features -p touring-code exit 0; cargo check --all-features -p touring-code exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W4.7',
        name='Update 25 consumers: touring_ast::X → touring_code::ast::X',
        validation="grep 'use touring_ast::' crates/ → apenas em touring-ast shim crate.",
        tdd_test='test_consumers_use_touring_code'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W4.8',
        name='Update 8 polyglot consumers',
        validation="grep 'touring_ast_polyglot' crates/ → apenas em shim.",
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W4.9',
        name='Update 3 language consumers',
        validation="grep 'touring_language' crates/ → apenas em shim.",
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W4.10',
        name='Update 2 semantics consumers',
        validation="grep 'touring_semantics' crates/ → apenas em shim.",
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W4.11',
        name='Bench parsing — regression < 5%',
        validation='Nenhum bench mais lento que -5%. Idealmente alguns ficam mais rápidos (cache compartilhado dentro do crate).',
        tdd_test='test_parsing_bench_within_5pct_of_baseline'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W4.12',
        name='Tests pass + cycle re-check',
        validation='cargo test workspace exit 0; cycle count ≤ baseline W3.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W4.13',
        name='Delete old crates (ast, ast-polyglot, language, semantics)',
        validation='ls crates/touring-{ast,ast-polyglot,language,semantics}/src/ → apenas lib.rs com pub use re-exports.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W4.14',
        name='Update workspace members',
        validation='grep \'"crates/touring-code"\' Cargo.toml; cargo check exit 0.',
        tdd_test=''
                  if False else '',
    ))

    # Wave-level invariants
    cargo_ok = run_cargo_check_workspace()
    cycles_ok = run_wiring_cycles_zero()

    results.append({
        "check": "wave-invariant",
        "name": "cargo check + wiring cycles zero",
        "validation": "cargo check exit 0 + 0 new cycles",
        "tdd_test": "",
        "passed": cargo_ok and cycles_ok,
        "details": f"cargo_check_ok={cargo_ok}, cycles_zero={cycles_ok}",
    })

    passed = sum(1 for r in results if r["passed"])
    total = len(results)
    score = passed / total if total > 0 else 0.0
    status = "PASS" if score >= 0.95 else "WARN" if score >= 0.70 else "FAIL"

    return {
        "wave": _WAVE_ID,
        "name": _WAVE_NAME,
        "timestamp": datetime.now(UTC).isoformat(),
        "checks_passed": passed,
        "checks_total": total,
        "score": round(score, 4),
        "status": status,
        "gate": _GATE,
        "results": results,
    }


def main() -> None:
    """Entry point. Prints report and saves checkpoint."""
    report = validate()
    print(f"\n{'='*60}")
    print(f"  {_WAVE_ID}: {_WAVE_NAME}")
    print(f"  Score: {report['score']:.4f} ({report['status']})")
    print(f"  Checks: {report['checks_passed']}/{report['checks_total']}")
    print(f"{'='*60}\n")
    for r in report["results"]:
        icon = "[PASS]" if r["passed"] else "[FAIL]"
        print(f"  {icon} {r['check']}: {r['name']}")
        if r["details"]:
            print(f"          {r['details']}")
    cp = _CHECKPOINTS_DIR / f"touring_premium_{_WAVE_ID}_{datetime.now(UTC).strftime('%Y%m%d')}.json"
    cp.parent.mkdir(parents=True, exist_ok=True)
    cp.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n  Checkpoint: {cp}")
    sys.exit(0 if report["status"] in ("PASS", "WARN") else 1)


if __name__ == "__main__":
    main()
