#!/usr/bin/env python3
"""Validator for W0: Prep & Safety Net.

Auto-generated by generate_plan.py — DO NOT edit manually.
Regenerate: python3 scripts/touring_premium_refactor_2026/generate_plan.py --emit-validators

Validates:
          - W0.1: touring-snapshot-pre-refactor-<DATE>.tar.gz existe + .sha256 sidecar; tamanho 80-150 MB esperado.
  - W0.2: docs/baselines/bench-pre-refactor-<DATE>.log existe; exit code 0.
  - W0.3: 2 logs em docs/baselines/, ambos exit 0.
  - W0.4: coverage-pre-refactor-<DATE>.json existe + parseável.
  - W0.5: 4 JSON files em docs/baselines/; cycle_count documentado.
  - W0.6: docs/plans/.../01-ARCHITECTURE.md existe; ≥ 600 LOC; menciona todos os 13 crates target + 46 atuais.
  - W0.7: docs/plans/.../02-DEPLOYMENT.md existe; ≥ 400 LOC.
  - W0.8: docs/plans/.../03-COMMERCIAL.md existe; ≥ 500 LOC.
  - W0.9: 26 .md em docs/plans/touring-premium-refactor-2026/; 16 .py em scripts/touring_premium_refactor_2026/.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
_CHECKPOINTS_DIR = _ROOT / ".claude" / "checkpoints"
_WAVE_ID = 'W0'
_WAVE_NAME = 'Prep & Safety Net'
_GATE = 'ADRs aprovados por Gabriel; baselines committed; cycle_count registrado (esperado: 2, depth max 618); cargo check exit 0.'


def check_subtask(check_id: str, name: str, validation: str, tdd_test: str) -> dict:
    """Run a single subtask check. Returns a result dict."""
    # TODO: implement real checks. Stub returns False with a clear "not implemented" note.
    return {
        "check": check_id,
        "name": name,
        "validation": validation,
        "tdd_test": tdd_test,
        "passed": False,
        "details": "Not yet implemented — replace stub with real check during W0 execution.",
    }


def run_cargo_check_workspace() -> bool:
    """Return True if `cargo check --workspace` exits 0."""
    try:
        r = subprocess.run(
            ["cargo", "check", "--workspace"],
            cwd=_ROOT, capture_output=True, timeout=600,
        )
        return r.returncode == 0
    except Exception:  # noqa: BLE001
        return False


def run_wiring_cycles_zero() -> bool:
    """Return True if no cycles of depth >= 2 detected."""
    try:
        r = subprocess.run(
            ["touring", "wiring", "cycles", "--min-depth", "2", "--format", "json"],
            capture_output=True, timeout=60,
        )
        if r.returncode != 0:
            return False
        data = json.loads(r.stdout.decode("utf-8") or "{}")
        return int(data.get("cycle_count", 0)) == 0
    except Exception:  # noqa: BLE001
        return False


def validate() -> dict:
    """Run all validation checks. Returns report dict."""
    results: list[dict] = []
    results.append(check_subtask(
        check_id='W0.1',
        name='Snapshot tar pre-refactor + SHA-256',
        validation='touring-snapshot-pre-refactor-<DATE>.tar.gz existe + .sha256 sidecar; tamanho 80-150 MB esperado.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W0.2',
        name='Bench baseline',
        validation='docs/baselines/bench-pre-refactor-<DATE>.log existe; exit code 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W0.3',
        name='CI baseline (cargo check + test --no-run)',
        validation='2 logs em docs/baselines/, ambos exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W0.4',
        name='Coverage baseline (cargo llvm-cov)',
        validation='coverage-pre-refactor-<DATE>.json existe + parseável.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W0.5',
        name='Wiring/cycle snapshot',
        validation='4 JSON files em docs/baselines/; cycle_count documentado.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W0.6',
        name='ADR-001 Premium Architecture Vision',
        validation='docs/plans/.../01-ARCHITECTURE.md existe; ≥ 600 LOC; menciona todos os 13 crates target + 46 atuais.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W0.7',
        name='ADR-002 Per-Project Deployment Model',
        validation='docs/plans/.../02-DEPLOYMENT.md existe; ≥ 400 LOC.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W0.8',
        name='ADR-003 Commercial Tiers + GTM Strategy',
        validation='docs/plans/.../03-COMMERCIAL.md existe; ≥ 500 LOC.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W0.9',
        name='MASTER-PLAN-2026 + 15 wave files + cross-cutting docs',
        validation='26 .md em docs/plans/touring-premium-refactor-2026/; 16 .py em scripts/touring_premium_refactor_2026/.',
        tdd_test=''
                  if False else '',
    ))

    # Wave-level invariants
    cargo_ok = run_cargo_check_workspace()
    cycles_ok = run_wiring_cycles_zero()

    results.append({
        "check": "wave-invariant",
        "name": "cargo check + wiring cycles zero",
        "validation": "cargo check exit 0 + 0 new cycles",
        "tdd_test": "",
        "passed": cargo_ok and cycles_ok,
        "details": f"cargo_check_ok={cargo_ok}, cycles_zero={cycles_ok}",
    })

    passed = sum(1 for r in results if r["passed"])
    total = len(results)
    score = passed / total if total > 0 else 0.0
    status = "PASS" if score >= 0.95 else "WARN" if score >= 0.70 else "FAIL"

    return {
        "wave": _WAVE_ID,
        "name": _WAVE_NAME,
        "timestamp": datetime.now(UTC).isoformat(),
        "checks_passed": passed,
        "checks_total": total,
        "score": round(score, 4),
        "status": status,
        "gate": _GATE,
        "results": results,
    }


def main() -> None:
    """Entry point. Prints report and saves checkpoint."""
    report = validate()
    print(f"\n{'='*60}")
    print(f"  {_WAVE_ID}: {_WAVE_NAME}")
    print(f"  Score: {report['score']:.4f} ({report['status']})")
    print(f"  Checks: {report['checks_passed']}/{report['checks_total']}")
    print(f"{'='*60}\n")
    for r in report["results"]:
        icon = "[PASS]" if r["passed"] else "[FAIL]"
        print(f"  {icon} {r['check']}: {r['name']}")
        if r["details"]:
            print(f"          {r['details']}")
    cp = _CHECKPOINTS_DIR / f"touring_premium_{_WAVE_ID}_{datetime.now(UTC).strftime('%Y%m%d')}.json"
    cp.parent.mkdir(parents=True, exist_ok=True)
    cp.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n  Checkpoint: {cp}")
    sys.exit(0 if report["status"] in ("PASS", "WARN") else 1)


if __name__ == "__main__":
    main()
