#!/usr/bin/env python3
"""Validator for W8: touring-hooks Internal Split.

Auto-generated by generate_plan.py — DO NOT edit manually.
Regenerate: python3 scripts/touring_premium_refactor_2026/generate_plan.py --emit-validators

Validates:
          - W8.1: cargo check -p touring-hooks-core ... exit 0 (6 crates).
  - W8.2: cargo check -p touring-hooks-core exit 0; touring-hooks-core sem deps de outros touring-hooks-*.
  - W8.3: cargo check -p touring-hooks-lifecycle exit 0.
  - W8.4: cargo check -p touring-hooks-cli exit 0; 70+ files reorganizados em subdiretórios temáticos.
  - W8.5: cargo check -p touring-hooks-tools exit 0; 99 MCP tools registered.
  - W8.6: cargo check -p touring-hooks-prediction exit 0.
  - W8.7: cargo check -p touring-hooks-rl exit 0.
  - W8.8: cargo public-api -p touring-hooks → diff vs pre-W8 baseline = 0 changes.
  - W8.9: cargo test --workspace exit 0; cada sub-crate ratio ≥ 20%.
  - W8.10: hdrhistogram P99 < 5ms para pre-edit; < 8ms para post-edit.
  - W8.11: cycle_count = 0; objective de zero cycles workspace-wide atingido.
  - W8.12: 24 hook events: 24 PASS, 0 FAIL.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
_CHECKPOINTS_DIR = _ROOT / ".claude" / "checkpoints"
_WAVE_ID = 'W8'
_WAVE_NAME = 'touring-hooks Internal Split'
_GATE = 'touring-hooks split em 6 sub-crates internos, façade externa intacta, 0 cycles workspace, hook hot-path < 5ms P99, 24 hook events smoke pass.'


def check_subtask(check_id: str, name: str, validation: str, tdd_test: str) -> dict:
    """Run a single subtask check. Returns a result dict."""
    # TODO: implement real checks. Stub returns False with a clear "not implemented" note.
    return {
        "check": check_id,
        "name": name,
        "validation": validation,
        "tdd_test": tdd_test,
        "passed": False,
        "details": "Not yet implemented — replace stub with real check during W8 execution.",
    }


def run_cargo_check_workspace() -> bool:
    """Return True if `cargo check --workspace` exits 0."""
    try:
        r = subprocess.run(
            ["cargo", "check", "--workspace"],
            cwd=_ROOT, capture_output=True, timeout=600,
        )
        return r.returncode == 0
    except Exception:  # noqa: BLE001
        return False


def run_wiring_cycles_zero() -> bool:
    """Return True if no cycles of depth >= 2 detected."""
    try:
        r = subprocess.run(
            ["touring", "wiring", "cycles", "--min-depth", "2", "--format", "json"],
            capture_output=True, timeout=60,
        )
        if r.returncode != 0:
            return False
        data = json.loads(r.stdout.decode("utf-8") or "{}")
        return int(data.get("cycle_count", 0)) == 0
    except Exception:  # noqa: BLE001
        return False


def validate() -> dict:
    """Run all validation checks. Returns report dict."""
    results: list[dict] = []
    results.append(check_subtask(
        check_id='W8.1',
        name='Create 6 internal sub-crates',
        validation='cargo check -p touring-hooks-core ... exit 0 (6 crates).',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W8.2',
        name='Move hooks/core/* → touring-hooks-core',
        validation='cargo check -p touring-hooks-core exit 0; touring-hooks-core sem deps de outros touring-hooks-*.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W8.3',
        name='Move lifecycle/* → touring-hooks-lifecycle',
        validation='cargo check -p touring-hooks-lifecycle exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W8.4',
        name='Move cli_handlers/* → touring-hooks-cli (70+ files)',
        validation='cargo check -p touring-hooks-cli exit 0; 70+ files reorganizados em subdiretórios temáticos.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W8.5',
        name='Move tools/* → touring-hooks-tools (MCP wiring)',
        validation='cargo check -p touring-hooks-tools exit 0; 99 MCP tools registered.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W8.6',
        name='Move layer7_prediction → touring-hooks-prediction',
        validation='cargo check -p touring-hooks-prediction exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W8.7',
        name='Move rl-related → touring-hooks-rl',
        validation='cargo check -p touring-hooks-rl exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W8.8',
        name='Façade touring-hooks reexports',
        validation='cargo public-api -p touring-hooks → diff vs pre-W8 baseline = 0 changes.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W8.9',
        name='Tests reorganize per sub-crate',
        validation='cargo test --workspace exit 0; cada sub-crate ratio ≥ 20%.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W8.10',
        name='Bench hook hot-path < 5ms P99',
        validation='hdrhistogram P99 < 5ms para pre-edit; < 8ms para post-edit.',
        tdd_test='test_pre_edit_p99_under_5ms'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W8.11',
        name='Cycle re-check — ZERO cycles',
        validation='cycle_count = 0; objective de zero cycles workspace-wide atingido.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W8.12',
        name='Validation: 24 hook events TACO smoke test',
        validation='24 hook events: 24 PASS, 0 FAIL.',
        tdd_test=''
                  if False else '',
    ))

    # Wave-level invariants
    cargo_ok = run_cargo_check_workspace()
    cycles_ok = run_wiring_cycles_zero()

    results.append({
        "check": "wave-invariant",
        "name": "cargo check + wiring cycles zero",
        "validation": "cargo check exit 0 + 0 new cycles",
        "tdd_test": "",
        "passed": cargo_ok and cycles_ok,
        "details": f"cargo_check_ok={cargo_ok}, cycles_zero={cycles_ok}",
    })

    passed = sum(1 for r in results if r["passed"])
    total = len(results)
    score = passed / total if total > 0 else 0.0
    status = "PASS" if score >= 0.95 else "WARN" if score >= 0.70 else "FAIL"

    return {
        "wave": _WAVE_ID,
        "name": _WAVE_NAME,
        "timestamp": datetime.now(UTC).isoformat(),
        "checks_passed": passed,
        "checks_total": total,
        "score": round(score, 4),
        "status": status,
        "gate": _GATE,
        "results": results,
    }


def main() -> None:
    """Entry point. Prints report and saves checkpoint."""
    report = validate()
    print(f"\n{'='*60}")
    print(f"  {_WAVE_ID}: {_WAVE_NAME}")
    print(f"  Score: {report['score']:.4f} ({report['status']})")
    print(f"  Checks: {report['checks_passed']}/{report['checks_total']}")
    print(f"{'='*60}\n")
    for r in report["results"]:
        icon = "[PASS]" if r["passed"] else "[FAIL]"
        print(f"  {icon} {r['check']}: {r['name']}")
        if r["details"]:
            print(f"          {r['details']}")
    cp = _CHECKPOINTS_DIR / f"touring_premium_{_WAVE_ID}_{datetime.now(UTC).strftime('%Y%m%d')}.json"
    cp.parent.mkdir(parents=True, exist_ok=True)
    cp.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n  Checkpoint: {cp}")
    sys.exit(0 if report["status"] in ("PASS", "WARN") else 1)


if __name__ == "__main__":
    main()
