#!/usr/bin/env python3
"""Validator for W14: Product Tiers & Distribution.

Auto-generated by generate_plan.py — DO NOT edit manually.
Regenerate: python3 scripts/touring_premium_refactor_2026/generate_plan.py --emit-validators

Validates:
          - W14.1: cargo build --release --no-default-features --features tier-free exit 0; binary ≤ 50 MB.
  - W14.2: touring login com license key válida → tier ativado.
  - W14.3: touring status → telemetry status reflects tier.
  - W14.4: touring registry sync exit 0 com private URL.
  - W14.5: touring login --sso github → browser opens → callback OK.
  - W14.6: touring config set enterprise.audit_log_path /tmp/audit.jsonl; tools logged.
  - W14.7: End-to-end: Stripe checkout → license email → touring login → tier-premium ativa.
  - W14.8: Push tag v1.0.0-rc.2 → workflow builds 6 targets → binaries em GH Release + signed.
  - W14.9: apt install touring (PPA) + brew install touring (homebrew/touring/touring) funciona.
  - W14.10: docker pull ghcr.io/touring/touring:1.0.0-distroless exit 0; size ≤ 60 MB.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
_CHECKPOINTS_DIR = _ROOT / ".claude" / "checkpoints"
_WAVE_ID = 'W14'
_WAVE_NAME = 'Product Tiers & Distribution'
_GATE = '1.0.0 GA published; install.touring.dev funcional; 4 tiers ativáveis via license key; SSO + audit + private registry operacionais para enterprise; 4 distro packages + 3 Docker images disponíveis.'


def check_subtask(check_id: str, name: str, validation: str, tdd_test: str) -> dict:
    """Run a single subtask check. Returns a result dict."""
    # TODO: implement real checks. Stub returns False with a clear "not implemented" note.
    return {
        "check": check_id,
        "name": name,
        "validation": validation,
        "tdd_test": tdd_test,
        "passed": False,
        "details": "Not yet implemented — replace stub with real check during W14 execution.",
    }


def run_cargo_check_workspace() -> bool:
    """Return True if `cargo check --workspace` exits 0."""
    try:
        r = subprocess.run(
            ["cargo", "check", "--workspace"],
            cwd=_ROOT, capture_output=True, timeout=600,
        )
        return r.returncode == 0
    except Exception:  # noqa: BLE001
        return False


def run_wiring_cycles_zero() -> bool:
    """Return True if no cycles of depth >= 2 detected."""
    try:
        r = subprocess.run(
            ["touring", "wiring", "cycles", "--min-depth", "2", "--format", "json"],
            capture_output=True, timeout=60,
        )
        if r.returncode != 0:
            return False
        data = json.loads(r.stdout.decode("utf-8") or "{}")
        return int(data.get("cycle_count", 0)) == 0
    except Exception:  # noqa: BLE001
        return False


def validate() -> dict:
    """Run all validation checks. Returns report dict."""
    results: list[dict] = []
    results.append(check_subtask(
        check_id='W14.1',
        name='Tiers as Cargo features',
        validation='cargo build --release --no-default-features --features tier-free exit 0; binary ≤ 50 MB.',
        tdd_test='test_tier_free_binary_size'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W14.2',
        name='License key system (JWT ed25519)',
        validation='touring login com license key válida → tier ativado.',
        tdd_test='test_expired_license_grace_30days'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W14.3',
        name='Telemetry tiered (free/std ON, premium/ent OFF)',
        validation='touring status → telemetry status reflects tier.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W14.4',
        name='Private registry support (enterprise)',
        validation='touring registry sync exit 0 com private URL.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W14.5',
        name='SSO scaffold (Okta/Google/GitHub)',
        validation='touring login --sso github → browser opens → callback OK.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W14.6',
        name='Audit log SIEM export (enterprise)',
        validation='touring config set enterprise.audit_log_path /tmp/audit.jsonl; tools logged.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W14.7',
        name='Pricing + license validation flow',
        validation='End-to-end: Stripe checkout → license email → touring login → tier-premium ativa.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W14.8',
        name='install.touring.dev + binary releases CI/CD',
        validation='Push tag v1.0.0-rc.2 → workflow builds 6 targets → binaries em GH Release + signed.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W14.9',
        name='Distro packages (deb, rpm, brew, scoop)',
        validation='apt install touring (PPA) + brew install touring (homebrew/touring/touring) funciona.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W14.10',
        name='Docker images (alpine, debian-slim, distroless)',
        validation='docker pull ghcr.io/touring/touring:1.0.0-distroless exit 0; size ≤ 60 MB.',
        tdd_test=''
                  if False else '',
    ))

    # Wave-level invariants
    cargo_ok = run_cargo_check_workspace()
    cycles_ok = run_wiring_cycles_zero()

    results.append({
        "check": "wave-invariant",
        "name": "cargo check + wiring cycles zero",
        "validation": "cargo check exit 0 + 0 new cycles",
        "tdd_test": "",
        "passed": cargo_ok and cycles_ok,
        "details": f"cargo_check_ok={cargo_ok}, cycles_zero={cycles_ok}",
    })

    passed = sum(1 for r in results if r["passed"])
    total = len(results)
    score = passed / total if total > 0 else 0.0
    status = "PASS" if score >= 0.95 else "WARN" if score >= 0.70 else "FAIL"

    return {
        "wave": _WAVE_ID,
        "name": _WAVE_NAME,
        "timestamp": datetime.now(UTC).isoformat(),
        "checks_passed": passed,
        "checks_total": total,
        "score": round(score, 4),
        "status": status,
        "gate": _GATE,
        "results": results,
    }


def main() -> None:
    """Entry point. Prints report and saves checkpoint."""
    report = validate()
    print(f"\n{'='*60}")
    print(f"  {_WAVE_ID}: {_WAVE_NAME}")
    print(f"  Score: {report['score']:.4f} ({report['status']})")
    print(f"  Checks: {report['checks_passed']}/{report['checks_total']}")
    print(f"{'='*60}\n")
    for r in report["results"]:
        icon = "[PASS]" if r["passed"] else "[FAIL]"
        print(f"  {icon} {r['check']}: {r['name']}")
        if r["details"]:
            print(f"          {r['details']}")
    cp = _CHECKPOINTS_DIR / f"touring_premium_{_WAVE_ID}_{datetime.now(UTC).strftime('%Y%m%d')}.json"
    cp.parent.mkdir(parents=True, exist_ok=True)
    cp.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n  Checkpoint: {cp}")
    sys.exit(0 if report["status"] in ("PASS", "WARN") else 1)


if __name__ == "__main__":
    main()
