#!/usr/bin/env python3
"""Validator for W5: touring-storage Fusion.

Auto-generated by generate_plan.py — DO NOT edit manually.
Regenerate: python3 scripts/touring_premium_refactor_2026/generate_plan.py --emit-validators

Validates:
          - W5.1: cargo check -p touring-storage exit 0.
  - W5.2: cargo check -p touring-storage --features storage-fts exit 0.
  - W5.3: cargo test -p touring-storage vfs exit 0.
  - W5.4: cargo test -p touring-storage salsa: ≥ 5 tests pass.
  - W5.5: cargo check --features storage-vec-qdrant exit 0.
  - W5.6: cargo check --features storage-emb-voyage exit 0.
  - W5.7: cargo test -p touring-storage hybrid_search: ≥ 8 tests pass.
  - W5.8: cargo check --workspace exit 0; shims em 6 crates antigos.
  - W5.9: Bench delta vs baseline ≥ -5%.
  - W5.10: ls crates/touring-{index,vfs,...}/ → shims only.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
_CHECKPOINTS_DIR = _ROOT / ".claude" / "checkpoints"
_WAVE_ID = 'W5'
_WAVE_NAME = 'touring-storage Fusion'
_GATE = 'touring-storage 10k LOC, 11 features, ≥ 25% test ratio (0% crates repagos), < 5% perf regression, 15 consumers updated.'


def check_subtask(check_id: str, name: str, validation: str, tdd_test: str) -> dict:
    """Run a single subtask check. Returns a result dict."""
    # TODO: implement real checks. Stub returns False with a clear "not implemented" note.
    return {
        "check": check_id,
        "name": name,
        "validation": validation,
        "tdd_test": tdd_test,
        "passed": False,
        "details": "Not yet implemented — replace stub with real check during W5 execution.",
    }


def run_cargo_check_workspace() -> bool:
    """Return True if `cargo check --workspace` exits 0."""
    try:
        r = subprocess.run(
            ["cargo", "check", "--workspace"],
            cwd=_ROOT, capture_output=True, timeout=600,
        )
        return r.returncode == 0
    except Exception:  # noqa: BLE001
        return False


def run_wiring_cycles_zero() -> bool:
    """Return True if no cycles of depth >= 2 detected."""
    try:
        r = subprocess.run(
            ["touring", "wiring", "cycles", "--min-depth", "2", "--format", "json"],
            capture_output=True, timeout=60,
        )
        if r.returncode != 0:
            return False
        data = json.loads(r.stdout.decode("utf-8") or "{}")
        return int(data.get("cycle_count", 0)) == 0
    except Exception:  # noqa: BLE001
        return False


def validate() -> dict:
    """Run all validation checks. Returns report dict."""
    results: list[dict] = []
    results.append(check_subtask(
        check_id='W5.1',
        name='Create touring-storage skeleton',
        validation='cargo check -p touring-storage exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W5.2',
        name='Move touring-index → storage/src/fts/',
        validation='cargo check -p touring-storage --features storage-fts exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W5.3',
        name='Move touring-vfs → storage/src/vfs/',
        validation='cargo test -p touring-storage vfs exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W5.4',
        name='Move touring-incremental-salsa → storage/src/salsa/',
        validation='cargo test -p touring-storage salsa: ≥ 5 tests pass.',
        tdd_test='test_salsa_incremental_invalidation'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W5.5',
        name='Move touring-vector-store → storage/src/vec/',
        validation='cargo check --features storage-vec-qdrant exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W5.6',
        name='Move touring-embeddings → storage/src/embeddings/',
        validation='cargo check --features storage-emb-voyage exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W5.7',
        name='Move touring-search-fusion → storage/src/hybrid_search/',
        validation='cargo test -p touring-storage hybrid_search: ≥ 8 tests pass.',
        tdd_test='test_hybrid_search_rrf_fusion'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W5.8',
        name='Define features storage-* + update 15 consumers',
        validation='cargo check --workspace exit 0; shims em 6 crates antigos.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W5.9',
        name='Bench query latency — regression < 5%',
        validation='Bench delta vs baseline ≥ -5%.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W5.10',
        name='Delete old crates + update workspace',
        validation='ls crates/touring-{index,vfs,...}/ → shims only.',
        tdd_test=''
                  if False else '',
    ))

    # Wave-level invariants
    cargo_ok = run_cargo_check_workspace()
    cycles_ok = run_wiring_cycles_zero()

    results.append({
        "check": "wave-invariant",
        "name": "cargo check + wiring cycles zero",
        "validation": "cargo check exit 0 + 0 new cycles",
        "tdd_test": "",
        "passed": cargo_ok and cycles_ok,
        "details": f"cargo_check_ok={cargo_ok}, cycles_zero={cycles_ok}",
    })

    passed = sum(1 for r in results if r["passed"])
    total = len(results)
    score = passed / total if total > 0 else 0.0
    status = "PASS" if score >= 0.95 else "WARN" if score >= 0.70 else "FAIL"

    return {
        "wave": _WAVE_ID,
        "name": _WAVE_NAME,
        "timestamp": datetime.now(UTC).isoformat(),
        "checks_passed": passed,
        "checks_total": total,
        "score": round(score, 4),
        "status": status,
        "gate": _GATE,
        "results": results,
    }


def main() -> None:
    """Entry point. Prints report and saves checkpoint."""
    report = validate()
    print(f"\n{'='*60}")
    print(f"  {_WAVE_ID}: {_WAVE_NAME}")
    print(f"  Score: {report['score']:.4f} ({report['status']})")
    print(f"  Checks: {report['checks_passed']}/{report['checks_total']}")
    print(f"{'='*60}\n")
    for r in report["results"]:
        icon = "[PASS]" if r["passed"] else "[FAIL]"
        print(f"  {icon} {r['check']}: {r['name']}")
        if r["details"]:
            print(f"          {r['details']}")
    cp = _CHECKPOINTS_DIR / f"touring_premium_{_WAVE_ID}_{datetime.now(UTC).strftime('%Y%m%d')}.json"
    cp.parent.mkdir(parents=True, exist_ok=True)
    cp.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n  Checkpoint: {cp}")
    sys.exit(0 if report["status"] in ("PASS", "WARN") else 1)


if __name__ == "__main__":
    main()
