#!/usr/bin/env python3
"""Validator for W3: Layer 1-2 Stabilization.

Auto-generated by generate_plan.py — DO NOT edit manually.
Regenerate: python3 scripts/touring_premium_refactor_2026/generate_plan.py --emit-validators

Validates:
          - W3.1: cargo check --workspace exit 0; consumers ainda compilam via shim.
  - W3.2: cargo check exit 0; embedding/ não mais em foundation/src/.
  - W3.3: mvkl/ presente em foundation/src/.
  - W3.4: cargo check exit 0; foundation::rules pública.
  - W3.5: cargo check exit 0; foundation::types pública.
  - W3.6: cargo check exit 0; foundation::telemetry pública.
  - W3.7: cargo check exit 0; foundation::sentinel pública.
  - W3.8: cargo check exit 0; foundation::activity pública.
  - W3.9: wc -l foundation/src/**/*.rs vs tests/ ≥ 0.25.
  - W3.10: identity tests ≥ 30%; proptest para EntityId determinism.
  - W3.11: cycle depth max < 618 (redução documentada).
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
_CHECKPOINTS_DIR = _ROOT / ".claude" / "checkpoints"
_WAVE_ID = 'W3'
_WAVE_NAME = 'Layer 1-2 Stabilization'
_GATE = 'touring-foundation ≤ 18k LOC; 5 crates absorvidos; identity standalone OK; test ratio ≥ 25% foundation, ≥ 30% identity; cycle reduction vs W0 baseline documentada.'


def check_subtask(check_id: str, name: str, validation: str, tdd_test: str) -> dict:
    """Run a single subtask check. Returns a result dict."""
    # TODO: implement real checks. Stub returns False with a clear "not implemented" note.
    return {
        "check": check_id,
        "name": name,
        "validation": validation,
        "tdd_test": tdd_test,
        "passed": False,
        "details": "Not yet implemented — replace stub with real check during W3 execution.",
    }


def run_cargo_check_workspace() -> bool:
    """Return True if `cargo check --workspace` exits 0."""
    try:
        r = subprocess.run(
            ["cargo", "check", "--workspace"],
            cwd=_ROOT, capture_output=True, timeout=600,
        )
        return r.returncode == 0
    except Exception:  # noqa: BLE001
        return False


def run_wiring_cycles_zero() -> bool:
    """Return True if no cycles of depth >= 2 detected."""
    try:
        r = subprocess.run(
            ["touring", "wiring", "cycles", "--min-depth", "2", "--format", "json"],
            capture_output=True, timeout=60,
        )
        if r.returncode != 0:
            return False
        data = json.loads(r.stdout.decode("utf-8") or "{}")
        return int(data.get("cycle_count", 0)) == 0
    except Exception:  # noqa: BLE001
        return False


def validate() -> dict:
    """Run all validation checks. Returns report dict."""
    results: list[dict] = []
    results.append(check_subtask(
        check_id='W3.1',
        name='Rename touring-core → touring-foundation (+ shim)',
        validation='cargo check --workspace exit 0; consumers ainda compilam via shim.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W3.2',
        name='Slim foundation: extract embedding/ (→ W5 storage)',
        validation='cargo check exit 0; embedding/ não mais em foundation/src/.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W3.3',
        name='Extract mvkl/ (multi-version key list) — keep in foundation',
        validation='mvkl/ presente em foundation/src/.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W3.4',
        name='Absorve touring-rule-engine → foundation/rules/',
        validation='cargo check exit 0; foundation::rules pública.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W3.5',
        name='Absorve touring-definitions → foundation/types/',
        validation='cargo check exit 0; foundation::types pública.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W3.6',
        name='Absorve touring-telemetry → foundation/telemetry/',
        validation='cargo check exit 0; foundation::telemetry pública.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W3.7',
        name='Absorve touring-resource-monitor → foundation/sentinel/',
        validation='cargo check exit 0; foundation::sentinel pública.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W3.8',
        name='Absorve touring-activity → foundation/activity/',
        validation='cargo check exit 0; foundation::activity pública.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W3.9',
        name='Foundation tests ≥ 25% LOC ratio',
        validation='wc -l foundation/src/**/*.rs vs tests/ ≥ 0.25.',
        tdd_test='test_foundation_coverage_25pct'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W3.10',
        name='Identity tests ≥ 30% ratio',
        validation='identity tests ≥ 30%; proptest para EntityId determinism.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W3.11',
        name='Cycle re-check',
        validation='cycle depth max < 618 (redução documentada).',
        tdd_test=''
                  if False else '',
    ))

    # Wave-level invariants
    cargo_ok = run_cargo_check_workspace()
    cycles_ok = run_wiring_cycles_zero()

    results.append({
        "check": "wave-invariant",
        "name": "cargo check + wiring cycles zero",
        "validation": "cargo check exit 0 + 0 new cycles",
        "tdd_test": "",
        "passed": cargo_ok and cycles_ok,
        "details": f"cargo_check_ok={cargo_ok}, cycles_zero={cycles_ok}",
    })

    passed = sum(1 for r in results if r["passed"])
    total = len(results)
    score = passed / total if total > 0 else 0.0
    status = "PASS" if score >= 0.95 else "WARN" if score >= 0.70 else "FAIL"

    return {
        "wave": _WAVE_ID,
        "name": _WAVE_NAME,
        "timestamp": datetime.now(UTC).isoformat(),
        "checks_passed": passed,
        "checks_total": total,
        "score": round(score, 4),
        "status": status,
        "gate": _GATE,
        "results": results,
    }


def main() -> None:
    """Entry point. Prints report and saves checkpoint."""
    report = validate()
    print(f"\n{'='*60}")
    print(f"  {_WAVE_ID}: {_WAVE_NAME}")
    print(f"  Score: {report['score']:.4f} ({report['status']})")
    print(f"  Checks: {report['checks_passed']}/{report['checks_total']}")
    print(f"{'='*60}\n")
    for r in report["results"]:
        icon = "[PASS]" if r["passed"] else "[FAIL]"
        print(f"  {icon} {r['check']}: {r['name']}")
        if r["details"]:
            print(f"          {r['details']}")
    cp = _CHECKPOINTS_DIR / f"touring_premium_{_WAVE_ID}_{datetime.now(UTC).strftime('%Y%m%d')}.json"
    cp.parent.mkdir(parents=True, exist_ok=True)
    cp.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n  Checkpoint: {cp}")
    sys.exit(0 if report["status"] in ("PASS", "WARN") else 1)


if __name__ == "__main__":
    main()
