#!/usr/bin/env python3
"""Validator for W6: touring-intelligence Fusion.

Auto-generated by generate_plan.py — DO NOT edit manually.
Regenerate: python3 scripts/touring_premium_refactor_2026/generate_plan.py --emit-validators

Validates:
          - W6.0: cortex tests LOC ≥ 4.7k; mutation kill rate ≥ 50%.
  - W6.1: cargo check -p touring-intelligence exit 0.
  - W6.2: cargo check -p touring-intelligence --features intel-reasoning exit 0.
  - W6.3: cargo check -p touring-intelligence --features intel-rl exit 0.
  - W6.4: cargo check -p touring-intelligence --features intel-pipeline exit 0.
  - W6.5: cargo check -p touring-intelligence --features intel-ann exit 0.
  - W6.6: cargo hack --feature-powerset check exit 0.
  - W6.7: cargo check --workspace exit 0.
  - W6.8: 3 benches dentro de -5% vs baseline.
  - W6.9: cycle_count ≤ 0 OR max_depth < 10; macrociclo de 618 GONE.
  - W6.10: ls crates/touring-{cognitive,learning,cortex,antt}/ → shims only.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
_CHECKPOINTS_DIR = _ROOT / ".claude" / "checkpoints"
_WAVE_ID = 'W6'
_WAVE_NAME = 'touring-intelligence Fusion'
_GATE = 'touring-intelligence 90k LOC, 11 features, ≥ 20% test ratio (cortex repago em W6.0), MACROCICLO 618 ELIMINADO, < 5% perf regression em MCTS/ANN/bandit.'


def check_subtask(check_id: str, name: str, validation: str, tdd_test: str) -> dict:
    """Run a single subtask check. Returns a result dict."""
    # TODO: implement real checks. Stub returns False with a clear "not implemented" note.
    return {
        "check": check_id,
        "name": name,
        "validation": validation,
        "tdd_test": tdd_test,
        "passed": False,
        "details": "Not yet implemented — replace stub with real check during W6 execution.",
    }


def run_cargo_check_workspace() -> bool:
    """Return True if `cargo check --workspace` exits 0."""
    try:
        r = subprocess.run(
            ["cargo", "check", "--workspace"],
            cwd=_ROOT, capture_output=True, timeout=600,
        )
        return r.returncode == 0
    except Exception:  # noqa: BLE001
        return False


def run_wiring_cycles_zero() -> bool:
    """Return True if no cycles of depth >= 2 detected."""
    try:
        r = subprocess.run(
            ["touring", "wiring", "cycles", "--min-depth", "2", "--format", "json"],
            capture_output=True, timeout=60,
        )
        if r.returncode != 0:
            return False
        data = json.loads(r.stdout.decode("utf-8") or "{}")
        return int(data.get("cycle_count", 0)) == 0
    except Exception:  # noqa: BLE001
        return False


def validate() -> dict:
    """Run all validation checks. Returns report dict."""
    results: list[dict] = []
    results.append(check_subtask(
        check_id='W6.0',
        name='🛑 PRE-TEST: cortex test ratio 0.56% → 15%',
        validation='cortex tests LOC ≥ 4.7k; mutation kill rate ≥ 50%.',
        tdd_test='test_cortex_coverage_15pct'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W6.1',
        name='Create touring-intelligence skeleton',
        validation='cargo check -p touring-intelligence exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W6.2',
        name='Move touring-cognitive → intelligence/src/reasoning/',
        validation='cargo check -p touring-intelligence --features intel-reasoning exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W6.3',
        name='Move touring-learning → intelligence/src/rl/',
        validation='cargo check -p touring-intelligence --features intel-rl exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W6.4',
        name='Move touring-cortex → intelligence/src/pipeline/',
        validation='cargo check -p touring-intelligence --features intel-pipeline exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W6.5',
        name='Move touring-antt → intelligence/src/ann/',
        validation='cargo check -p touring-intelligence --features intel-ann exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W6.6',
        name='Define 11 features intel-* opt-in',
        validation='cargo hack --feature-powerset check exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W6.7',
        name='Update 12 consumers',
        validation='cargo check --workspace exit 0.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W6.8',
        name='Bench MCTS / ANN / bandit — regression < 5%',
        validation='3 benches dentro de -5% vs baseline.',
        tdd_test='test_intel_benches_within_5pct'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W6.9',
        name='Tests pass + cycle re-check',
        validation='cycle_count ≤ 0 OR max_depth < 10; macrociclo de 618 GONE.',
        tdd_test='test_no_macrocycle_618'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W6.10',
        name='Delete old crates + workspace update',
        validation='ls crates/touring-{cognitive,learning,cortex,antt}/ → shims only.',
        tdd_test=''
                  if False else '',
    ))

    # Wave-level invariants
    cargo_ok = run_cargo_check_workspace()
    cycles_ok = run_wiring_cycles_zero()

    results.append({
        "check": "wave-invariant",
        "name": "cargo check + wiring cycles zero",
        "validation": "cargo check exit 0 + 0 new cycles",
        "tdd_test": "",
        "passed": cargo_ok and cycles_ok,
        "details": f"cargo_check_ok={cargo_ok}, cycles_zero={cycles_ok}",
    })

    passed = sum(1 for r in results if r["passed"])
    total = len(results)
    score = passed / total if total > 0 else 0.0
    status = "PASS" if score >= 0.95 else "WARN" if score >= 0.70 else "FAIL"

    return {
        "wave": _WAVE_ID,
        "name": _WAVE_NAME,
        "timestamp": datetime.now(UTC).isoformat(),
        "checks_passed": passed,
        "checks_total": total,
        "score": round(score, 4),
        "status": status,
        "gate": _GATE,
        "results": results,
    }


def main() -> None:
    """Entry point. Prints report and saves checkpoint."""
    report = validate()
    print(f"\n{'='*60}")
    print(f"  {_WAVE_ID}: {_WAVE_NAME}")
    print(f"  Score: {report['score']:.4f} ({report['status']})")
    print(f"  Checks: {report['checks_passed']}/{report['checks_total']}")
    print(f"{'='*60}\n")
    for r in report["results"]:
        icon = "[PASS]" if r["passed"] else "[FAIL]"
        print(f"  {icon} {r['check']}: {r['name']}")
        if r["details"]:
            print(f"          {r['details']}")
    cp = _CHECKPOINTS_DIR / f"touring_premium_{_WAVE_ID}_{datetime.now(UTC).strftime('%Y%m%d')}.json"
    cp.parent.mkdir(parents=True, exist_ok=True)
    cp.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n  Checkpoint: {cp}")
    sys.exit(0 if report["status"] in ("PASS", "WARN") else 1)


if __name__ == "__main__":
    main()
