#!/usr/bin/env python3
"""Validator for W1: Dead Code Purge.

Auto-generated by generate_plan.py — DO NOT edit manually.
Regenerate: python3 scripts/touring_premium_refactor_2026/generate_plan.py --emit-validators

Validates:
          - W1.1: cargo check --workspace exit 0; nenhuma referência restante.
  - W1.2: cargo check --workspace exit 0; touring wiring orphans -j no new orphans.
  - W1.3: cargo check --workspace --all-targets exit 0; 0 unused warnings novos.
  - W1.4: touring wiring cycles --min-depth 2: Cycle #1 GONE; cycle_count = 1 (only macrociclo of depth 618 remains).
  - W1.5: cargo check --workspace exit 0; cargo test --workspace --no-run exit 0; orphan delta ≤ 0.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
_CHECKPOINTS_DIR = _ROOT / ".claude" / "checkpoints"
_WAVE_ID = 'W1'
_WAVE_NAME = 'Dead Code Purge'
_GATE = '4 crates removidos; Cycle #1 eliminado; cargo check + test --no-run exit 0; orphans não aumentaram.'


def check_subtask(check_id: str, name: str, validation: str, tdd_test: str) -> dict:
    """Run a single subtask check. Returns a result dict."""
    # TODO: implement real checks. Stub returns False with a clear "not implemented" note.
    return {
        "check": check_id,
        "name": name,
        "validation": validation,
        "tdd_test": tdd_test,
        "passed": False,
        "details": "Not yet implemented — replace stub with real check during W1 execution.",
    }


def run_cargo_check_workspace() -> bool:
    """Return True if `cargo check --workspace` exits 0."""
    try:
        r = subprocess.run(
            ["cargo", "check", "--workspace"],
            cwd=_ROOT, capture_output=True, timeout=600,
        )
        return r.returncode == 0
    except Exception:  # noqa: BLE001
        return False


def run_wiring_cycles_zero() -> bool:
    """Return True if no cycles of depth >= 2 detected."""
    try:
        r = subprocess.run(
            ["touring", "wiring", "cycles", "--min-depth", "2", "--format", "json"],
            capture_output=True, timeout=60,
        )
        if r.returncode != 0:
            return False
        data = json.loads(r.stdout.decode("utf-8") or "{}")
        return int(data.get("cycle_count", 0)) == 0
    except Exception:  # noqa: BLE001
        return False


def validate() -> dict:
    """Run all validation checks. Returns report dict."""
    results: list[dict] = []
    results.append(check_subtask(
        check_id='W1.1',
        name='DELETE touring-semantic-spike',
        validation='cargo check --workspace exit 0; nenhuma referência restante.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W1.2',
        name='DELETE touring-wasm-{client,common,server}',
        validation='cargo check --workspace exit 0; touring wiring orphans -j no new orphans.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W1.3',
        name='Audit + clean dead reexports',
        validation='cargo check --workspace --all-targets exit 0; 0 unused warnings novos.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W1.4',
        name='Fix Cycle #1 (file_tools ↔ project_tools intra-server)',
        validation='touring wiring cycles --min-depth 2: Cycle #1 GONE; cycle_count = 1 (only macrociclo of depth 618 remains).',
        tdd_test='test_no_cycle_file_project_tools'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W1.5',
        name='Update workspace + validate',
        validation='cargo check --workspace exit 0; cargo test --workspace --no-run exit 0; orphan delta ≤ 0.',
        tdd_test=''
                  if False else '',
    ))

    # Wave-level invariants
    cargo_ok = run_cargo_check_workspace()
    cycles_ok = run_wiring_cycles_zero()

    results.append({
        "check": "wave-invariant",
        "name": "cargo check + wiring cycles zero",
        "validation": "cargo check exit 0 + 0 new cycles",
        "tdd_test": "",
        "passed": cargo_ok and cycles_ok,
        "details": f"cargo_check_ok={cargo_ok}, cycles_zero={cycles_ok}",
    })

    passed = sum(1 for r in results if r["passed"])
    total = len(results)
    score = passed / total if total > 0 else 0.0
    status = "PASS" if score >= 0.95 else "WARN" if score >= 0.70 else "FAIL"

    return {
        "wave": _WAVE_ID,
        "name": _WAVE_NAME,
        "timestamp": datetime.now(UTC).isoformat(),
        "checks_passed": passed,
        "checks_total": total,
        "score": round(score, 4),
        "status": status,
        "gate": _GATE,
        "results": results,
    }


def main() -> None:
    """Entry point. Prints report and saves checkpoint."""
    report = validate()
    print(f"\n{'='*60}")
    print(f"  {_WAVE_ID}: {_WAVE_NAME}")
    print(f"  Score: {report['score']:.4f} ({report['status']})")
    print(f"  Checks: {report['checks_passed']}/{report['checks_total']}")
    print(f"{'='*60}\n")
    for r in report["results"]:
        icon = "[PASS]" if r["passed"] else "[FAIL]"
        print(f"  {icon} {r['check']}: {r['name']}")
        if r["details"]:
            print(f"          {r['details']}")
    cp = _CHECKPOINTS_DIR / f"touring_premium_{_WAVE_ID}_{datetime.now(UTC).strftime('%Y%m%d')}.json"
    cp.parent.mkdir(parents=True, exist_ok=True)
    cp.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n  Checkpoint: {cp}")
    sys.exit(0 if report["status"] in ("PASS", "WARN") else 1)


if __name__ == "__main__":
    main()
