#!/usr/bin/env python3
"""Validator for W12: Per-Project Deployment.

Auto-generated by generate_plan.py — DO NOT edit manually.
Regenerate: python3 scripts/touring_premium_refactor_2026/generate_plan.py --emit-validators

Validates:
          - W12.1: touring init -> .touring/{touring.toml,data/,bin/,hooks/} exists.
  - W12.2: ls ~/.touring/toolchains/ shows ≥ 1 version; ~/.touring/default file aponta para versão válida.
  - W12.3: touring toolchain list mostra versões instaladas; rollback funciona.
  - W12.4: Config merge testado em 4 cenários; conflicts resolvidos.
  - W12.5: lsof | grep daemon.sock retorna N sockets para N projetos abertos.
  - W12.6: Em projeto com .touring/, hook usa local binary. Fora, usa default toolchain.
  - W12.7: touring memory recall em projeto migrado retorna lessons originais.
  - W12.8: curl https://install.touring.dev | sh -- --dry-run → imprime steps sem mutar disco.
  - W12.9: 5 workflows core funcionam em konverter via .touring/ local.
  - W12.10: 5 workflows core funcionam em analise via .touring/ local.
  - W12.11: 3 guides em docs/guide/; mdbook builds; cada guide ≥ 200 LOC.
  - W12.12: GitHub Actions matrix 2/2 green.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
_CHECKPOINTS_DIR = _ROOT / ".claude" / "checkpoints"
_WAVE_ID = 'W12'
_WAVE_NAME = 'Per-Project Deployment'
_GATE = '2 pilots rodando per-project; install.touring.dev funcional; backward compat --legacy-global preservado; cross-platform Linux+macOS green.'


def check_subtask(check_id: str, name: str, validation: str, tdd_test: str) -> dict:
    """Run a single subtask check. Returns a result dict."""
    # TODO: implement real checks. Stub returns False with a clear "not implemented" note.
    return {
        "check": check_id,
        "name": name,
        "validation": validation,
        "tdd_test": tdd_test,
        "passed": False,
        "details": "Not yet implemented — replace stub with real check during W12 execution.",
    }


def run_cargo_check_workspace() -> bool:
    """Return True if `cargo check --workspace` exits 0."""
    try:
        r = subprocess.run(
            ["cargo", "check", "--workspace"],
            cwd=_ROOT, capture_output=True, timeout=600,
        )
        return r.returncode == 0
    except Exception:  # noqa: BLE001
        return False


def run_wiring_cycles_zero() -> bool:
    """Return True if no cycles of depth >= 2 detected."""
    try:
        r = subprocess.run(
            ["touring", "wiring", "cycles", "--min-depth", "2", "--format", "json"],
            capture_output=True, timeout=60,
        )
        if r.returncode != 0:
            return False
        data = json.loads(r.stdout.decode("utf-8") or "{}")
        return int(data.get("cycle_count", 0)) == 0
    except Exception:  # noqa: BLE001
        return False


def validate() -> dict:
    """Run all validation checks. Returns report dict."""
    results: list[dict] = []
    results.append(check_subtask(
        check_id='W12.1',
        name='Implement `touring init` CLI',
        validation='touring init -> .touring/{touring.toml,data/,bin/,hooks/} exists.',
        tdd_test='test_touring_init_creates_structure'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W12.2',
        name='Implement ~/.touring/ toolchain manager',
        validation='ls ~/.touring/toolchains/ shows ≥ 1 version; ~/.touring/default file aponta para versão válida.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W12.3',
        name='Implement `touring update/toolchain/component`',
        validation='touring toolchain list mostra versões instaladas; rollback funciona.',
        tdd_test='test_toolchain_install_rollback'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W12.4',
        name='Implement layered config loader',
        validation='Config merge testado em 4 cenários; conflicts resolvidos.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W12.5',
        name='Daemon multi-instance (per-project socket)',
        validation='lsof | grep daemon.sock retorna N sockets para N projetos abertos.',
        tdd_test='test_two_projects_two_daemons'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W12.6',
        name='Hook dispatcher walk-up shim',
        validation='Em projeto com .touring/, hook usa local binary. Fora, usa default toolchain.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W12.7',
        name='Implement `touring migrate --from-global`',
        validation='touring memory recall em projeto migrado retorna lessons originais.',
        tdd_test='test_migrate_preserves_project_memory'
                  if True else '',
    ))

    results.append(check_subtask(
        check_id='W12.8',
        name='External installer (install.touring.dev)',
        validation='curl https://install.touring.dev | sh -- --dry-run → imprime steps sem mutar disco.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W12.9',
        name='Pilot konverter: install + validate workflows',
        validation='5 workflows core funcionam em konverter via .touring/ local.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W12.10',
        name='Pilot analise: install + validate',
        validation='5 workflows core funcionam em analise via .touring/ local.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W12.11',
        name='Documentation: getting-started + migration guide',
        validation='3 guides em docs/guide/; mdbook builds; cada guide ≥ 200 LOC.',
        tdd_test=''
                  if False else '',
    ))

    results.append(check_subtask(
        check_id='W12.12',
        name='Cross-platform testing (Linux + macOS)',
        validation='GitHub Actions matrix 2/2 green.',
        tdd_test=''
                  if False else '',
    ))

    # Wave-level invariants
    cargo_ok = run_cargo_check_workspace()
    cycles_ok = run_wiring_cycles_zero()

    results.append({
        "check": "wave-invariant",
        "name": "cargo check + wiring cycles zero",
        "validation": "cargo check exit 0 + 0 new cycles",
        "tdd_test": "",
        "passed": cargo_ok and cycles_ok,
        "details": f"cargo_check_ok={cargo_ok}, cycles_zero={cycles_ok}",
    })

    passed = sum(1 for r in results if r["passed"])
    total = len(results)
    score = passed / total if total > 0 else 0.0
    status = "PASS" if score >= 0.95 else "WARN" if score >= 0.70 else "FAIL"

    return {
        "wave": _WAVE_ID,
        "name": _WAVE_NAME,
        "timestamp": datetime.now(UTC).isoformat(),
        "checks_passed": passed,
        "checks_total": total,
        "score": round(score, 4),
        "status": status,
        "gate": _GATE,
        "results": results,
    }


def main() -> None:
    """Entry point. Prints report and saves checkpoint."""
    report = validate()
    print(f"\n{'='*60}")
    print(f"  {_WAVE_ID}: {_WAVE_NAME}")
    print(f"  Score: {report['score']:.4f} ({report['status']})")
    print(f"  Checks: {report['checks_passed']}/{report['checks_total']}")
    print(f"{'='*60}\n")
    for r in report["results"]:
        icon = "[PASS]" if r["passed"] else "[FAIL]"
        print(f"  {icon} {r['check']}: {r['name']}")
        if r["details"]:
            print(f"          {r['details']}")
    cp = _CHECKPOINTS_DIR / f"touring_premium_{_WAVE_ID}_{datetime.now(UTC).strftime('%Y%m%d')}.json"
    cp.parent.mkdir(parents=True, exist_ok=True)
    cp.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n  Checkpoint: {cp}")
    sys.exit(0 if report["status"] in ("PASS", "WARN") else 1)


if __name__ == "__main__":
    main()
