#!/usr/bin/env python3
"""W8.6 — Generate touring-hooks/src/lib.rs façade with pub use re-exports.

After W8.1-W8.5 split touring-hooks into 8 sub-crates, the façade `touring-hooks`
crate becomes a thin re-export shell. This script reads the bucket map
(data/w8-hooks-split-plan.json) and emits the lib.rs that re-exports the
public API of each sub-crate.

Outputs:
  - staging/w8-touring-hooks-facade-lib.rs    (drop-in replacement for src/lib.rs)
  - staging/w8-touring-hooks-Cargo.toml       (updated [dependencies] only)
  - data/w8-facade-manifest.json

Usage
-----
    python3 w8_hooks_facade_emitter.py
    python3 w8_hooks_facade_emitter.py --plan data/w8-hooks-split-plan.json
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import UTC, datetime
from pathlib import Path

LOGGER = logging.getLogger(__name__)
_ROOT = Path(__file__).resolve().parents[2]
_DATA_DIR = _ROOT / "scripts" / "touring_premium_refactor_2026" / "data"
_STAGING_DIR = _ROOT / "scripts" / "touring_premium_refactor_2026" / "staging"


def build_parser() -> argparse.ArgumentParser:
    """CLI parser."""
    p = argparse.ArgumentParser(
        prog="w8_hooks_facade_emitter", description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--plan", type=Path,
                   default=_DATA_DIR / "w8-hooks-split-plan.json")
    p.add_argument("--output-dir", type=Path, default=_DATA_DIR)
    p.add_argument("-v", "--verbose", action="store_true")
    return p


def emit_facade_lib(buckets: list[str]) -> str:
    """Generate lib.rs façade content."""
    sub_crates = [b for b in buckets
                   if b.startswith("touring-hooks-")
                   and b not in ("touring-hooks-facade", "touring-hooks-misc")]
    lines = [
        '//! `touring-hooks` — Façade re-exports for the 8 split sub-crates.',
        '//!',
        '//! Auto-generated by w8_hooks_facade_emitter.py (W8.6).',
        '//! DO NOT add direct code here — extend the relevant sub-crate instead.',
        "",
        "#![forbid(unsafe_code)]",
        "#![deny(missing_docs)]",
        "",
    ]
    for sub in sub_crates:
        mod = sub.replace("touring-hooks-", "")
        lines.append(f"pub use {sub.replace('-', '_')} as {mod};")
    lines.extend([
        "",
        "/// Crate version (semver-compatible with workspace).",
        'pub const VERSION: &str = env!("CARGO_PKG_VERSION");',
        "",
    ])
    return "\n".join(lines)


def emit_facade_cargo(buckets: list[str]) -> str:
    """Generate Cargo.toml [dependencies] section update."""
    sub_crates = sorted(b for b in buckets
                         if b.startswith("touring-hooks-")
                         and b not in ("touring-hooks-facade",
                                        "touring-hooks-misc"))
    deps_lines = [f'{sub} = {{ workspace = true }}' for sub in sub_crates]
    return "\n".join([
        "# AUTO-GENERATED — W8.6 façade [dependencies] section",
        f"# Generated: {datetime.now(UTC).isoformat()}",
        "# Replace existing [dependencies] in crates/touring-hooks/Cargo.toml",
        "",
        "[dependencies]",
        *deps_lines,
        "",
    ])


def run(args: argparse.Namespace) -> dict:
    """Load plan + emit façade."""
    args.output_dir.mkdir(parents=True, exist_ok=True)
    _STAGING_DIR.mkdir(parents=True, exist_ok=True)
    if not args.plan.exists():
        return {"status": "PLAN_MISSING",
                "hint": "Run w8_hooks_split_planner.py first"}
    plan = json.loads(args.plan.read_text(encoding="utf-8"))
    buckets = list(plan.get("buckets", {}).keys())
    lib_rs = _STAGING_DIR / "w8-touring-hooks-facade-lib.rs"
    lib_rs.write_text(emit_facade_lib(buckets), encoding="utf-8")
    cargo_toml = _STAGING_DIR / "w8-touring-hooks-Cargo.toml"
    cargo_toml.write_text(emit_facade_cargo(buckets), encoding="utf-8")
    manifest = {
        "script": "w8_hooks_facade_emitter",
        "wave": "W8", "subtask_refs": ["W8.6"],
        "timestamp": datetime.now(UTC).isoformat(),
        "status": "OK",
        "buckets_in_plan": buckets,
        "sub_crates_reexported": [b for b in buckets
                                     if b.startswith("touring-hooks-")
                                     and b != "touring-hooks-facade"],
        "lib_rs_path": str(lib_rs.relative_to(_ROOT)),
        "cargo_toml_path": str(cargo_toml.relative_to(_ROOT)),
    }
    json_path = args.output_dir / "w8-facade-manifest.json"
    json_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False),
                          encoding="utf-8")
    manifest["json_path"] = str(json_path.relative_to(_ROOT))
    return manifest


def main() -> int:
    """Entry point."""
    args = build_parser().parse_args()
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
    )
    try:
        result = run(args)
        sys.stdout.write(json.dumps(result, indent=2, ensure_ascii=False) + "\n")
        return 0 if result.get("status") == "OK" else 1
    except KeyboardInterrupt:
        LOGGER.warning("interrupted")
        return 130
    except Exception:  # noqa: BLE001
        LOGGER.exception("error")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
