#!/usr/bin/env bash
# audit-plan-completion.sh
# Generated by taco-forge plan --quality high (plan_quality v1.15.0)
# Cross-audit final gate (REGRA #15)
#
# Plan: Loop Engineering MVP para o Touring: um orquestrador de loop agentic hibrido-autonomo. Construir (fatia-fina): (1) skill loop-engineering (SKILL.md, o cerebro de orquestracao: protocolo do loop, gate de convergencia mensuravel, pontos de human-gate, referencias aos scripts e a um AGENTS.md de manutencao do bundle estilo OpenKB); (2) scripts/loop_diagnose.py (diagnostico one-shot compondo touring map+scout+blast+touring-quality --workspace+wiring chains+memory recall num digest JSON+OKF); (3) scripts/loop_converged.py (gate de convergencia mensuravel: decompose-ready-vazio E touring-quality>=0.80 E 0 dims P0 Fail E orphans<=baseline E cargo check/test/clippy verde E cross-audit limpo; exit0=convergiu exit1=continua+unmet[]+next_action); (4) scripts/loop_phase_close.py (phase-close: memory store + learning reward + decompose update/finalize + append plan.md + relatorio de fase OKF-compliant + Knowledge Abstract tipado estilo Hyper-Extract com entity_id/relation_id deterministicos + wikilinks); (5) scripts/loop_doc_link_gate.py (validador OKF: schema frontmatter + resolucao de links bundle-relative + lint de contradicoes estilo OpenKB); (6) dois hooks em settings.json: Stop loop-stop-guard (nao-convergiu injeta continue+proxima-subtask-ready) e PreCompact loop-snapshot (snapshot do loop-state que sobrevive compactacao, analogo checkpointer LangGraph); (7) convencao de bundle .md OKF-compliant (index.md+log.md+frontmatter+cross-links bundle-relative) como ledger duravel resumivel. Doc-layer: adotar OKF integralmente; adotar padroes Hyper-Extract+OpenKB nativamente (sem deps Python externas no MVP; ferramentas reais deferidas). Reusar primitivas Touring existentes (master commands, decompose DAG, touring-quality); zero CLI nova.
# Task ID: task_1782996878252842489
# Generated: 2026-07-02T12:54:40.001029Z
#
# DO NOT HAND-EDIT — regenerate via plan_quality.cli generate.

set -euo pipefail

TASK_ID="task_1782996878252842489"
PHASE_IDS="P0"
VGP_SYMBOLS=""
PLAN_DIR="$(cd "$(dirname "$0")" && pwd)"
REPORT="$PLAN_DIR/.audit-report.toon"
WORKSPACE_ROOT="${HOME}/.claude/rust"

log()   { printf "[audit] %s\n" "$*" >&2; }
fail()  { log "FATAL: $*"; PASS=0; FAIL_REASONS+=("$*"); }
ok()    { log "OK: $*"; CHECKS_PASSED+=("$*"); }

PASS=1
FAIL_REASONS=()
CHECKS_PASSED=()
START_TS=$(date +%s)

# ─── Gate 1: daemon health ──────────────────────────────────────────────────
log "Gate 1/9: daemon health"
if ! touring doctor -j 2>/dev/null | jq -e '[.[] | .status] | all(.=="ok")' >/dev/null; then
  fail "touring doctor not OK"
else
  ok "daemon healthy"
fi

# ─── Gate 2: all phases finalized ──────────────────────────────────────────
log "Gate 2/9: phases finalized"
DAG_STATE=$(touring decompose get "$TASK_ID" 2>/dev/null || echo '{}')
TOTAL=$(echo "$DAG_STATE" | jq -r '.subtasks | length // 0')
COMPLETED=$(echo "$DAG_STATE" | jq -r '[.subtasks[]? | select(.status=="completed")] | length')
log "  $COMPLETED/$TOTAL subtasks completed"
if [[ "$TOTAL" -gt 0 && "$COMPLETED" -eq "$TOTAL" ]]; then
  ok "all $TOTAL subtasks completed"
else
  fail "DAG incomplete: $COMPLETED/$TOTAL"
fi

# ─── Gate 3: VGP symbols still verified ────────────────────────────────────
log "Gate 3/9: VGP re-verify"
if [[ -n "$VGP_SYMBOLS" ]]; then
  IFS=',' read -ra _SYMS <<< "$VGP_SYMBOLS"
  VGP_FAILS=0
  for sym in "${_SYMS[@]}"; do
    if ! touring generate verify --symbol "$sym" >/dev/null 2>&1; then
      log "  VGP FAIL: $sym"
      VGP_FAILS=$((VGP_FAILS + 1))
    fi
  done
  if [[ "$VGP_FAILS" -eq 0 ]]; then
    ok "all ${#_SYMS[@]} VGP symbols still verified"
  else
    fail "$VGP_FAILS VGP symbols regressed"
  fi
else
  ok "no VGP symbols declared (skip)"
fi

# ─── Gate 4: wiring orphans delta ──────────────────────────────────────────
log "Gate 4/9: wiring orphans delta"
BASELINE_FILE="$PLAN_DIR/.baseline/discover-baseline.toon"
CURRENT_ORPHANS=$(touring wiring orphans -j 2>/dev/null | jq -r '.orphan_count // 0')
if [[ -e "$BASELINE_FILE" ]]; then
  BASELINE_ORPHANS=$(grep '^orphan_count:' "$BASELINE_FILE" 2>/dev/null | awk '{print $2}' || echo 0)
else
  BASELINE_ORPHANS=$CURRENT_ORPHANS
fi
DELTA=$((CURRENT_ORPHANS - BASELINE_ORPHANS))
log "  baseline=$BASELINE_ORPHANS current=$CURRENT_ORPHANS delta=$DELTA"
if [[ "$DELTA" -le 0 ]]; then
  ok "orphan delta $DELTA ≤ 0 (REGRA #0 satisfied)"
else
  fail "orphan delta $DELTA > 0 (new unwired pub symbols)"
fi

# ─── Gate 5: cargo check ────────────────────────────────────────────────────
log "Gate 5/9: cargo check --workspace"
cd "$WORKSPACE_ROOT" 2>/dev/null || { fail "workspace not found"; cd "$PLAN_DIR"; }
if cargo check --workspace 2>&1 | tail -3 | grep -q "^error"; then
  fail "cargo check has errors"
else
  ok "cargo check clean"
fi
cd "$PLAN_DIR"

# ─── Gate 6: cargo test ─────────────────────────────────────────────────────
log "Gate 6/9: cargo test --workspace (smoke)"
cd "$WORKSPACE_ROOT" 2>/dev/null || cd "$PLAN_DIR"
if [[ -f Cargo.toml ]]; then
  if cargo test --workspace --no-run 2>&1 | tail -5 | grep -q "error\["; then
    fail "cargo test build has errors"
  else
    ok "cargo test build clean"
  fi
else
  ok "no Cargo.toml — skip cargo test"
fi
cd "$PLAN_DIR"

# ─── Gate 7: e2e standard ───────────────────────────────────────────────────
log "Gate 7/9: e2e standard"
E2E_OUT=$(touring e2e --depth standard -j 2>/dev/null || echo '{}')
E2E_SCORE=$(echo "$E2E_OUT" | jq -r '.composite_score // 0')
log "  e2e composite=$E2E_SCORE"
if (( $(echo "$E2E_SCORE >= 0.7" | bc -l) )); then
  ok "e2e $E2E_SCORE ≥ 0.7"
else
  fail "e2e $E2E_SCORE < 0.7"
fi

# ─── Gate 8: per-phase validators all PASS ─────────────────────────────────
log "Gate 8/9: per-phase validators"
PHASE_FAILS=0
if [[ -n "$PHASE_IDS" ]]; then
  IFS=',' read -ra _PIDS <<< "$PHASE_IDS"
  for pid in "${_PIDS[@]}"; do
    script="$PLAN_DIR/validators/validate-phase-$pid.sh"
    if [[ ! -x "$script" ]]; then
      log "  MISSING: $script"
      PHASE_FAILS=$((PHASE_FAILS + 1))
      continue
    fi
    if bash "$script" >/dev/null 2>&1; then
      log "  ✓ phase $pid"
    else
      log "  ✗ phase $pid"
      PHASE_FAILS=$((PHASE_FAILS + 1))
    fi
  done
  if [[ "$PHASE_FAILS" -eq 0 ]]; then
    ok "all ${#_PIDS[@]} phase validators passed"
  else
    fail "$PHASE_FAILS phase validators failed"
  fi
else
  ok "no phases declared (skip)"
fi

# ─── Gate 9: persist outcome + RL reward ───────────────────────────────────
log "Gate 9/9: persist + reward"
END_TS=$(date +%s)
DURATION=$((END_TS - START_TS))

# Emit TOON report
{
  echo "task_id: $TASK_ID"
  echo "audit_timestamp: $(date -Iseconds)"
  echo "duration_seconds: $DURATION"
  if [[ "$PASS" -eq 1 ]]; then
    echo "status: PASS"
  else
    echo "status: FAIL"
  fi
  echo "checks_passed[${#CHECKS_PASSED[@]}]:"
  for c in "${CHECKS_PASSED[@]}"; do
    echo "  - \"$c\""
  done
  if [[ "${#FAIL_REASONS[@]}" -gt 0 ]]; then
    echo "fail_reasons[${#FAIL_REASONS[@]}]:"
    for r in "${FAIL_REASONS[@]}"; do
      echo "  - \"$r\""
    done
  fi
  echo "e2e_composite: $E2E_SCORE"
  echo "orphan_delta: $DELTA"
} > "$REPORT"

log "  audit report: $REPORT"

if [[ "$PASS" -eq 1 ]]; then
  touring memory store "plan:${TASK_ID}:audit:final" "PASS" --tier semantic 2>/dev/null || true
  touring learning reward orchestrate 1.0 "plan_audit_full_pass:$TASK_ID" 2>/dev/null || true
  touring diary write touring-auditor "Plan $TASK_ID cross-audit PASS — 9/9 gates" \
    --aaak --task "$TASK_ID" 2>/dev/null || true
  log "✓ CROSS-AUDIT PASSED (9/9 gates)"
  exit 0
else
  touring memory store "plan:${TASK_ID}:audit:final" "FAIL" --tier semantic 2>/dev/null || true
  touring learning reward orchestrate -0.5 "plan_audit_failed:$TASK_ID" 2>/dev/null || true
  log "✗ CROSS-AUDIT FAILED — see $REPORT"
  exit 99
fi
