//! `cli_repo_health` — Wave R3: auto-generated executive Markdown report.
//!
//! Combines `cli_repo_score` (Wave R1) and `cli_kpi` (Wave R2) into a
//! human-readable Markdown document so Gabriel can consume the workspace
//! health snapshot without parsing JSON.
//!
//! # Output format
//!
//! ```markdown
//! # Repository Health — 2026-04-25
//!
//! **Score**: 150/269 (55.8%) — Grade **F**
//!
//! ## Top-Line Commitments
//! - Wiring orphan symbols: 9106 ❌ (threshold: <= 100)
//! - RL EMA reward: 0.18 ❌ (threshold: >= 0.2)
//! ...
//!
//! ## Categories
//! ### architecture — 0/30 (wiring)
//! - orphan_count: 9106
//! ...
//!
//! ## Diagnostics
//! - **Q-200** [warning]: category `architecture` scored 0/30
//! ...
//! ```
//!
//! # CLI flags (handled by `touring-server::cli::repo_health`)
//!
//! - `--output <path>`: write to a file (default: `docs/repo-health.md`)
//! - `--stdout`: print to stdout instead of writing a file

use crate::runtime::HookRuntime;
use serde_json::Value;
use std::path::PathBuf;

// ─────────────────────────────────────────────────────────────────────────────
// Public handler
// ─────────────────────────────────────────────────────────────────────────────

/// `cli-repo-health` handler — produces the Markdown executive snapshot.
///
/// Payload optional fields:
/// - `"output_path": "/abs/path"` → write Markdown to this file
/// - `"stdout": true` → return Markdown in JSON `markdown` key (no file write)
pub fn cli_repo_health(rt: &mut HookRuntime, payload: &Value) -> String {
    let output_path = payload.get("output_path").and_then(Value::as_str);
    let stdout_only = payload
        .get("stdout")
        .and_then(Value::as_bool)
        .unwrap_or(false);

    // Collect both upstream snapshots.
    let score_raw = super::repo_score::cli_repo_score(rt, &Value::Null);
    let kpi_raw = super::kpi::cli_kpi(rt, &Value::Null);

    let score_json: Value = serde_json::from_str(&score_raw).unwrap_or(Value::Null);
    let kpi_json: Value = serde_json::from_str(&kpi_raw).unwrap_or(Value::Null);

    let markdown = render_markdown(&score_json, &kpi_json);

    if stdout_only {
        return serde_json::json!({
            "markdown": markdown,
            "bytes": markdown.len(),
        })
        .to_string();
    }

    let target = output_path
        .map(PathBuf::from)
        .unwrap_or_else(default_output_path);

    match write_atomic(&target, &markdown) {
        Ok(()) => serde_json::json!({
            "written": true,
            "output_path": target.display().to_string(),
            "bytes": markdown.len(),
        })
        .to_string(),
        Err(e) => serde_json::json!({
            "written": false,
            "error": e.to_string(),
            "output_path": target.display().to_string(),
        })
        .to_string(),
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Markdown renderer (zero external deps — no Tera/Handlebars)
// ─────────────────────────────────────────────────────────────────────────────

/// Build the full Markdown document from the two upstream JSON payloads.
///
/// Public so consumers can render to a string without going through the daemon.
#[must_use]
pub fn render_markdown(score: &Value, kpi: &Value) -> String {
    let mut out = String::with_capacity(4096);

    let date = kpi
        .get("snapshot_date")
        .and_then(Value::as_str)
        .unwrap_or("unknown");
    let total = score
        .get("total_score")
        .and_then(Value::as_u64)
        .unwrap_or(0);
    let max = score.get("max_score").and_then(Value::as_u64).unwrap_or(0);
    let pct = score
        .get("percentage")
        .and_then(Value::as_f64)
        .unwrap_or(0.0);
    let grade = score.get("grade").and_then(Value::as_str).unwrap_or("?");

    use std::fmt::Write;
    let _ = writeln!(out, "# Repository Health — {date}");
    out.push('\n');
    let _ = writeln!(
        out,
        "**Score**: {total}/{max} ({pct:.1}%) — Grade **{grade}**"
    );
    out.push('\n');

    out.push_str("## Top-Line Commitments\n\n");
    render_kpi_section(&mut out, kpi);
    out.push('\n');

    out.push_str("## Categories\n\n");
    render_categories_section(&mut out, score);
    out.push('\n');

    out.push_str("## Diagnostics\n\n");
    render_diagnostics_section(&mut out, score, kpi);
    out.push('\n');

    out.push_str("## Trend (30 days)\n\n");
    out.push_str("```\n");
    out.push_str("Trend data not available yet — first snapshot is the baseline.\n");
    out.push_str("Run `touring kpi --snapshot` daily to start collecting series.\n");
    out.push_str("```\n\n");

    out.push_str("---\n");
    out.push_str(
        "*Auto-generated by `touring repo-health` (Wave R3, RFC-100 + RFC-R1 + RFC-R2).*\n",
    );

    out
}

fn render_kpi_section(out: &mut String, kpi: &Value) {
    let checks = match kpi.get("checks").and_then(Value::as_array) {
        Some(arr) => arr,
        None => {
            out.push_str("_No KPI data available._\n");
            return;
        }
    };
    if checks.is_empty() {
        out.push_str("_No commitments configured._\n");
        return;
    }
    for c in checks {
        let name = c.get("name").and_then(Value::as_str).unwrap_or("?");
        let actual = c.get("actual").map_or("null".to_string(), |v| {
            v.as_f64().map_or_else(|| v.to_string(), format_actual)
        });
        let threshold = c.get("threshold").and_then(Value::as_f64).unwrap_or(0.0);
        let direction = c.get("direction").and_then(Value::as_str).unwrap_or("?");
        let status = c.get("status").and_then(Value::as_str).unwrap_or("?");
        let emoji = status_emoji(status);
        let dir_word = match direction {
            "gte" => ">=",
            "lte" => "<=",
            "eq" => "==",
            _ => "?",
        };
        use std::fmt::Write;
        let _ = writeln!(
            out,
            "- **{name}**: `{actual}` {emoji} (threshold: `{dir_word} {threshold}`)"
        );
    }
}

fn render_categories_section(out: &mut String, score: &Value) {
    let categories = match score.get("categories").and_then(Value::as_object) {
        Some(obj) => obj,
        None => {
            out.push_str("_No category data._\n");
            return;
        }
    };
    use std::fmt::Write;
    for (name, cat) in categories {
        let s = cat.get("score").and_then(Value::as_u64).unwrap_or(0);
        let m = cat.get("max").and_then(Value::as_u64).unwrap_or(0);
        let source = cat.get("source").and_then(Value::as_str).unwrap_or("?");
        let _ = writeln!(out, "### {name} — {s}/{m} _(source: {source})_");
        if let Some(details) = cat.get("details").and_then(Value::as_object) {
            for (k, v) in details {
                let _ = writeln!(out, "- `{k}`: `{}`", strip_quotes(&v.to_string()));
            }
        }
        out.push('\n');
    }
}

fn render_diagnostics_section(out: &mut String, score: &Value, kpi: &Value) {
    let mut all = Vec::new();
    if let Some(arr) = score.get("diagnostics").and_then(Value::as_array) {
        all.extend(arr.iter());
    }
    if let Some(arr) = kpi.get("diagnostics").and_then(Value::as_array) {
        all.extend(arr.iter());
    }
    if all.is_empty() {
        out.push_str("_No diagnostics emitted — all categories above the warning threshold._\n");
        return;
    }
    use std::fmt::Write;
    for d in all {
        let code = d.get("code").and_then(Value::as_str).unwrap_or("?");
        let sev = d.get("severity").and_then(Value::as_str).unwrap_or("?");
        let msg = d.get("message").and_then(Value::as_str).unwrap_or("?");
        let _ = writeln!(out, "- **{code}** [{sev}]: {msg}");
    }
}

fn status_emoji(status: &str) -> &'static str {
    match status {
        "PASS" => "✅",
        "FAIL" => "❌",
        "STUB" => "⚠",
        _ => "❓",
    }
}

fn format_actual(v: f64) -> String {
    if v.fract() == 0.0 && v.abs() < 1e15 {
        format!("{v:.0}")
    } else {
        format!("{v:.3}")
    }
}

fn strip_quotes(s: &str) -> String {
    s.trim_matches('"').to_string()
}

// ─────────────────────────────────────────────────────────────────────────────
// Output path resolution
// ─────────────────────────────────────────────────────────────────────────────

fn default_output_path() -> PathBuf {
    if let Ok(home) = std::env::var("HOME") {
        PathBuf::from(home).join(".claude/rust/docs/repo-health.md")
    } else {
        PathBuf::from("docs/repo-health.md")
    }
}

fn write_atomic(target: &PathBuf, contents: &str) -> std::io::Result<()> {
    if let Some(parent) = target.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let tmp = target.with_extension("md.tmp");
    std::fs::write(&tmp, contents)?;
    std::fs::rename(&tmp, target)?;
    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn sample_score() -> Value {
        json!({
            "total_score": 150,
            "max_score": 269,
            "percentage": 55.8,
            "grade": "F",
            "categories": {
                "architecture": {
                    "score": 0,
                    "max": 30,
                    "source": "wiring",
                    "details": {"orphan_count": 9106, "total_pub_symbols": 5777}
                }
            },
            "diagnostics": [
                {"code": "Q-200", "severity": "warning", "message": "category `architecture` scored 0/30"}
            ]
        })
    }

    fn sample_kpi() -> Value {
        json!({
            "schema": "kpi-commitments-v1",
            "snapshot_date": "2026-04-25",
            "checks": [
                {
                    "id": "touring.wiring.orphans",
                    "name": "Wiring orphan symbols",
                    "threshold": 100.0,
                    "direction": "lte",
                    "actual": 9106.0,
                    "status": "FAIL"
                }
            ],
            "summary": {"total": 1, "passed": 0, "failed": 1, "stub": 0, "regressions": 0}
        })
    }

    #[test]
    fn render_includes_header_with_grade() {
        let md = render_markdown(&sample_score(), &sample_kpi());
        assert!(md.contains("# Repository Health — 2026-04-25"));
        assert!(md.contains("Grade **F**"));
        assert!(md.contains("150/269 (55.8%)"));
    }

    #[test]
    fn render_includes_kpi_section() {
        let md = render_markdown(&sample_score(), &sample_kpi());
        assert!(md.contains("## Top-Line Commitments"));
        assert!(md.contains("Wiring orphan symbols"));
        assert!(md.contains("9106"));
        assert!(md.contains("❌"), "FAIL must render with red-x emoji");
    }

    #[test]
    fn render_includes_categories_section() {
        let md = render_markdown(&sample_score(), &sample_kpi());
        assert!(md.contains("## Categories"));
        assert!(md.contains("### architecture — 0/30"));
        assert!(md.contains("orphan_count"));
    }

    #[test]
    fn render_includes_diagnostics_section() {
        let md = render_markdown(&sample_score(), &sample_kpi());
        assert!(md.contains("## Diagnostics"));
        assert!(md.contains("**Q-200**"));
    }

    #[test]
    fn render_handles_empty_diagnostics_gracefully() {
        let mut score = sample_score();
        score["diagnostics"] = json!([]);
        let mut kpi = sample_kpi();
        kpi["diagnostics"] = json!([]);
        let md = render_markdown(&score, &kpi);
        assert!(md.contains("_No diagnostics emitted"));
    }

    #[test]
    fn render_handles_missing_categories_gracefully() {
        let score = json!({"total_score": 0, "max_score": 100, "percentage": 0.0, "grade": "F"});
        let kpi = sample_kpi();
        let md = render_markdown(&score, &kpi);
        assert!(md.contains("_No category data._"));
    }

    #[test]
    fn status_emoji_maps_correctly() {
        assert_eq!(status_emoji("PASS"), "✅");
        assert_eq!(status_emoji("FAIL"), "❌");
        assert_eq!(status_emoji("STUB"), "⚠");
        assert_eq!(status_emoji("anything_else"), "❓");
    }

    #[test]
    fn format_actual_drops_trailing_zeros_for_integers() {
        assert_eq!(format_actual(42.0), "42");
        assert_eq!(format_actual(9106.0), "9106");
    }

    #[test]
    fn format_actual_keeps_decimals_for_floats() {
        assert_eq!(format_actual(0.179), "0.179");
        assert_eq!(format_actual(3.14), "3.140");
    }

    #[test]
    fn render_includes_trend_placeholder() {
        let md = render_markdown(&sample_score(), &sample_kpi());
        assert!(md.contains("## Trend (30 days)"));
        assert!(md.contains("Trend data not available yet"));
    }

    #[test]
    fn render_ends_with_attribution_footer() {
        let md = render_markdown(&sample_score(), &sample_kpi());
        assert!(md.contains("Auto-generated by `touring repo-health`"));
    }

    #[test]
    fn write_atomic_creates_parent_dirs() {
        let tmp = std::env::temp_dir()
            .join(format!("touring-r3-test-{}", std::process::id()))
            .join("nested")
            .join("repo-health.md");
        let _ = std::fs::remove_file(&tmp);
        let _ = std::fs::remove_dir_all(tmp.parent().unwrap());
        write_atomic(&tmp, "# Hello\n").expect("write should succeed");
        let read_back = std::fs::read_to_string(&tmp).expect("read");
        assert_eq!(read_back, "# Hello\n");
        let _ = std::fs::remove_dir_all(tmp.parent().unwrap().parent().unwrap());
    }
}
