#!/usr/bin/env bash
# validate-phase-W1.sh
# Generated by taco-forge plan --quality high (plan_quality v1.14.0)
# Phase: W1 — quick win 7 Cargo.toml edits
# Task ID: task_1777851082497360181
# Contribution: quick win 7 Cargo.toml edits
# DO NOT HAND-EDIT — regenerate via plan_quality.cli generate.

set -euo pipefail

PHASE_ID="W1"
TASK_ID="task_1777851082497360181"
PLAN_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CHECKPOINT_DIR="$PLAN_DIR/checkpoints"
BASELINE_DIR="$PLAN_DIR/.baseline"
mkdir -p "$CHECKPOINT_DIR" "$BASELINE_DIR"

log()  { printf "[validate-phase-%s] %s\n" "$PHASE_ID" "$*" >&2; }
fail() { log "FATAL: $*"; exit "${2:-1}"; }
step() { printf "\n=== %s ===\n" "$*" >&2; }

step "setup"
WORKSPACE_ROOT="${HOME}/.claude/rust"
cd "$WORKSPACE_ROOT" || fail "workspace not found: $WORKSPACE_ROOT" 2
log "workspace=$WORKSPACE_ROOT"

# Ensure daemon is up
if ! touring doctor -j 2>/dev/null | jq -e "[.[] | .status] | all(.==\"ok\")" >/dev/null; then
  fail "touring doctor not OK — run update-touring" 3
fi
log "daemon healthy"

step "baseline capture"
BASELINE_FILE="$BASELINE_DIR/phase-${PHASE_ID}-baseline.json"
if [[ ! -e "$BASELINE_FILE" ]]; then
  log "capturing baseline (first run)"
  {
    echo "{\"orphans\":"
    touring wiring orphans -j 2>/dev/null || echo "{}"
    echo ",\"gate_metrics\":"
    touring gate-metrics -j 2>/dev/null || echo "{}"
    echo "}"
  } > "$BASELINE_FILE"
fi
log "baseline=$BASELINE_FILE"

step "cargo check"
cargo check --workspace || fail "cargo check failed" 10

step "cargo test"
cargo test || fail "cargo test failed" 11

step "wiring orphans delta"
BASELINE_ORPHANS=$(jq -r ".orphans.orphan_count // 0" "$BASELINE_FILE")
CURRENT_ORPHANS=$(touring wiring orphans -j 2>/dev/null | jq -r ".orphan_count // 0")
DELTA=$((CURRENT_ORPHANS - BASELINE_ORPHANS))
log "  baseline=$BASELINE_ORPHANS current=$CURRENT_ORPHANS delta=$DELTA"
if [[ "$DELTA" -gt 0 ]]; then
  fail "orphan delta $DELTA > 0 (REGRA #0 — wire new pub symbols)" 13
fi

step "gate-metrics capture"
METRICS_FILE="$CHECKPOINT_DIR/phase-${PHASE_ID}-gate-metrics.json"
touring gate-metrics -j > "$METRICS_FILE" 2>/dev/null || log "WARN: gate-metrics failed"
log "  saved: $METRICS_FILE"

step "E2E health gate"
E2E_OUT=$(touring e2e --depth standard -j 2>/dev/null || echo '{}')
E2E_SCORE=$(echo "$E2E_OUT" | jq -r ".composite_score // 0")
log "  e2e composite=$E2E_SCORE (min=0.7)"
if (( $(echo "$E2E_SCORE < 0.7" | bc -l) )); then
  fail "e2e composite $E2E_SCORE < 0.7" 14
fi

step "TDD REFACTOR gate (clippy + tdg)"
cargo clippy --workspace -- -D warnings || fail "clippy warnings (REFACTOR fail)" 15
log "  clippy clean"

step "persist outcome + RL reward"
OUTCOME_FILE="$CHECKPOINT_DIR/phase-${PHASE_ID}-outcome.toon"
{
  echo "phase_id: $PHASE_ID"
  echo "task_id: $TASK_ID"
  echo "title: quick win 7 Cargo.toml edits"
  echo "timestamp: $(date -Iseconds)"
  echo "status: completed"
  echo "orphan_delta: $DELTA"
  echo "e2e_score: $E2E_SCORE"
} > "$OUTCOME_FILE"
log "  outcome saved: $OUTCOME_FILE"

touring memory store "plan:${TASK_ID}:phase:${PHASE_ID}:outcome" "$(cat \"$OUTCOME_FILE\")" --tier semantic 2>/dev/null || true
touring learning reward orchestrate 1.0 "phase_${PHASE_ID}_validated" 2>/dev/null || true

log "PHASE $PHASE_ID VALIDATED ✓"
exit 0
