//! Generator specification output from N3 meta-generation.
//!
//! Describes a specialized N1 generator that can handle a specific domain.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Specification for a specialized N1 generator.
///
/// Generated by N3 MetaGenerator from a DomainSpec.
/// Describes the generator's configuration, pheromone keys, and sequence patterns.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratorSpec {
    /// Unique identifier for this generator.
    pub id: GeneratorId,
    /// Domain this generator handles.
    pub domain_id: super::DomainId,
    /// Human-readable description.
    pub description: String,
    /// Configuration for the generator.
    pub config: GeneratorConfig,
    /// Sequence patterns this generator knows.
    pub patterns: Vec<SequencePattern>,
    /// Pheromone key prefix for ACO integration.
    pub pheromone_prefix: String,
    /// Quality gates this generator enforces.
    pub quality_gates: Vec<super::QualityGate>,
}

/// Configuration for a generator.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratorConfig {
    /// Maximum tool calls per sequence.
    pub max_tool_calls: usize,
    /// Evaporation rate for pheromone trails.
    pub evaporation_rate: f64,
    /// Minimum confidence threshold.
    pub min_confidence: f64,
    /// Whether to use parallel execution.
    pub allow_parallel: bool,
    /// Custom parameters.
    pub custom: HashMap<String, serde_json::Value>,
}

impl Default for GeneratorConfig {
    fn default() -> Self {
        Self {
            max_tool_calls: 10,
            evaporation_rate: 0.1,
            min_confidence: 0.5,
            allow_parallel: true,
            custom: HashMap::new(),
        }
    }
}

impl GeneratorConfig {
    /// Create a default config.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set max tool calls.
    pub fn with_max_tool_calls(mut self, max: usize) -> Self {
        self.max_tool_calls = max;
        self
    }

    /// Set evaporation rate.
    pub fn with_evaporation_rate(mut self, rate: f64) -> Self {
        self.evaporation_rate = rate;
        self
    }

    /// Set min confidence.
    pub fn with_min_confidence(mut self, confidence: f64) -> Self {
        self.min_confidence = confidence;
        self
    }
}

/// A sequence pattern the generator knows.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SequencePattern {
    /// Name of the pattern.
    pub name: String,
    /// Description of when to use this pattern.
    pub trigger: String,
    /// Tool calls in this pattern.
    pub tool_sequence: Vec<ToolCallSpec>,
    /// Pheromone strength (0.0-1.0).
    pub pheromone_strength: f64,
}

/// A tool call within a sequence pattern.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallSpec {
    /// Tool name.
    pub tool_name: String,
    /// Whether this call typically has dependencies.
    pub has_dependency: bool,
    /// Whether this call is typically parallelizable.
    pub parallelizable: bool,
    /// Expected output type.
    pub expected_output: Option<String>,
}

impl SequencePattern {
    /// Create a new sequence pattern.
    pub fn new(name: impl Into<String>, trigger: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            trigger: trigger.into(),
            tool_sequence: Vec::new(),
            pheromone_strength: 1.0,
        }
    }

    /// Add a tool call to the pattern.
    pub fn with_tool(mut self, tool: ToolCallSpec) -> Self {
        self.tool_sequence.push(tool);
        self
    }

    /// Set pheromone strength.
    pub fn with_strength(mut self, strength: f64) -> Self {
        self.pheromone_strength = strength;
        self
    }
}

/// Unique identifier for a generator.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct GeneratorId(pub &'static str);

// Predefined generator IDs as free constants
/// Generator id for the basic general-purpose generator.
pub const GENERATOR_ID_BASIC: GeneratorId = GeneratorId("basic_gen");
/// Generator id for the Rust analyzer-driven generator.
pub const GENERATOR_ID_RUST_ANALYZER: GeneratorId = GeneratorId("rust_analyzer_gen");
/// Generator id for the web (TypeScript/JavaScript) generator.
pub const GENERATOR_ID_WEB_GENERATOR: GeneratorId = GeneratorId("web_gen");
/// Generator id for the data-pipeline generator.
pub const GENERATOR_ID_DATA_PIPELINE: GeneratorId = GeneratorId("data_pipeline_gen");

// Manually implement Serialize (trivially works for &'static str)
impl Serialize for GeneratorId {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.0)
    }
}

// Custom Deserialize that leaks the String to get &'static str
struct GeneratorIdVisitor;
impl<'de> serde::de::Visitor<'de> for GeneratorIdVisitor {
    type Value = GeneratorId;
    fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
        formatter.write_str("a string")
    }
    fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        let leaked: &'static str = Box::leak(v.to_string().into_boxed_str());
        Ok(GeneratorId(leaked))
    }
}
impl<'de> Deserialize<'de> for GeneratorId {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        deserializer.deserialize_str(GeneratorIdVisitor)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generator_config_defaults() {
        let config = GeneratorConfig::default();
        assert_eq!(config.max_tool_calls, 10);
        assert_eq!(config.evaporation_rate, 0.1);
        assert_eq!(config.min_confidence, 0.5);
    }

    #[test]
    fn test_sequence_pattern_builder() {
        let pattern = SequencePattern::new("read_edit", "file modification")
            .with_tool(ToolCallSpec {
                tool_name: "Read".into(),
                has_dependency: false,
                parallelizable: true,
                expected_output: Some("file content".into()),
            })
            .with_tool(ToolCallSpec {
                tool_name: "Edit".into(),
                has_dependency: true,
                parallelizable: false,
                expected_output: Some("edit result".into()),
            })
            .with_strength(0.9);

        assert_eq!(pattern.name, "read_edit");
        assert_eq!(pattern.tool_sequence.len(), 2);
        assert_eq!(pattern.pheromone_strength, 0.9);
    }
}
