#!/usr/bin/env python3
"""changelog_synth.py - merge-aware Keep-a-Changelog synthesizer for TOON checkpoints.

Master Plan D.W3.P1.T7. Synthesizes dated changelog entries from the
docs/checkpoints/*.toon checkpoint files and MERGES them into CHANGELOG.md
WITHOUT destroying the hand-curated history below the marker block.

The generated content is wrapped in idempotency markers:

    <!-- BEGIN toon-synth (auto-generated by docs/changelog_synth.py - do not edit by hand) -->
    ... auto-generated dated checkpoint groups ...
    <!-- END toon-synth -->

The block is inserted AFTER the preamble (the "All notable changes..." line) and
BEFORE the first hand-curated section header (## [...]). On re-run the content
between the markers is REPLACED in place - never duplicated, and nothing outside
the markers is touched. The hand-curated history stays byte-identical.

TOON files come in two on-disk variants, both handled:
  * YAML-style:  `format: toon` ... `topic: <slug>` ... `timestamp: "<ISO>"` ...
                 `content:\n  sections[N]: a,b,c`
  * JSON-style:  `{ "format": "TOON", "topic": ..., "timestamp": ..., ... }`

Date resolution order (robust against missing/empty timestamps):
  1. `timestamp` field (first YYYY-MM-DD found)
  2. filename date prefix (YYYY-MM-DD-...)
  3. file modification time

Usage:
    docs/changelog_synth.py            merge the synth block into CHANGELOG.md in place
    docs/changelog_synth.py --check    exit 1 if CHANGELOG.md WOULD change (CI drift gate)
    docs/changelog_synth.py --json     machine-readable summary of what was synthesized
    docs/changelog_synth.py --help     this help
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHECKPOINT_DIR = ROOT / "docs" / "checkpoints"
CHANGELOG = ROOT / "CHANGELOG.md"

BEGIN_MARKER = (
    "<!-- BEGIN toon-synth (auto-generated by docs/changelog_synth.py "
    "- do not edit by hand) -->"
)
END_MARKER = "<!-- END toon-synth -->"

# Preamble anchor: the synth block goes immediately after this line.
PREAMBLE_ANCHOR = "All notable changes to this project will be documented in this file."

DATE_RE = re.compile(r"(20\d{2}-\d{2}-\d{2})")
FILENAME_DATE_RE = re.compile(r"^(20\d{2}-\d{2}-\d{2})")
SECTIONS_RE = re.compile(r"sections\[\d+\]:\s*(.+)$", re.M)


def _first_date(text: str) -> str | None:
    m = DATE_RE.search(text or "")
    return m.group(1) if m else None


def _yaml_field(text: str, key: str) -> str:
    """Extract a top-level YAML-ish scalar field value, stripping quotes."""
    m = re.search(rf'^{re.escape(key)}:\s*(.*)$', text, re.M)
    if not m:
        return ""
    val = m.group(1).strip()
    if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
        val = val[1:-1]
    return val.strip()


def _summarize_sections(text: str) -> str:
    """For YAML-style files, summarize content.sections[N]: a,b,c as a short phrase."""
    m = SECTIONS_RE.search(text)
    if not m:
        return ""
    raw = m.group(1).strip()
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    if not parts:
        return ""
    if len(parts) <= 3:
        return "; ".join(parts)
    return "; ".join(parts[:3]) + f" (+{len(parts) - 3} more)"


def _clean_intent(intent: str) -> str:
    """Collapse whitespace/newlines and trim an intent string to one tidy line."""
    s = " ".join((intent or "").split())
    # Drop a trailing period clutter is fine; cap length for changelog tidiness.
    if len(s) > 240:
        s = s[:237].rstrip() + "..."
    return s


def parse_checkpoint(path: Path) -> dict:
    """Parse one .toon checkpoint into {date, topic, role, intent, source}."""
    text = path.read_text(encoding="utf-8", errors="ignore")
    stripped = text.lstrip()

    topic = ""
    role = ""
    intent = ""
    ts = ""

    if stripped.startswith("{"):
        # JSON-style variant.
        try:
            data = json.loads(text)
        except Exception:
            data = {}
        topic = str(data.get("topic") or data.get("slug") or "").strip()
        role = str(data.get("role") or "").strip()
        intent = str(data.get("intent") or "").strip()
        ts = str(data.get("timestamp") or "").strip()
    else:
        # YAML-style variant.
        topic = _yaml_field(text, "topic") or _yaml_field(text, "slug")
        role = _yaml_field(text, "role")
        intent = _yaml_field(text, "intent")
        ts = _yaml_field(text, "timestamp")

    # Date resolution: timestamp -> filename prefix -> mtime.
    date = _first_date(ts)
    if not date:
        fm = FILENAME_DATE_RE.match(path.name)
        date = fm.group(1) if fm else None
    if not date:
        date = datetime.fromtimestamp(
            path.stat().st_mtime, tz=timezone.utc
        ).strftime("%Y-%m-%d")

    if not topic:
        # Fall back to filename stem (minus a leading date prefix).
        stem = path.stem
        stem = FILENAME_DATE_RE.sub("", stem).lstrip("-")
        topic = stem or path.stem

    if not role:
        role = "unknown"

    description = _clean_intent(intent)
    if not description and not stripped.startswith("{"):
        description = _summarize_sections(text)
    if not description:
        description = "(checkpoint)"

    return {
        "date": date,
        "topic": topic,
        "role": role,
        "description": description,
        "source": path.name,
    }


def collect() -> list[dict]:
    """Parse every checkpoint, sorted newest-date-first then topic for stability."""
    if not CHECKPOINT_DIR.is_dir():
        return []
    entries = [parse_checkpoint(p) for p in sorted(CHECKPOINT_DIR.glob("*.toon"))]
    return entries


def build_block(entries: list[dict]) -> str:
    """Render the marker-wrapped synth block from parsed checkpoints."""
    # Group by date.
    by_date: dict[str, list[dict]] = {}
    for e in entries:
        by_date.setdefault(e["date"], []).append(e)

    lines: list[str] = []
    lines.append(BEGIN_MARKER)
    lines.append("")
    lines.append(
        "_The entries below are synthesized deterministically from the "
        f"{len(entries)} TOON checkpoints in `docs/checkpoints/`. "
        "Regenerate with `docs/changelog_synth.py`; the hand-curated "
        "history follows the END marker._"
    )
    lines.append("")

    for date in sorted(by_date.keys(), reverse=True):
        group = sorted(by_date[date], key=lambda e: e["topic"])
        lines.append(f"### [{date}] - checkpoints")
        lines.append("")
        for e in group:
            lines.append(f"- **{e['topic']}** ({e['role']}): {e['description']}")
        lines.append("")

    lines.append(END_MARKER)
    return "\n".join(lines)


def render_changelog(current: str, block: str) -> str:
    """Return CHANGELOG content with the synth block merged in idempotently.

    If markers already exist, replace ONLY the content between them.
    Otherwise insert the block after the preamble anchor line.
    Content outside the markers is preserved byte-for-byte.
    """
    begin_idx = current.find(BEGIN_MARKER)
    end_idx = current.find(END_MARKER)

    if begin_idx != -1 and end_idx != -1 and end_idx > begin_idx:
        # Replace existing block in place. Span = from BEGIN to end of END_MARKER.
        end_span = end_idx + len(END_MARKER)
        return current[:begin_idx] + block + current[end_span:]

    # No markers yet: insert after the preamble anchor.
    anchor_idx = current.find(PREAMBLE_ANCHOR)
    if anchor_idx == -1:
        # Defensive fallback: insert right after the first line (the # Changelog title).
        nl = current.find("\n")
        insert_at = nl + 1 if nl != -1 else len(current)
        return current[:insert_at] + "\n" + block + "\n" + current[insert_at:]

    # Insert after the full anchor line (advance to end of that line).
    line_end = current.find("\n", anchor_idx)
    if line_end == -1:
        line_end = len(current)
    insert_at = line_end + 1
    return current[:insert_at] + "\n" + block + "\n" + current[insert_at:]


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Merge-aware Keep-a-Changelog synthesizer for TOON checkpoints."
    )
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if CHANGELOG.md would change (CI drift gate)")
    ap.add_argument("--json", action="store_true",
                    help="machine-readable summary")
    args = ap.parse_args()

    entries = collect()
    block = build_block(entries)

    current = CHANGELOG.read_text(encoding="utf-8") if CHANGELOG.exists() else ""
    updated = render_changelog(current, block)
    would_change = updated != current

    distinct_dates = sorted({e["date"] for e in entries}, reverse=True)

    summary = {
        "script": "docs/changelog_synth.py",
        "toon_files_parsed": len(entries),
        "dated_entries_generated": len(entries),
        "distinct_dates": len(distinct_dates),
        "date_range": [distinct_dates[-1], distinct_dates[0]] if distinct_dates else [],
        "markers_present": BEGIN_MARKER in current,
        "would_change": would_change,
    }

    if args.check:
        if args.json:
            summary["check"] = True
            summary["in_sync"] = not would_change
            print(json.dumps(summary, indent=2))
        else:
            status = "DRIFT" if would_change else "IN_SYNC"
            print(f"changelog_synth --check: {status} "
                  f"({len(entries)} checkpoints, {len(distinct_dates)} dates)")
        return 1 if would_change else 0

    # Default: merge into CHANGELOG.md in place.
    if would_change:
        CHANGELOG.write_text(updated, encoding="utf-8")

    if args.json:
        summary["applied"] = would_change
        print(json.dumps(summary, indent=2))
    else:
        action = "updated" if would_change else "already in sync"
        print(f"changelog_synth: CHANGELOG.md {action} - "
              f"{len(entries)} checkpoints across {len(distinct_dates)} dates "
              f"merged inside toon-synth markers (hand-curated history preserved).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
