#!/usr/bin/env python3
"""sync_metrics.py - single source of truth for Touring workspace metrics.

Closes A03 (documentation drift) durably - Master Plan H0 (C.W2.P1.T6 / A.W1 / E.W1).
Measures crates / LOC / test functions deterministically (zero-LLM, daemon-optional)
and verifies that ARCHITECTURE.md does not drift from the measured reality.

Usage:
    docs/sync_metrics.py            human-readable metrics
    docs/sync_metrics.py --json     machine-readable JSON
    docs/sync_metrics.py --check    exit 1 if ARCHITECTURE.md crate count drifts >5%
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEST_RE = re.compile(r"#\[(?:tokio::test|test|rstest)")


def crate_count() -> int | None:
    """Authoritative crate count via cargo metadata workspace_members."""
    try:
        out = subprocess.run(
            ["cargo", "metadata", "--no-deps", "--format-version", "1"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=120,
        )
        if out.returncode == 0:
            return len(json.loads(out.stdout)["workspace_members"])
    except Exception:
        pass
    return None


def measure() -> dict:
    """Walk crates/ once, accumulating LOC, test-fn count, and hotspots."""
    loc_src = 0
    loc_ws = 0
    test_fns = 0
    biggest_file = ("", 0)
    per_crate: dict[str, int] = {}
    for path in (ROOT / "crates").rglob("*.rs"):
        sp = str(path)
        if "/target/" in sp:
            continue
        try:
            text = path.read_text(errors="ignore")
        except Exception:
            continue
        n = text.count("\n") + 1
        loc_ws += n
        test_fns += len(TEST_RE.findall(text))
        if n > biggest_file[1]:
            biggest_file = (str(path.relative_to(ROOT)), n)
        if "/src/" in sp:
            loc_src += n
            crate = sp.split("/crates/", 1)[1].split("/", 1)[0]
            per_crate[crate] = per_crate.get(crate, 0) + n
    biggest_crate = max(per_crate.items(), key=lambda kv: kv[1]) if per_crate else ("", 0)

    health = "n/a"
    try:
        out = subprocess.run(
            ["touring", "status", "-j"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=15,
        )
        if out.returncode == 0:
            health = str(json.loads(out.stdout).get("composite_health_score", "n/a"))
    except Exception:
        pass

    return {
        "crates": crate_count(),
        "loc_src": loc_src,
        "loc_workspace": loc_ws,
        "test_fns": test_fns,
        "biggest_crate": f"{biggest_crate[0]} ({biggest_crate[1]} LOC)",
        "biggest_file": f"{biggest_file[0]} ({biggest_file[1]} LOC)",
        "composite_health": health,
    }


def declared_crates() -> int | None:
    """Parse the crate count declared in the ARCHITECTURE.md header."""
    try:
        for line in (ROOT / "ARCHITECTURE.md").read_text(errors="ignore").splitlines():
            m = re.search(r"(\d+)\s+crates", line)
            if m:
                return int(m.group(1))
    except Exception:
        pass
    return None


def declared_metrics() -> dict:
    """Parse exact loc_src/loc_workspace/test_fns from the ARCHITECTURE.md METRICS comment.

    The header carries `<!-- METRICS: ... (crates=N, loc_src=N, loc_workspace=N, test_fns=N) -->`.
    Returning exact ints lets --check guard LOC/test drift (not just crate count).
    """
    out: dict[str, int] = {}
    try:
        text = (ROOT / "ARCHITECTURE.md").read_text(errors="ignore")
        for key in ("loc_src", "loc_workspace", "test_fns"):
            m = re.search(rf"{key}=(\d+)", text)
            if m:
                out[key] = int(m.group(1))
    except Exception:
        pass
    return out


# ── Generated crate inventory (DOC-02, 2026-06-13) ───────────────────────────
# The ARCHITECTURE.md *body* used to hand-list ~38 pre-decomposition crates
# (phantom touring-core/index/vfs/semantics + touring-hooks 127,575 LOC) while
# the header said 46. The old --check only matched the FIRST "N crates" (header),
# so the body drift was invisible. We now GENERATE the inventory between markers
# and --check verifies the block byte-for-byte → the body cannot drift again.
CRATES_BEGIN = "<!-- CRATES:BEGIN (generated by docs/sync_metrics.py --sync — do not edit by hand) -->"
CRATES_END = "<!-- CRATES:END -->"


def per_crate_loc() -> dict[str, int]:
    """Map each workspace crate to its src LOC (walk crates/*/src/**/*.rs once)."""
    per: dict[str, int] = {}
    for path in (ROOT / "crates").rglob("*.rs"):
        sp = str(path)
        if "/target/" in sp or "/src/" not in sp:
            continue
        try:
            n = path.read_text(errors="ignore").count("\n") + 1
        except Exception:
            continue
        crate = sp.split("/crates/", 1)[1].split("/", 1)[0]
        per[crate] = per.get(crate, 0) + n
    return per


def render_crate_inventory() -> str:
    """Render the marker-delimited crate inventory table (sorted by src LOC)."""
    per = per_crate_loc()
    total = sum(per.values()) or 1
    rows = sorted(per.items(), key=lambda kv: (-kv[1], kv[0]))
    lines = [
        CRATES_BEGIN,
        f"**{len(per)} crates · {total:,} LOC (src)** — generated by "
        "`docs/sync_metrics.py --sync`; each crate's own `ARCHITECTURE.md` carries "
        "type-level detail. Largest crate is well under the 15% single-crate ceiling.",
        "",
        "| # | crate | src LOC | % |",
        "|--:|-------|--------:|--:|",
    ]
    for i, (name, loc) in enumerate(rows, 1):
        lines.append(f"| {i} | `{name}` | {loc:,} | {100 * loc / total:.1f}% |")
    lines.append(CRATES_END)
    return "\n".join(lines)


def sync_arch() -> int:
    """Rewrite the crate-inventory block in ARCHITECTURE.md from measured reality."""
    arch = ROOT / "ARCHITECTURE.md"
    text = arch.read_text(errors="ignore")
    if CRATES_BEGIN not in text or CRATES_END not in text:
        print(
            f"sync: markers not found in ARCHITECTURE.md — add a block:\n{CRATES_BEGIN}\n{CRATES_END}",
            file=sys.stderr,
        )
        return 1
    pre = text.split(CRATES_BEGIN, 1)[0]
    post = text.split(CRATES_END, 1)[1]
    new = pre + render_crate_inventory() + post
    if new != text:
        arch.write_text(new)
        print(f"synced crate inventory into ARCHITECTURE.md ({len(per_crate_loc())} crates)")
    else:
        print("crate inventory already in sync")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Touring workspace metrics (A03 anti-drift gate).")
    ap.add_argument("--json", action="store_true", help="machine-readable JSON")
    ap.add_argument("--check", action="store_true", help="exit 1 on ARCHITECTURE.md crate/LOC/inventory drift")
    ap.add_argument("--sync", action="store_true", help="rewrite the ARCHITECTURE.md crate-inventory block from reality")
    args = ap.parse_args()

    if args.sync:
        return sync_arch()

    m = measure()

    if args.check:
        decl = declared_crates()
        real = m["crates"] or 0
        if decl is None:
            print("DRIFT: cannot parse crate count from ARCHITECTURE.md", file=sys.stderr)
            return 1
        tol = max(1, real // 20)
        if abs(decl - real) > tol:
            print(
                f"DRIFT: ARCHITECTURE.md declares {decl} crates, measured {real} (> tol {tol})",
                file=sys.stderr,
            )
            return 1
        # Extend the gate beyond crate count: LOC + test_fns drift silently slipped
        # past the old crate-only check (the exact regression this closes). Parse the
        # exact ints from the METRICS comment and guard each within 5% tolerance.
        dm = declared_metrics()
        drift = []
        for key in ("loc_src", "test_fns"):
            decl_v = dm.get(key)
            if decl_v is None:
                continue  # back-compat: tolerate a header without the METRICS comment
            real_v = int(m.get(key) or 0)
            ktol = max(1, real_v // 20)  # 5%
            if abs(decl_v - real_v) > ktol:
                drift.append(f"{key}: declared {decl_v}, measured {real_v} (> tol {ktol})")
        if drift:
            print("DRIFT: ARCHITECTURE.md METRICS stale -> " + "; ".join(drift), file=sys.stderr)
            return 1
        # DOC-02: the generated crate-inventory block must be byte-for-byte fresh.
        # This is the gate the old crate-count-only check lacked — it catches a
        # stale body (phantom crates, wrong totals) that the header alone hid.
        arch_text = (ROOT / "ARCHITECTURE.md").read_text(errors="ignore")
        if CRATES_BEGIN in arch_text and CRATES_END in arch_text:
            current = (
                CRATES_BEGIN
                + arch_text.split(CRATES_BEGIN, 1)[1].split(CRATES_END, 1)[0]
                + CRATES_END
            )
            if current.strip() != render_crate_inventory().strip():
                print(
                    "DRIFT: ARCHITECTURE.md crate inventory block is stale -> "
                    "run docs/sync_metrics.py --sync",
                    file=sys.stderr,
                )
                return 1
        print(
            f"OK: crates={real} loc_src={m['loc_src']} test_fns={m['test_fns']} inventory in sync"
        )
        return 0

    if args.json:
        print(json.dumps(m, indent=2))
        return 0

    print("Touring workspace metrics (measured in loco):")
    for key, value in m.items():
        print(f"  {key:16}: {value}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
