//! Evidence — evidence tracking and accumulation for fascicle operations
//!
//! Handles the accumulation and validation of evidence across fascicle executions.

use chrono::{DateTime, Utc};
use rustc_hash::FxHashMap;
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};

/// Thread-safe global generator for unique TypedIDs.
///
/// Initialized to start at 1 (0 is reserved for default/uninitialized IDs).
static GENERATOR: AtomicU64 = AtomicU64::new(1);

/// Unique identifier for evidence with built-in generator.
///
/// Uses an AtomicU64 generator to ensure uniqueness across all evidence instances.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct TypedID {
    /// The raw numeric value.
    value: u64,
}

impl TypedID {
    /// Creates a new unique TypedID using the global generator.
    ///
    /// Each call produces a monotonically increasing unique identifier.
    pub fn new() -> Self {
        Self {
            value: GENERATOR.fetch_add(1, Ordering::Relaxed),
        }
    }

    /// Returns the raw numeric value.
    pub fn value(&self) -> u64 {
        self.value
    }
}

impl std::fmt::Display for TypedID {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "TypedID({})", self.value)
    }
}

/// Confidence score wrapper — f64 guaranteed to be in [0, 1].
///
/// # Invariant
/// Values outside [0, 1] are clamped to the nearest bound.
#[derive(Debug, Clone, Copy, PartialEq, PartialOrd)]
pub struct Confidence(pub f64);

impl Confidence {
    /// Creates a new Confidence, clamping to [0, 1].
    pub fn new(value: f64) -> Self {
        Self(value.clamp(0.0, 1.0))
    }

    /// Returns the inner value.
    pub fn value(&self) -> f64 {
        self.0
    }
}

impl Default for Confidence {
    fn default() -> Self {
        Self(0.0)
    }
}

impl From<f64> for Confidence {
    fn from(value: f64) -> Self {
        Self::new(value)
    }
}

impl From<Confidence> for f64 {
    fn from(c: Confidence) -> Self {
        c.0
    }
}

/// Priority wrapper — u8 guaranteed to be in [0, 255].
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Default)]
pub struct Priority(pub u8);

impl Priority {
    /// Creates a new Priority, clamping to [0, 255].
    pub fn new(value: u8) -> Self {
        Self(value)
    }

    /// Returns the inner value.
    pub fn value(&self) -> u8 {
        self.0
    }
}

impl From<u8> for Priority {
    fn from(value: u8) -> Self {
        Self::new(value)
    }
}

impl From<Priority> for u8 {
    fn from(p: Priority) -> Self {
        p.0
    }
}

/// Handler name identifier — which handler generated this evidence.
///
/// Uses `Arc<str>` for efficient cloning without heap allocation.
pub type HandlerName = Arc<str>;

/// Evidence generated by a handler during fascicle execution.
///
/// Tracks provenance, confidence, and priority for downstream processing.
#[derive(Debug, Clone)]
pub struct Evidence {
    /// Unique identifier for this evidence.
    pub id: TypedID,
    /// Confidence score in [0, 1].
    pub confidence: Confidence,
    /// Priority value in [0, 255].
    pub priority: Priority,
    /// Timestamp when this evidence was generated.
    pub timestamp: DateTime<Utc>,
    /// Which handler generated this evidence.
    pub source: HandlerName,
    /// Arbitrary key-value payload from the handler.
    pub payload: FxHashMap<String, serde_json::Value>,
}

impl Evidence {
    /// Creates a new Evidence with the given parameters.
    ///
    /// The id is auto-generated to ensure uniqueness.
    #[must_use]
    pub fn new(
        confidence: Confidence,
        priority: Priority,
        source: HandlerName,
        payload: FxHashMap<String, serde_json::Value>,
    ) -> Self {
        Self {
            id: TypedID::new(),
            confidence,
            priority,
            timestamp: Utc::now(),
            source,
            payload,
        }
    }

    /// Creates a new Evidence with auto-generated ID and default confidence/priority.
    #[must_use]
    pub fn with_defaults(source: HandlerName) -> Self {
        Self {
            id: TypedID::new(),
            confidence: Confidence::default(),
            priority: Priority::default(),
            timestamp: Utc::now(),
            source,
            payload: FxHashMap::default(),
        }
    }

    /// Returns the confidence as f64 for numeric operations.
    pub fn confidence_value(&self) -> f64 {
        self.confidence.value()
    }

    /// Returns the priority as u8 for numeric operations.
    pub fn priority_value(&self) -> u8 {
        self.priority.value()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_typed_id_uniqueness() {
        let id1 = TypedID::new();
        let id2 = TypedID::new();
        assert_ne!(id1, id2);
        assert!(id2.value() > id1.value());
    }

    #[test]
    fn test_typed_id_default() {
        let id = TypedID::default();
        // Default-constructed ID has value 0
        assert_eq!(id.value(), 0);
    }

    #[test]
    fn test_confidence_clamping() {
        let c1 = Confidence::new(0.5);
        assert!((c1.value() - 0.5).abs() < f64::EPSILON);

        let c2 = Confidence::new(1.5);
        assert!((c2.value() - 1.0).abs() < f64::EPSILON);

        let c3 = Confidence::new(-0.5);
        assert!((c3.value() - 0.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_confidence_from_f64() {
        let c: Confidence = 0.75.into();
        assert!((c.value() - 0.75).abs() < f64::EPSILON);
    }

    #[test]
    fn test_priority_new() {
        let p = Priority::new(128);
        assert_eq!(p.value(), 128);
    }

    #[test]
    fn test_priority_default() {
        let p = Priority::default();
        assert_eq!(p.value(), 0);
    }

    #[test]
    fn test_handler_name_from_string() {
        let name: HandlerName = "my-handler".into();
        assert_eq!(name.as_ref(), "my-handler");
    }

    #[test]
    fn test_handler_name_arc_efficiency() {
        let name: HandlerName = "shared".into();
        let name2 = name.clone();
        // Arc should point to same allocation
        assert_eq!(name.as_ref(), name2.as_ref());
    }

    #[test]
    fn test_evidence_new() {
        let payload = FxHashMap::default();
        let e = Evidence::new(
            Confidence::new(0.9),
            Priority::new(200),
            HandlerName::from("test-handler"),
            payload,
        );
        assert!(e.confidence_value() > 0.89);
        assert_eq!(e.priority_value(), 200);
        assert_eq!(e.source.as_ref(), "test-handler");
        assert!(e.payload.is_empty(), "payload must start empty");
    }

    #[test]
    fn test_evidence_with_defaults() {
        let e = Evidence::with_defaults(HandlerName::from("auto-handler"));
        assert_eq!(e.confidence_value(), 0.0);
        assert_eq!(e.priority_value(), 0);
        assert_eq!(e.source.as_ref(), "auto-handler");
    }

    #[test]
    fn test_evidence_id_monotonic() {
        let ids: Vec<u64> = (0..10).map(|_| TypedID::new().value()).collect();
        for window in ids.windows(2) {
            assert!(window[1] > window[0]);
        }
    }
}
