//! Atomic unit of execution in a generated sequence.
//!
//! A `ToolCall` represents a single action (tool invocation) that is part
//! of a larger sequence generated by N1.

use serde::{Deserialize, Serialize};
use std::collections::{HashMap, VecDeque};

/// A single tool call within a generated sequence.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    /// Unique identifier for this tool call within the sequence.
    pub id: ToolCallId,
    /// Name of the tool to invoke.
    pub tool_name: String,
    /// Arguments to pass to the tool.
    pub arguments: ToolArguments,
    /// Ordering constraints (dependencies on other tool calls).
    pub dependencies: Vec<ToolCallId>,
    /// Expected output type (for validation).
    pub expected_output: Option<String>,
    /// Retry policy for this call.
    pub retry_policy: RetryPolicy,
    /// Whether this call can be parallelized with others.
    pub parallelizable: bool,
}

/// Unique identifier for a tool call within a sequence.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ToolCallId(pub usize);

impl ToolCallId {
    /// Construct a `ToolCallId` from a numeric id.
    pub fn new(id: usize) -> Self {
        Self(id)
    }
}

impl std::fmt::Display for ToolCallId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "TC{}", self.0)
    }
}

/// Arguments to a tool call, stored as key-value pairs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolArguments {
    /// Positional arguments (if any).
    pub positional: Vec<serde_json::Value>,
    /// Named arguments.
    pub named: std::collections::HashMap<String, serde_json::Value>,
}

impl ToolArguments {
    /// Create empty arguments.
    pub fn new() -> Self {
        Self {
            positional: Vec::new(),
            named: HashMap::new(),
        }
    }

    /// Add a positional argument.
    pub fn with_positional(mut self, value: serde_json::Value) -> Self {
        self.positional.push(value);
        self
    }

    /// Add a named argument.
    pub fn with_named(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.named.insert(key.into(), value);
        self
    }
}

impl Default for ToolArguments {
    fn default() -> Self {
        Self::new()
    }
}

/// Retry policy for a tool call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RetryPolicy {
    /// Maximum number of retries.
    pub max_retries: u8,
    /// Base delay between retries.
    pub base_delay_ms: u64,
    /// Multiplier for exponential backoff.
    pub backoff_multiplier: f64,
    /// Maximum delay cap.
    pub max_delay_ms: u64,
}

impl Default for RetryPolicy {
    fn default() -> Self {
        Self {
            max_retries: 3,
            base_delay_ms: 100,
            backoff_multiplier: 2.0,
            max_delay_ms: 5000,
        }
    }
}

impl RetryPolicy {
    /// Create a no-retry policy.
    pub fn no_retry() -> Self {
        Self {
            max_retries: 0,
            base_delay_ms: 0,
            backoff_multiplier: 1.0,
            max_delay_ms: 0,
        }
    }
}

/// Result of executing a single tool call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallResult {
    /// ID of the tool call.
    pub id: ToolCallId,
    /// Whether execution succeeded.
    pub success: bool,
    /// Output from the tool (if successful).
    pub output: Option<serde_json::Value>,
    /// Error message (if failed).
    pub error: Option<String>,
    /// Execution duration.
    pub duration_ms: u64,
    /// Whether this was a retry.
    pub was_retry: bool,
}

impl ToolCallResult {
    /// Create a successful result.
    pub fn success(id: ToolCallId, output: serde_json::Value, duration_ms: u64) -> Self {
        Self {
            id,
            success: true,
            output: Some(output),
            error: None,
            duration_ms,
            was_retry: false,
        }
    }

    /// Create a failed result.
    pub fn failure(id: ToolCallId, error: impl Into<String>, duration_ms: u64) -> Self {
        Self {
            id,
            success: false,
            output: None,
            error: Some(error.into()),
            duration_ms,
            was_retry: false,
        }
    }

    /// Create a retried result.
    pub fn retried(id: ToolCallId, output: serde_json::Value, duration_ms: u64) -> Self {
        Self {
            id,
            success: true,
            output: Some(output),
            error: None,
            duration_ms,
            was_retry: true,
        }
    }
}

// ── Internal helpers ─────────────────────────────────────────────────────────────

fn build_dependency_graph(
    calls: &[ToolCall],
) -> (
    std::collections::HashMap<ToolCallId, usize>,
    std::collections::HashMap<ToolCallId, Vec<ToolCallId>>,
) {
    let mut in_degree: std::collections::HashMap<ToolCallId, usize> = HashMap::new();
    let mut graph: std::collections::HashMap<ToolCallId, Vec<ToolCallId>> = HashMap::new();

    for call in calls {
        in_degree.insert(call.id, call.dependencies.len());
        graph.entry(call.id).or_default();
        for dep in &call.dependencies {
            graph.entry(*dep).or_default().push(call.id);
        }
    }
    (in_degree, graph)
}

fn extract_zero_degree_nodes(
    in_degree: &std::collections::HashMap<ToolCallId, usize>,
) -> VecDeque<ToolCallId> {
    let mut nodes: Vec<_> = in_degree
        .iter()
        .filter(|&(_, &d)| d == 0)
        .map(|(&id, _)| id)
        .collect();
    nodes.sort_by_key(|&id| id.0);
    nodes.into_iter().collect()
}

fn process_node(
    node: ToolCallId,
    graph: &std::collections::HashMap<ToolCallId, Vec<ToolCallId>>,
    in_degree: &mut std::collections::HashMap<ToolCallId, usize>,
    queue: &mut VecDeque<ToolCallId>,
) {
    if let Some(neighbors) = graph.get(&node) {
        for &neighbor in neighbors {
            if let Some(deg) = in_degree.get_mut(&neighbor) {
                *deg -= 1;
                if *deg == 0 {
                    queue.push_back(neighbor);
                }
            }
        }
    }
}

fn find_cycle_nodes(in_degree: &std::collections::HashMap<ToolCallId, usize>) -> Vec<ToolCallId> {
    in_degree
        .iter()
        .filter(|&(_, &d)| d > 0)
        .map(|(&id, _)| id)
        .collect()
}

/// Compute topological ordering of tool calls based on dependencies.
///
/// Returns the tool calls in dependency-respecting order, or a cycle error.
pub fn topological_order(calls: &[ToolCall]) -> Result<Vec<ToolCallId>, Vec<ToolCallId>> {
    let (mut in_degree, graph) = build_dependency_graph(calls);
    let mut queue = extract_zero_degree_nodes(&in_degree);
    let mut result = Vec::with_capacity(calls.len());

    while let Some(node) = queue.pop_front() {
        result.push(node);
        process_node(node, &graph, &mut in_degree, &mut queue);
    }

    if result.len() != calls.len() {
        Err(find_cycle_nodes(&in_degree))
    } else {
        Ok(result)
    }
}

fn compute_levels(
    ordered: &[ToolCallId],
    calls: &[ToolCall],
) -> std::collections::HashMap<ToolCallId, usize> {
    let mut levels: std::collections::HashMap<ToolCallId, usize> = HashMap::new();
    for &id in ordered {
        let call = calls
            .iter()
            .find(|c| c.id == id)
            .expect("ToolCallId must exist in calls");
        let max_dep_level = call
            .dependencies
            .iter()
            .filter_map(|&dep| levels.get(&dep).copied())
            .max()
            .unwrap_or(0);
        levels.insert(id, max_dep_level + 1);
    }
    levels
}

fn group_by_level(levels: &std::collections::HashMap<ToolCallId, usize>) -> Vec<Vec<ToolCallId>> {
    let mut groups: std::collections::HashMap<usize, Vec<ToolCallId>> = HashMap::new();
    for (&id, &level) in levels {
        groups.entry(level).or_default().push(id);
    }
    let mut result: Vec<Vec<ToolCallId>> = groups.into_values().collect();
    result.sort_by_key(|g: &Vec<ToolCallId>| g.first().map(|id| id.0).unwrap_or(0));
    for group in &mut result {
        group.sort_by_key(|id: &ToolCallId| id.0);
    }
    result
}

/// Compute parallel groups (tool calls that can execute concurrently).
pub fn parallel_groups(calls: &[ToolCall]) -> Vec<Vec<ToolCallId>> {
    let ordered = match topological_order(calls) {
        Ok(o) => o,
        Err(cycle) => cycle,
    };
    let levels = compute_levels(&ordered, calls);
    group_by_level(&levels)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_topological_order_linear() {
        let calls = vec![
            ToolCall {
                id: ToolCallId::new(0),
                tool_name: "read".into(),
                arguments: ToolArguments::new(),
                dependencies: vec![],
                expected_output: None,
                retry_policy: RetryPolicy::default(),
                parallelizable: false,
            },
            ToolCall {
                id: ToolCallId::new(1),
                tool_name: "edit".into(),
                arguments: ToolArguments::new(),
                dependencies: vec![ToolCallId::new(0)],
                expected_output: None,
                retry_policy: RetryPolicy::default(),
                parallelizable: false,
            },
            ToolCall {
                id: ToolCallId::new(2),
                tool_name: "write".into(),
                arguments: ToolArguments::new(),
                dependencies: vec![ToolCallId::new(1)],
                expected_output: None,
                retry_policy: RetryPolicy::default(),
                parallelizable: false,
            },
        ];

        let result = topological_order(&calls).unwrap();
        assert_eq!(
            result,
            vec![ToolCallId::new(0), ToolCallId::new(1), ToolCallId::new(2)]
        );
    }

    #[test]
    fn test_topological_order_parallel() {
        let calls = vec![
            ToolCall {
                id: ToolCallId::new(0),
                tool_name: "read_a".into(),
                arguments: ToolArguments::new(),
                dependencies: vec![],
                expected_output: None,
                retry_policy: RetryPolicy::default(),
                parallelizable: true,
            },
            ToolCall {
                id: ToolCallId::new(1),
                tool_name: "read_b".into(),
                arguments: ToolArguments::new(),
                dependencies: vec![],
                expected_output: None,
                retry_policy: RetryPolicy::default(),
                parallelizable: true,
            },
            ToolCall {
                id: ToolCallId::new(2),
                tool_name: "merge".into(),
                arguments: ToolArguments::new(),
                dependencies: vec![ToolCallId::new(0), ToolCallId::new(1)],
                expected_output: None,
                retry_policy: RetryPolicy::default(),
                parallelizable: false,
            },
        ];

        let result = topological_order(&calls).unwrap();
        assert_eq!(result[0], ToolCallId::new(0));
        assert_eq!(result[1], ToolCallId::new(1));
        assert_eq!(result[2], ToolCallId::new(2));
    }

    #[test]
    fn test_parallel_groups() {
        let calls = vec![
            ToolCall {
                id: ToolCallId::new(0),
                tool_name: "read_a".into(),
                arguments: ToolArguments::new(),
                dependencies: vec![],
                expected_output: None,
                retry_policy: RetryPolicy::default(),
                parallelizable: true,
            },
            ToolCall {
                id: ToolCallId::new(1),
                tool_name: "read_b".into(),
                arguments: ToolArguments::new(),
                dependencies: vec![],
                expected_output: None,
                retry_policy: RetryPolicy::default(),
                parallelizable: true,
            },
            ToolCall {
                id: ToolCallId::new(2),
                tool_name: "merge".into(),
                arguments: ToolArguments::new(),
                dependencies: vec![ToolCallId::new(0), ToolCallId::new(1)],
                expected_output: None,
                retry_policy: RetryPolicy::default(),
                parallelizable: false,
            },
        ];

        let groups = parallel_groups(&calls);
        assert_eq!(groups.len(), 2); // Level 1: [0,1], Level 2: [2]
        assert_eq!(groups[0].len(), 2);
        assert_eq!(groups[1].len(), 1);
    }
}
